from typing import NamedTuple, Optional, Dict

from BaseClasses import Item, ItemClassification
from .Names import ItemName
from .Options import LHP2Options


# from .Options import LHP2Options


class LHP2Item(Item):
    game: str = "Lego Harry Potter 5-7"


class LHP2ItemData(NamedTuple):
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    # qty: int = 1


base_item_id = 400000

# 0 - 212
character_item_table: Dict[str, LHP2ItemData] = {
    ItemName.hagrid_play: LHP2ItemData(base_item_id + 0),
    ItemName.fang_play: LHP2ItemData(base_item_id + 1),
    ItemName.hagrid_wed_play: LHP2ItemData(base_item_id + 2),
    ItemName.prof_flit_play: LHP2ItemData(base_item_id + 3),
    ItemName.madam_malk_play: LHP2ItemData(base_item_id + 4),
    ItemName.dobby_play: LHP2ItemData(base_item_id + 5),
    ItemName.kreacher_play: LHP2ItemData(base_item_id + 6),
    ItemName.tr_orphanage_play: LHP2ItemData(base_item_id + 7),
    ItemName.bogrod_play: LHP2ItemData(base_item_id + 8),
    ItemName.mund_fletch_play: LHP2ItemData(base_item_id + 9),
    ItemName.griphook_play: LHP2ItemData(base_item_id + 10),
    ItemName.prof_mcgon_play: LHP2ItemData(base_item_id + 11),
    ItemName.madam_pince_play: LHP2ItemData(base_item_id + 12),
    ItemName.prof_sprout_play: LHP2ItemData(base_item_id + 13),
    ItemName.madam_pomfrey_play: LHP2ItemData(base_item_id + 14),
    ItemName.prof_trelawney_play: LHP2ItemData(base_item_id + 15),
    ItemName.madam_rosmerta_play: LHP2ItemData(base_item_id + 16),
    ItemName.fat_friar_play: LHP2ItemData(base_item_id + 17),
    ItemName.grey_lady_play: LHP2ItemData(base_item_id + 18),
    ItemName.fat_lady_play: LHP2ItemData(base_item_id + 19),
    ItemName.herm_ball_play: LHP2ItemData(base_item_id + 20),
    ItemName.bellatrix_play: LHP2ItemData(base_item_id + 21),
    ItemName.emmeline_play: LHP2ItemData(base_item_id + 22),
    ItemName.narcissa_play: LHP2ItemData(base_item_id + 23),
    ItemName.mcgon_pyjamas_play: LHP2ItemData(base_item_id + 24),
    ItemName.mary_cattermole_play: LHP2ItemData(base_item_id + 25),
    ItemName.mcgon_black_play: LHP2ItemData(base_item_id + 26),
    ItemName.herm_gringotts_play: LHP2ItemData(base_item_id + 27),
    ItemName.prof_grubbly_play: LHP2ItemData(base_item_id + 28),
    ItemName.bellatrix_azka_play: LHP2ItemData(base_item_id + 29),
    ItemName.death_eater_play: LHP2ItemData(base_item_id + 30),
    ItemName.dudley_grey_play: LHP2ItemData(base_item_id + 31),
    ItemName.prof_dumble_play: LHP2ItemData(base_item_id + 32),
    ItemName.harry_play: LHP2ItemData(base_item_id + 33),
    ItemName.herm_play: LHP2ItemData(base_item_id + 34),
    ItemName.argus_play: LHP2ItemData(base_item_id + 35),
    ItemName.madam_hooch_play: LHP2ItemData(base_item_id + 36),
    ItemName.crabbe_play: LHP2ItemData(base_item_id + 37),
    ItemName.goyle_play: LHP2ItemData(base_item_id + 38),
    ItemName.ginny_play: LHP2ItemData(base_item_id + 39),
    ItemName.arthur_play: LHP2ItemData(base_item_id + 40),
    ItemName.katie_play: LHP2ItemData(base_item_id + 41),
    ItemName.lily_play: LHP2ItemData(base_item_id + 42),
    ItemName.bloody_baron_play: LHP2ItemData(base_item_id + 43),
    ItemName.fudge_play: LHP2ItemData(base_item_id + 44),
    ItemName.justin_play: LHP2ItemData(base_item_id + 45),
    ItemName.cho_play: LHP2ItemData(base_item_id + 46),
    ItemName.dean_play: LHP2ItemData(base_item_id + 47),
    ItemName.draco_play: LHP2ItemData(base_item_id + 48),
    ItemName.lucius_play: LHP2ItemData(base_item_id + 49),
    ItemName.draco_suit_play: LHP2ItemData(base_item_id + 50),
    ItemName.custom_a_play: LHP2ItemData(base_item_id + 51),
    ItemName.custom_b_play: LHP2ItemData(base_item_id + 52),
    ItemName.custom_c_play: LHP2ItemData(base_item_id + 53),
    ItemName.custom_d_play: LHP2ItemData(base_item_id + 54),
    ItemName.custom_e_play: LHP2ItemData(base_item_id + 55),
    ItemName.custom_g_play: LHP2ItemData(base_item_id + 56),
    ItemName.custom_h_play: LHP2ItemData(base_item_id + 57),
    ItemName.custom_i_play: LHP2ItemData(base_item_id + 58),
    ItemName.custom_j_play: LHP2ItemData(base_item_id + 59),
    ItemName.harry_pyjamas_play: LHP2ItemData(base_item_id + 60),
    ItemName.myrtle_play: LHP2ItemData(base_item_id + 61),
    ItemName.james_ghost_play: LHP2ItemData(base_item_id + 62),
    ItemName.madeye_play: LHP2ItemData(base_item_id + 63),
    ItemName.hannah_play: LHP2ItemData(base_item_id + 64),
    ItemName.custom_f_play: LHP2ItemData(base_item_id + 65),
    ItemName.kingsley_play: LHP2ItemData(base_item_id + 66),
    ItemName.aberforth_play: LHP2ItemData(base_item_id + 67),
    ItemName.runcorn_play: LHP2ItemData(base_item_id + 68),
    ItemName.alecto_play: LHP2ItemData(base_item_id + 69),
    ItemName.amycus_play: LHP2ItemData(base_item_id + 70),
    ItemName.anthony_play: LHP2ItemData(base_item_id + 71),
    ItemName.bathilda_snake_play: LHP2ItemData(base_item_id + 72),
    ItemName.blaise_play: LHP2ItemData(base_item_id + 73),
    ItemName.charity_play: LHP2ItemData(base_item_id + 74),
    ItemName.charlie_play: LHP2ItemData(base_item_id + 75),
    ItemName.cormac_play: LHP2ItemData(base_item_id + 76),
    ItemName.dedalus_play: LHP2ItemData(base_item_id + 77),
    ItemName.dirk_play: LHP2ItemData(base_item_id + 78),
    ItemName.dolohov_play: LHP2ItemData(base_item_id + 79),
    ItemName.dragomir_play: LHP2ItemData(base_item_id + 80),
    ItemName.elphias_play: LHP2ItemData(base_item_id + 81),
    ItemName.fenrir_play: LHP2ItemData(base_item_id + 82),
    ItemName.grindel_young_play: LHP2ItemData(base_item_id + 83),
    ItemName.grindel_old_play: LHP2ItemData(base_item_id + 84),
    ItemName.gregorovitch_play: LHP2ItemData(base_item_id + 85),
    ItemName.hestia_play: LHP2ItemData(base_item_id + 86),
    ItemName.prof_slughorn_play: LHP2ItemData(base_item_id + 87),
    ItemName.james_young_play: LHP2ItemData(base_item_id + 88),
    ItemName.lavender_play: LHP2ItemData(base_item_id + 89),
    ItemName.mafalda_play: LHP2ItemData(base_item_id + 90),
    ItemName.belby_play: LHP2ItemData(base_item_id + 91),
    ItemName.luna_purple_coat_play: LHP2ItemData(base_item_id + 92),
    ItemName.herm_grey_coat_play: LHP2ItemData(base_item_id + 93),
    ItemName.harry_godric_play: LHP2ItemData(base_item_id + 94),
    ItemName.prof_umbridge_play: LHP2ItemData(base_item_id + 95),
    ItemName.fred_play: LHP2ItemData(base_item_id + 96),
    ItemName.george_play: LHP2ItemData(base_item_id + 97),
    ItemName.molly_apron_play: LHP2ItemData(base_item_id + 98),
    ItemName.crabbe_jumper_play: LHP2ItemData(base_item_id + 99),
    ItemName.draco_sweater_play: LHP2ItemData(base_item_id + 100),
    ItemName.goyle_jumper_play: LHP2ItemData(base_item_id + 101),
    ItemName.milk_man_play: LHP2ItemData(base_item_id + 102),
    ItemName.twin_2_play: LHP2ItemData(base_item_id + 103),
    ItemName.herm_mafalda_play: LHP2ItemData(base_item_id + 104),
    ItemName.ministry_guard_play: LHP2ItemData(base_item_id + 105),
    ItemName.harry_winter_play: LHP2ItemData(base_item_id + 106),
    ItemName.arthur_torn_suit_play: LHP2ItemData(base_item_id + 107),
    ItemName.fred_winter_play: LHP2ItemData(base_item_id + 108),
    ItemName.cho_winter_play: LHP2ItemData(base_item_id + 109),
    ItemName.george_winter_play: LHP2ItemData(base_item_id + 110),
    ItemName.herm_scarf_play: LHP2ItemData(base_item_id + 111),
    ItemName.luna_blue_jumper_play: LHP2ItemData(base_item_id + 112),
    ItemName.fred_owls_play: LHP2ItemData(base_item_id + 113),
    ItemName.fred_pyjamas_play: LHP2ItemData(base_item_id + 114),
    ItemName.george_owls_play: LHP2ItemData(base_item_id + 115),
    ItemName.george_pyjamas_play: LHP2ItemData(base_item_id + 116),
    ItemName.herm_jumper_play: LHP2ItemData(base_item_id + 117),
    ItemName.fudge_wizengamot_play: LHP2ItemData(base_item_id + 118),
    ItemName.dudley_play: LHP2ItemData(base_item_id + 119),
    ItemName.gang_mem_play: LHP2ItemData(base_item_id + 120),
    ItemName.harry_albert_runcorn_play: LHP2ItemData(base_item_id + 121),
    ItemName.harry_brown_jacket_play: LHP2ItemData(base_item_id + 122),
    ItemName.dumble_cursed_play: LHP2ItemData(base_item_id + 123),
    ItemName.lucius_death_eater_play: LHP2ItemData(base_item_id + 124),
    ItemName.luna_play: LHP2ItemData(base_item_id + 125),
    ItemName.umbridge_wizengamot_play: LHP2ItemData(base_item_id + 126),
    ItemName.dolohov_workman_play: LHP2ItemData(base_item_id + 127),
    ItemName.michael_play: LHP2ItemData(base_item_id + 128),
    ItemName.dean_winter_play: LHP2ItemData(base_item_id + 129),
    ItemName.arthur_cardigan_play: LHP2ItemData(base_item_id + 130),
    ItemName.luna_pink_dress_play: LHP2ItemData(base_item_id + 131),
    ItemName.marietta_play: LHP2ItemData(base_item_id + 132),
    ItemName.dumble_young_play: LHP2ItemData(base_item_id + 133),
    ItemName.slughorn_young_play: LHP2ItemData(base_item_id + 134),
    ItemName.slughorn_pajamas_play: LHP2ItemData(base_item_id + 135),
    ItemName.lily_young_casual_play: LHP2ItemData(base_item_id + 136),
    ItemName.ginny_dress_play: LHP2ItemData(base_item_id + 137),
    ItemName.ginny_pyjamas_play: LHP2ItemData(base_item_id + 138),
    ItemName.blaise_black_shirt_play: LHP2ItemData(base_item_id + 139),
    ItemName.cormac_suit_play: LHP2ItemData(base_item_id + 140),
    ItemName.muggle_orphan_play: LHP2ItemData(base_item_id + 141),
    ItemName.luna_overalls_play: LHP2ItemData(base_item_id + 142),
    ItemName.molly_play: LHP2ItemData(base_item_id + 143),
    ItemName.herm_cardigan_play: LHP2ItemData(base_item_id + 144),
    ItemName.luna_yellow_dress_play: LHP2ItemData(base_item_id + 145),
    ItemName.dudley_shirt_play: LHP2ItemData(base_item_id + 146),
    ItemName.bill_wedding_play: LHP2ItemData(base_item_id + 147),
    ItemName.fleur_play: LHP2ItemData(base_item_id + 148),
    ItemName.herm_red_dress_play: LHP2ItemData(base_item_id + 149),
    ItemName.figg_play: LHP2ItemData(base_item_id + 150),
    ItemName.harry_locket_play: LHP2ItemData(base_item_id + 151),
    ItemName.twin_1_play: LHP2ItemData(base_item_id + 152),
    ItemName.cole_play: LHP2ItemData(base_item_id + 153),
    ItemName.herm_ministry_play: LHP2ItemData(base_item_id + 154),
    ItemName.arthur_suit_play: LHP2ItemData(base_item_id + 155),
    ItemName.harry_christmas_play: LHP2ItemData(base_item_id + 156),
    ItemName.ernie_play: LHP2ItemData(base_item_id + 157),
    ItemName.prof_snape_play: LHP2ItemData(base_item_id + 158),
    ItemName.neville_play: LHP2ItemData(base_item_id + 159),
    ItemName.ron_play: LHP2ItemData(base_item_id + 160),
    ItemName.ron_quidditch_play: LHP2ItemData(base_item_id + 161),
    ItemName.vernon_play: LHP2ItemData(base_item_id + 162),
    ItemName.tom_riddle_play: LHP2ItemData(base_item_id + 163),
    ItemName.sirius_black_play: LHP2ItemData(base_item_id + 164),
    ItemName.remus_lupin_play: LHP2ItemData(base_item_id + 165),
    ItemName.wormtail_play: LHP2ItemData(base_item_id + 166),
    ItemName.rita_skeeter_play: LHP2ItemData(base_item_id + 167),
    ItemName.padma_patil_play: LHP2ItemData(base_item_id + 168),
    ItemName.station_guard_play: LHP2ItemData(base_item_id + 169),
    ItemName.prof_binns_play: LHP2ItemData(base_item_id + 170),
    ItemName.penelope_play: LHP2ItemData(base_item_id + 171),
    ItemName.susan_play: LHP2ItemData(base_item_id + 172),
    ItemName.tonks_play: LHP2ItemData(base_item_id + 173),
    ItemName.pius_play: LHP2ItemData(base_item_id + 174),
    ItemName.reg_play: LHP2ItemData(base_item_id + 175),
    ItemName.regulus_play: LHP2ItemData(base_item_id + 176),
    ItemName.scrimgeour_play: LHP2ItemData(base_item_id + 177),
    ItemName.scabior_play: LHP2ItemData(base_item_id + 178),
    ItemName.xeno_play: LHP2ItemData(base_item_id + 179),
    ItemName.yaxley_play: LHP2ItemData(base_item_id + 180),
    ItemName.zacharias_play: LHP2ItemData(base_item_id + 181),
    ItemName.waitress_treats_play: LHP2ItemData(base_item_id + 182),
    ItemName.lord_voldemort_play: LHP2ItemData(base_item_id + 183),
    ItemName.ron_blue_pyjamas_play: LHP2ItemData(base_item_id + 184),
    ItemName.neville_cardigan_play: LHP2ItemData(base_item_id + 185),
    ItemName.neville_pyjamas_play: LHP2ItemData(base_item_id + 186),
    ItemName.percy_play: LHP2ItemData(base_item_id + 187),
    ItemName.sirius_azkaban_play: LHP2ItemData(base_item_id + 188),
    ItemName.black_play: LHP2ItemData(base_item_id + 189),
    ItemName.xeno_luna_play: LHP2ItemData(base_item_id + 190),
    ItemName.ron_reg_cattermole_play: LHP2ItemData(base_item_id + 191),
    ItemName.tonks_pink_coat_play: LHP2ItemData(base_item_id + 192),
    ItemName.ron_winter_clothes_play: LHP2ItemData(base_item_id + 193),
    ItemName.snape_underwear_play: LHP2ItemData(base_item_id + 194),
    ItemName.rowle_play: LHP2ItemData(base_item_id + 195),
    ItemName.petunia_play: LHP2ItemData(base_item_id + 196),
    ItemName.neville_tank_top_play: LHP2ItemData(base_item_id + 197),
    ItemName.neville_winter_play: LHP2ItemData(base_item_id + 198),
    ItemName.parvati_play: LHP2ItemData(base_item_id + 199),
    ItemName.ron_red_sweater_play: LHP2ItemData(base_item_id + 200),
    ItemName.olivander_play: LHP2ItemData(base_item_id + 201),
    ItemName.seamus_winter_play: LHP2ItemData(base_item_id + 202),
    ItemName.ron_underwear_play: LHP2ItemData(base_item_id + 203),
    ItemName.ron_wedding_play: LHP2ItemData(base_item_id + 204),
    ItemName.waitress_luchino_play: LHP2ItemData(base_item_id + 205),
    ItemName.petunia_green_coat_play: LHP2ItemData(base_item_id + 206),
    ItemName.seamus_play: LHP2ItemData(base_item_id + 207),
    ItemName.snatcher_play: LHP2ItemData(base_item_id + 208),
    ItemName.ron_green_shirt_play: LHP2ItemData(base_item_id + 209),
    ItemName.neville_waiter_play: LHP2ItemData(base_item_id + 210),
    ItemName.xeno_wedding_play: LHP2ItemData(base_item_id + 211),
    ItemName.skeleton_play: LHP2ItemData(base_item_id + 212),
}

# 213 - 425
character_token_item_table: Dict[str, LHP2ItemData] = {
    ItemName.hagrid_token: LHP2ItemData(base_item_id + 213),
    ItemName.fang_token: LHP2ItemData(base_item_id + 214),
    ItemName.hagrid_wed_token: LHP2ItemData(base_item_id + 215),
    ItemName.prof_flit_token: LHP2ItemData(base_item_id + 216),
    ItemName.madam_malk_token: LHP2ItemData(base_item_id + 217),
    ItemName.dobby_token: LHP2ItemData(base_item_id + 218),
    ItemName.kreacher_token: LHP2ItemData(base_item_id + 219),
    ItemName.tr_orphanage_token: LHP2ItemData(base_item_id + 220),
    ItemName.bogrod_token: LHP2ItemData(base_item_id + 221),
    ItemName.mund_fletch_token: LHP2ItemData(base_item_id + 222),
    ItemName.griphook_token: LHP2ItemData(base_item_id + 223),
    ItemName.prof_mcgon_token: LHP2ItemData(base_item_id + 224),
    ItemName.madam_pince_token: LHP2ItemData(base_item_id + 225),
    ItemName.prof_sprout_token: LHP2ItemData(base_item_id + 226),
    ItemName.madam_pomfrey_token: LHP2ItemData(base_item_id + 227),
    ItemName.prof_trelawney_token: LHP2ItemData(base_item_id + 228),
    ItemName.madam_rosmerta_token: LHP2ItemData(base_item_id + 229),
    ItemName.fat_friar_token: LHP2ItemData(base_item_id + 230),
    ItemName.grey_lady_token: LHP2ItemData(base_item_id + 231),
    ItemName.fat_lady_token: LHP2ItemData(base_item_id + 232),
    ItemName.herm_ball_token: LHP2ItemData(base_item_id + 233),
    ItemName.bellatrix_token: LHP2ItemData(base_item_id + 234),
    ItemName.emmeline_token: LHP2ItemData(base_item_id + 235),
    ItemName.narcissa_token: LHP2ItemData(base_item_id + 236),
    ItemName.mcgon_pyjamas_token: LHP2ItemData(base_item_id + 237),
    ItemName.mary_cattermole_token: LHP2ItemData(base_item_id + 238),
    ItemName.mcgon_black_token: LHP2ItemData(base_item_id + 239),
    ItemName.herm_gringotts_token: LHP2ItemData(base_item_id + 240),
    ItemName.prof_grubbly_token: LHP2ItemData(base_item_id + 241),
    ItemName.bellatrix_azka_token: LHP2ItemData(base_item_id + 242),
    ItemName.death_eater_token: LHP2ItemData(base_item_id + 243),
    ItemName.dudley_grey_token: LHP2ItemData(base_item_id + 244),
    ItemName.prof_dumble_token: LHP2ItemData(base_item_id + 245),
    ItemName.harry_token: LHP2ItemData(base_item_id + 246),
    ItemName.herm_token: LHP2ItemData(base_item_id + 247),
    ItemName.argus_token: LHP2ItemData(base_item_id + 248),
    ItemName.madam_hooch_token: LHP2ItemData(base_item_id + 249),
    ItemName.crabbe_token: LHP2ItemData(base_item_id + 250),
    ItemName.goyle_token: LHP2ItemData(base_item_id + 251),
    ItemName.ginny_token: LHP2ItemData(base_item_id + 252),
    ItemName.arthur_token: LHP2ItemData(base_item_id + 253),
    ItemName.katie_token: LHP2ItemData(base_item_id + 254),
    ItemName.lily_token: LHP2ItemData(base_item_id + 255),
    ItemName.bloody_baron_token: LHP2ItemData(base_item_id + 256),
    ItemName.fudge_token: LHP2ItemData(base_item_id + 257),
    ItemName.justin_token: LHP2ItemData(base_item_id + 258),
    ItemName.cho_token: LHP2ItemData(base_item_id + 259),
    ItemName.dean_token: LHP2ItemData(base_item_id + 260),
    ItemName.draco_token: LHP2ItemData(base_item_id + 261),
    ItemName.lucius_token: LHP2ItemData(base_item_id + 262),
    ItemName.draco_suit_token: LHP2ItemData(base_item_id + 263),
    ItemName.custom_a_token: LHP2ItemData(base_item_id + 264),
    ItemName.custom_b_token: LHP2ItemData(base_item_id + 265),
    ItemName.custom_c_token: LHP2ItemData(base_item_id + 266),
    ItemName.custom_d_token: LHP2ItemData(base_item_id + 267),
    ItemName.custom_e_token: LHP2ItemData(base_item_id + 268),
    ItemName.custom_g_token: LHP2ItemData(base_item_id + 269),
    ItemName.custom_h_token: LHP2ItemData(base_item_id + 270),
    ItemName.custom_i_token: LHP2ItemData(base_item_id + 271),
    ItemName.custom_j_token: LHP2ItemData(base_item_id + 272),
    ItemName.harry_pyjamas_token: LHP2ItemData(base_item_id + 273),
    ItemName.myrtle_token: LHP2ItemData(base_item_id + 274),
    ItemName.james_ghost_token: LHP2ItemData(base_item_id + 275),
    ItemName.madeye_token: LHP2ItemData(base_item_id + 276),
    ItemName.hannah_token: LHP2ItemData(base_item_id + 277),
    ItemName.custom_f_token: LHP2ItemData(base_item_id + 278),
    ItemName.kingsley_token: LHP2ItemData(base_item_id + 279),
    ItemName.aberforth_token: LHP2ItemData(base_item_id + 280),
    ItemName.runcorn_token: LHP2ItemData(base_item_id + 281),
    ItemName.alecto_token: LHP2ItemData(base_item_id + 282),
    ItemName.amycus_token: LHP2ItemData(base_item_id + 283),
    ItemName.anthony_token: LHP2ItemData(base_item_id + 284),
    ItemName.bathilda_snake_token: LHP2ItemData(base_item_id + 285),
    ItemName.blaise_token: LHP2ItemData(base_item_id + 286),
    ItemName.charity_token: LHP2ItemData(base_item_id + 287),
    ItemName.charlie_token: LHP2ItemData(base_item_id + 288),
    ItemName.cormac_token: LHP2ItemData(base_item_id + 289),
    ItemName.dedalus_token: LHP2ItemData(base_item_id + 290),
    ItemName.dirk_token: LHP2ItemData(base_item_id + 291),
    ItemName.dolohov_token: LHP2ItemData(base_item_id + 292),
    ItemName.dragomir_token: LHP2ItemData(base_item_id + 293),
    ItemName.elphias_token: LHP2ItemData(base_item_id + 294),
    ItemName.fenrir_token: LHP2ItemData(base_item_id + 295),
    ItemName.grindel_young_token: LHP2ItemData(base_item_id + 296),
    ItemName.grindel_old_token: LHP2ItemData(base_item_id + 297),
    ItemName.gregorovitch_token: LHP2ItemData(base_item_id + 298),
    ItemName.hestia_token: LHP2ItemData(base_item_id + 299),
    ItemName.prof_slughorn_token: LHP2ItemData(base_item_id + 300),
    ItemName.james_young_token: LHP2ItemData(base_item_id + 301),
    ItemName.lavender_token: LHP2ItemData(base_item_id + 302),
    ItemName.mafalda_token: LHP2ItemData(base_item_id + 303),
    ItemName.belby_token: LHP2ItemData(base_item_id + 304),
    ItemName.luna_purple_coat_token: LHP2ItemData(base_item_id + 305),
    ItemName.herm_grey_coat_token: LHP2ItemData(base_item_id + 306),
    ItemName.harry_godric_token: LHP2ItemData(base_item_id + 307),
    ItemName.prof_umbridge_token: LHP2ItemData(base_item_id + 308),
    ItemName.fred_token: LHP2ItemData(base_item_id + 309),
    ItemName.george_token: LHP2ItemData(base_item_id + 310),
    ItemName.molly_apron_token: LHP2ItemData(base_item_id + 311),
    ItemName.crabbe_jumper_token: LHP2ItemData(base_item_id + 312),
    ItemName.draco_sweater_token: LHP2ItemData(base_item_id + 313),
    ItemName.goyle_jumper_token: LHP2ItemData(base_item_id + 314),
    ItemName.milk_man_token: LHP2ItemData(base_item_id + 315),
    ItemName.twin_2_token: LHP2ItemData(base_item_id + 316),
    ItemName.herm_mafalda_token: LHP2ItemData(base_item_id + 317),
    ItemName.ministry_guard_token: LHP2ItemData(base_item_id + 318),
    ItemName.harry_winter_token: LHP2ItemData(base_item_id + 319),
    ItemName.arthur_torn_suit_token: LHP2ItemData(base_item_id + 320),
    ItemName.fred_winter_token: LHP2ItemData(base_item_id + 321),
    ItemName.cho_winter_token: LHP2ItemData(base_item_id + 322),
    ItemName.george_winter_token: LHP2ItemData(base_item_id + 323),
    ItemName.herm_scarf_token: LHP2ItemData(base_item_id + 324),
    ItemName.luna_blue_jumper_token: LHP2ItemData(base_item_id + 325),
    ItemName.fred_owls_token: LHP2ItemData(base_item_id + 326),
    ItemName.fred_pyjamas_token: LHP2ItemData(base_item_id + 327),
    ItemName.george_owls_token: LHP2ItemData(base_item_id + 328),
    ItemName.george_pyjamas_token: LHP2ItemData(base_item_id + 329),
    ItemName.herm_jumper_token: LHP2ItemData(base_item_id + 330),
    ItemName.fudge_wizengamot_token: LHP2ItemData(base_item_id + 331),
    ItemName.dudley_token: LHP2ItemData(base_item_id + 332),
    ItemName.gang_mem_token: LHP2ItemData(base_item_id + 333),
    ItemName.harry_albert_runcorn_token: LHP2ItemData(base_item_id + 334),
    ItemName.harry_brown_jacket_token: LHP2ItemData(base_item_id + 335),
    ItemName.dumble_cursed_token: LHP2ItemData(base_item_id + 336),
    ItemName.lucius_death_eater_token: LHP2ItemData(base_item_id + 337),
    ItemName.luna_token: LHP2ItemData(base_item_id + 338),
    ItemName.umbridge_wizengamot_token: LHP2ItemData(base_item_id + 339),
    ItemName.dolohov_workman_token: LHP2ItemData(base_item_id + 340),
    ItemName.michael_token: LHP2ItemData(base_item_id + 341),
    ItemName.dean_winter_token: LHP2ItemData(base_item_id + 342),
    ItemName.arthur_cardigan_token: LHP2ItemData(base_item_id + 343),
    ItemName.luna_pink_dress_token: LHP2ItemData(base_item_id + 344),
    ItemName.marietta_token: LHP2ItemData(base_item_id + 345),
    ItemName.dumble_young_token: LHP2ItemData(base_item_id + 346),
    ItemName.slughorn_young_token: LHP2ItemData(base_item_id + 347),
    ItemName.slughorn_pajamas_token: LHP2ItemData(base_item_id + 348),
    ItemName.lily_young_casual_token: LHP2ItemData(base_item_id + 349),
    ItemName.ginny_dress_token: LHP2ItemData(base_item_id + 350),
    ItemName.ginny_pyjamas_token: LHP2ItemData(base_item_id + 351),
    ItemName.blaise_black_shirt_token: LHP2ItemData(base_item_id + 352),
    ItemName.cormac_suit_token: LHP2ItemData(base_item_id + 353),
    ItemName.muggle_orphan_token: LHP2ItemData(base_item_id + 354),
    ItemName.luna_overalls_token: LHP2ItemData(base_item_id + 355),
    ItemName.molly_token: LHP2ItemData(base_item_id + 356),
    ItemName.herm_cardigan_token: LHP2ItemData(base_item_id + 357),
    ItemName.luna_yellow_dress_token: LHP2ItemData(base_item_id + 358),
    ItemName.dudley_shirt_token: LHP2ItemData(base_item_id + 359),
    ItemName.bill_wedding_token: LHP2ItemData(base_item_id + 360),
    ItemName.fleur_token: LHP2ItemData(base_item_id + 361),
    ItemName.herm_red_dress_token: LHP2ItemData(base_item_id + 362),
    ItemName.figg_token: LHP2ItemData(base_item_id + 363),
    ItemName.harry_locket_token: LHP2ItemData(base_item_id + 364),
    ItemName.twin_1_token: LHP2ItemData(base_item_id + 365),
    ItemName.cole_token: LHP2ItemData(base_item_id + 366),
    ItemName.herm_ministry_token: LHP2ItemData(base_item_id + 367),
    ItemName.arthur_suit_token: LHP2ItemData(base_item_id + 368),
    ItemName.harry_christmas_token: LHP2ItemData(base_item_id + 369),
    ItemName.ernie_token: LHP2ItemData(base_item_id + 370),
    ItemName.prof_snape_token: LHP2ItemData(base_item_id + 371),
    ItemName.neville_token: LHP2ItemData(base_item_id + 372),
    ItemName.ron_token: LHP2ItemData(base_item_id + 373),
    ItemName.ron_quidditch_token: LHP2ItemData(base_item_id + 374),
    ItemName.vernon_token: LHP2ItemData(base_item_id + 375),
    ItemName.tom_riddle_token: LHP2ItemData(base_item_id + 376),
    ItemName.sirius_black_token: LHP2ItemData(base_item_id + 377),
    ItemName.remus_lupin_token: LHP2ItemData(base_item_id + 378),
    ItemName.wormtail_token: LHP2ItemData(base_item_id + 379),
    ItemName.rita_skeeter_token: LHP2ItemData(base_item_id + 380),
    ItemName.padma_patil_token: LHP2ItemData(base_item_id + 381),
    ItemName.station_guard_token: LHP2ItemData(base_item_id + 382),
    ItemName.prof_binns_token: LHP2ItemData(base_item_id + 383),
    ItemName.penelope_token: LHP2ItemData(base_item_id + 384),
    ItemName.susan_token: LHP2ItemData(base_item_id + 385),
    ItemName.tonks_token: LHP2ItemData(base_item_id + 386),
    ItemName.pius_token: LHP2ItemData(base_item_id + 387),
    ItemName.reg_token: LHP2ItemData(base_item_id + 388),
    ItemName.regulus_token: LHP2ItemData(base_item_id + 389),
    ItemName.scrimgeour_token: LHP2ItemData(base_item_id + 390),
    ItemName.scabior_token: LHP2ItemData(base_item_id + 391),
    ItemName.xeno_token: LHP2ItemData(base_item_id + 392),
    ItemName.yaxley_token: LHP2ItemData(base_item_id + 393),
    ItemName.zacharias_token: LHP2ItemData(base_item_id + 394),
    ItemName.waitress_treats_token: LHP2ItemData(base_item_id + 395),
    ItemName.lord_voldemort_token: LHP2ItemData(base_item_id + 396),
    ItemName.ron_blue_pyjamas_token: LHP2ItemData(base_item_id + 397),
    ItemName.neville_cardigan_token: LHP2ItemData(base_item_id + 398),
    ItemName.neville_pyjamas_token: LHP2ItemData(base_item_id + 399),
    ItemName.percy_token: LHP2ItemData(base_item_id + 400),
    ItemName.sirius_azkaban_token: LHP2ItemData(base_item_id + 401),
    ItemName.black_token: LHP2ItemData(base_item_id + 402),
    ItemName.xeno_luna_token: LHP2ItemData(base_item_id + 403),
    ItemName.ron_reg_cattermole_token: LHP2ItemData(base_item_id + 404),
    ItemName.tonks_pink_coat_token: LHP2ItemData(base_item_id + 405),
    ItemName.ron_winter_clothes_token: LHP2ItemData(base_item_id + 406),
    ItemName.snape_underwear_token: LHP2ItemData(base_item_id + 407),
    ItemName.rowle_token: LHP2ItemData(base_item_id + 408),
    ItemName.petunia_token: LHP2ItemData(base_item_id + 409),
    ItemName.neville_tank_top_token: LHP2ItemData(base_item_id + 410),
    ItemName.neville_winter_token: LHP2ItemData(base_item_id + 411),
    ItemName.parvati_token: LHP2ItemData(base_item_id + 412),
    ItemName.ron_red_sweater_token: LHP2ItemData(base_item_id + 413),
    ItemName.olivander_token: LHP2ItemData(base_item_id + 414),
    ItemName.seamus_winter_token: LHP2ItemData(base_item_id + 415),
    ItemName.ron_underwear_token: LHP2ItemData(base_item_id + 416),
    ItemName.ron_wedding_token: LHP2ItemData(base_item_id + 417),
    ItemName.waitress_luchino_token: LHP2ItemData(base_item_id + 418),
    ItemName.petunia_green_coat_token: LHP2ItemData(base_item_id + 419),
    ItemName.seamus_token: LHP2ItemData(base_item_id + 420),
    ItemName.snatcher_token: LHP2ItemData(base_item_id + 421),
    ItemName.ron_green_shirt_token: LHP2ItemData(base_item_id + 422),
    ItemName.neville_waiter_token: LHP2ItemData(base_item_id + 423),
    ItemName.xeno_wedding_token: LHP2ItemData(base_item_id + 424),
    ItemName.skeleton_token: LHP2ItemData(base_item_id + 425),
}

# 450 - 473
level_unlock_item_table: Dict[str, LHP2ItemData] = {
    ItemName.dt_unlock: LHP2ItemData(base_item_id + 450, ItemClassification.progression),
    ItemName.da_unlock: LHP2ItemData(base_item_id + 451, ItemClassification.progression),
    ItemName.foc_unlock: LHP2ItemData(base_item_id + 452, ItemClassification.progression),
    ItemName.kd_unlock: LHP2ItemData(base_item_id + 453, ItemClassification.progression),
    ItemName.agv_unlock: LHP2ItemData(base_item_id + 454, ItemClassification.progression),
    ItemName.avt_unlock: LHP2ItemData(base_item_id + 455, ItemClassification.progression),
    ItemName.oor_unlock: LHP2ItemData(base_item_id + 456, ItemClassification.progression),
    ItemName.jd_unlock: LHP2ItemData(base_item_id + 457, ItemClassification.progression),
    ItemName.ansmc_unlock: LHP2ItemData(base_item_id + 458, ItemClassification.progression),
    ItemName.lh_unlock: LHP2ItemData(base_item_id + 459, ItemClassification.progression),
    ItemName.ff_unlock: LHP2ItemData(base_item_id + 460, ItemClassification.progression),
    ItemName.thath_unlock: LHP2ItemData(base_item_id + 461, ItemClassification.progression),
    ItemName.tsh_unlock: LHP2ItemData(base_item_id + 462, ItemClassification.progression),
    ItemName.mim_unlock: LHP2ItemData(base_item_id + 463, ItemClassification.progression),
    ItemName.igd_unlock: LHP2ItemData(base_item_id + 464, ItemClassification.progression),
    ItemName.sal_unlock: LHP2ItemData(base_item_id + 465, ItemClassification.progression),
    ItemName.ll_unlock: LHP2ItemData(base_item_id + 466, ItemClassification.progression),
    ItemName.dob_unlock: LHP2ItemData(base_item_id + 467, ItemClassification.progression),
    ItemName.ttd_unlock: LHP2ItemData(base_item_id + 468, ItemClassification.progression),
    ItemName.bts_unlock: LHP2ItemData(base_item_id + 469, ItemClassification.progression),
    ItemName.bb_unlock: LHP2ItemData(base_item_id + 470, ItemClassification.progression),
    ItemName.fiend_unlock: LHP2ItemData(base_item_id + 471, ItemClassification.progression),
    ItemName.st_unlock: LHP2ItemData(base_item_id + 472, ItemClassification.progression),
    ItemName.tfitp_unlock: LHP2ItemData(base_item_id + 473, ItemClassification.progression),
}

# 475 - 535 (to verify totals since there are extras)
sip_item_table: Dict[str, LHP2ItemData] = {
    ItemName.dt_sip: LHP2ItemData(base_item_id + 475),
    ItemName.da_sip: LHP2ItemData(base_item_id + 476),
    ItemName.foc_sip: LHP2ItemData(base_item_id + 477),
    ItemName.kd_sip: LHP2ItemData(base_item_id + 478),
    ItemName.agv_sip: LHP2ItemData(base_item_id + 479),
    ItemName.avt_sip: LHP2ItemData(base_item_id + 480),
    ItemName.oor_sip: LHP2ItemData(base_item_id + 481),
    ItemName.jd_sip: LHP2ItemData(base_item_id + 482),
    ItemName.ansmc_sip: LHP2ItemData(base_item_id + 483),
    ItemName.lh_sip: LHP2ItemData(base_item_id + 484),
    ItemName.ff_sip: LHP2ItemData(base_item_id + 485),
    ItemName.thath_sip: LHP2ItemData(base_item_id + 486),
    ItemName.tsh_sip: LHP2ItemData(base_item_id + 487),
    ItemName.mim_sip: LHP2ItemData(base_item_id + 488),
    ItemName.igd_sip: LHP2ItemData(base_item_id + 489),
    ItemName.sal_sip: LHP2ItemData(base_item_id + 490),
    ItemName.ll_sip: LHP2ItemData(base_item_id + 491),
    ItemName.dob_sip: LHP2ItemData(base_item_id + 492),
    ItemName.ttd_sip: LHP2ItemData(base_item_id + 493),
    ItemName.bts_sip: LHP2ItemData(base_item_id + 494),
    ItemName.bb_sip: LHP2ItemData(base_item_id + 495),
    ItemName.fiend_sip: LHP2ItemData(base_item_id + 496),
    ItemName.st_sip: LHP2ItemData(base_item_id + 497),
    ItemName.tfitp_sip: LHP2ItemData(base_item_id + 498),
}

# 550 - 525
house_crest_item_table: Dict[str, LHP2ItemData] = {
    # Gryff Crests
    ItemName.dt_gc: LHP2ItemData(base_item_id + 550),
    ItemName.da_gc: LHP2ItemData(base_item_id + 551),
    ItemName.foc_gc: LHP2ItemData(base_item_id + 552),
    ItemName.kd_gc: LHP2ItemData(base_item_id + 553),
    ItemName.agv_gc: LHP2ItemData(base_item_id + 554),
    ItemName.avt_gc: LHP2ItemData(base_item_id + 555),
    ItemName.oor_gc: LHP2ItemData(base_item_id + 556),
    ItemName.jd_gc: LHP2ItemData(base_item_id + 557),
    ItemName.ansmc_gc: LHP2ItemData(base_item_id + 558),
    ItemName.lh_gc: LHP2ItemData(base_item_id + 559),
    ItemName.ff_gc: LHP2ItemData(base_item_id + 560),
    ItemName.thath_gc: LHP2ItemData(base_item_id + 561),
    ItemName.tsh_gc: LHP2ItemData(base_item_id + 562),
    ItemName.mim_gc: LHP2ItemData(base_item_id + 563),
    ItemName.igd_gc: LHP2ItemData(base_item_id + 564),
    ItemName.sal_gc: LHP2ItemData(base_item_id + 565),
    ItemName.ll_gc: LHP2ItemData(base_item_id + 566),
    ItemName.dob_gc: LHP2ItemData(base_item_id + 567),
    ItemName.ttd_gc: LHP2ItemData(base_item_id + 568),
    ItemName.bts_gc: LHP2ItemData(base_item_id + 569),
    ItemName.bb_gc: LHP2ItemData(base_item_id + 570),
    ItemName.fiend_gc: LHP2ItemData(base_item_id + 571),
    ItemName.st_gc: LHP2ItemData(base_item_id + 572),
    ItemName.tfitp_gc: LHP2ItemData(base_item_id + 573),
    # Slyth Crests
    ItemName.dt_sc: LHP2ItemData(base_item_id + 574),
    ItemName.da_sc: LHP2ItemData(base_item_id + 575),
    ItemName.foc_sc: LHP2ItemData(base_item_id + 576),
    ItemName.kd_sc: LHP2ItemData(base_item_id + 577),
    ItemName.agv_sc: LHP2ItemData(base_item_id + 578),
    ItemName.avt_sc: LHP2ItemData(base_item_id + 579),
    ItemName.oor_sc: LHP2ItemData(base_item_id + 580),
    ItemName.jd_sc: LHP2ItemData(base_item_id + 581),
    ItemName.ansmc_sc: LHP2ItemData(base_item_id + 582),
    ItemName.lh_sc: LHP2ItemData(base_item_id + 583),
    ItemName.ff_sc: LHP2ItemData(base_item_id + 584),
    ItemName.thath_sc: LHP2ItemData(base_item_id + 585),
    ItemName.tsh_sc: LHP2ItemData(base_item_id + 586),
    ItemName.mim_sc: LHP2ItemData(base_item_id + 587),
    ItemName.igd_sc: LHP2ItemData(base_item_id + 588),
    ItemName.sal_sc: LHP2ItemData(base_item_id + 589),
    ItemName.ll_sc: LHP2ItemData(base_item_id + 590),
    ItemName.dob_sc: LHP2ItemData(base_item_id + 591),
    ItemName.ttd_sc: LHP2ItemData(base_item_id + 592),
    ItemName.bts_sc: LHP2ItemData(base_item_id + 593),
    ItemName.bb_sc: LHP2ItemData(base_item_id + 594),
    ItemName.fiend_sc: LHP2ItemData(base_item_id + 595),
    ItemName.st_sc: LHP2ItemData(base_item_id + 596),
    ItemName.tfitp_sc: LHP2ItemData(base_item_id + 597),
    # Raven Crests
    ItemName.dt_rc: LHP2ItemData(base_item_id + 598),
    ItemName.da_rc: LHP2ItemData(base_item_id + 599),
    ItemName.foc_rc: LHP2ItemData(base_item_id + 600),
    ItemName.kd_rc: LHP2ItemData(base_item_id + 601),
    ItemName.agv_rc: LHP2ItemData(base_item_id + 602),
    ItemName.avt_rc: LHP2ItemData(base_item_id + 603),
    ItemName.oor_rc: LHP2ItemData(base_item_id + 604),
    ItemName.jd_rc: LHP2ItemData(base_item_id + 605),
    ItemName.ansmc_rc: LHP2ItemData(base_item_id + 606),
    ItemName.lh_rc: LHP2ItemData(base_item_id + 607),
    ItemName.ff_rc: LHP2ItemData(base_item_id + 608),
    ItemName.thath_rc: LHP2ItemData(base_item_id + 609),
    ItemName.tsh_rc: LHP2ItemData(base_item_id + 610),
    ItemName.mim_rc: LHP2ItemData(base_item_id + 611),
    ItemName.igd_rc: LHP2ItemData(base_item_id + 612),
    ItemName.sal_rc: LHP2ItemData(base_item_id + 613),
    ItemName.ll_rc: LHP2ItemData(base_item_id + 614),
    ItemName.dob_rc: LHP2ItemData(base_item_id + 615),
    ItemName.ttd_rc: LHP2ItemData(base_item_id + 616),
    ItemName.bts_rc: LHP2ItemData(base_item_id + 617),
    ItemName.bb_rc: LHP2ItemData(base_item_id + 618),
    ItemName.fiend_rc: LHP2ItemData(base_item_id + 619),
    ItemName.st_rc: LHP2ItemData(base_item_id + 620),
    ItemName.tfitp_rc: LHP2ItemData(base_item_id + 621),
    # Huffle Crests
    ItemName.dt_hc: LHP2ItemData(base_item_id + 622),
    ItemName.da_hc: LHP2ItemData(base_item_id + 623),
    ItemName.foc_hc: LHP2ItemData(base_item_id + 624),
    ItemName.kd_hc: LHP2ItemData(base_item_id + 625),
    ItemName.agv_hc: LHP2ItemData(base_item_id + 626),
    ItemName.avt_hc: LHP2ItemData(base_item_id + 627),
    ItemName.oor_hc: LHP2ItemData(base_item_id + 628),
    ItemName.jd_hc: LHP2ItemData(base_item_id + 629),
    ItemName.ansmc_hc: LHP2ItemData(base_item_id + 630),
    ItemName.lh_hc: LHP2ItemData(base_item_id + 631),
    ItemName.ff_hc: LHP2ItemData(base_item_id + 632),
    ItemName.thath_hc: LHP2ItemData(base_item_id + 633),
    ItemName.tsh_hc: LHP2ItemData(base_item_id + 634),
    ItemName.mim_hc: LHP2ItemData(base_item_id + 635),
    ItemName.igd_hc: LHP2ItemData(base_item_id + 636),
    ItemName.sal_hc: LHP2ItemData(base_item_id + 637),
    ItemName.ll_hc: LHP2ItemData(base_item_id + 638),
    ItemName.dob_hc: LHP2ItemData(base_item_id + 639),
    ItemName.ttd_hc: LHP2ItemData(base_item_id + 640),
    ItemName.bts_hc: LHP2ItemData(base_item_id + 641),
    ItemName.bb_hc: LHP2ItemData(base_item_id + 642),
    ItemName.fiend_hc: LHP2ItemData(base_item_id + 643),
    ItemName.st_hc: LHP2ItemData(base_item_id + 644),
    ItemName.tfitp_hc: LHP2ItemData(base_item_id + 645),
}

# 650 - 673
# House Crest Completed

# 675 - 698
true_wizard_item_table: Dict[str, LHP2ItemData] = {
    ItemName.dt_tw: LHP2ItemData(base_item_id + 675),
    ItemName.da_tw: LHP2ItemData(base_item_id + 676),
    ItemName.foc_tw: LHP2ItemData(base_item_id + 677),
    ItemName.kd_tw: LHP2ItemData(base_item_id + 678),
    ItemName.agv_tw: LHP2ItemData(base_item_id + 679),
    ItemName.avt_tw: LHP2ItemData(base_item_id + 680),
    ItemName.oor_tw: LHP2ItemData(base_item_id + 681),
    ItemName.jd_tw: LHP2ItemData(base_item_id + 682),
    ItemName.ansmc_tw: LHP2ItemData(base_item_id + 683),
    ItemName.lh_tw: LHP2ItemData(base_item_id + 684),
    ItemName.ff_tw: LHP2ItemData(base_item_id + 685),
    ItemName.thath_tw: LHP2ItemData(base_item_id + 686),
    ItemName.tsh_tw: LHP2ItemData(base_item_id + 687),
    ItemName.mim_tw: LHP2ItemData(base_item_id + 688),
    ItemName.igd_tw: LHP2ItemData(base_item_id + 689),
    ItemName.sal_tw: LHP2ItemData(base_item_id + 690),
    ItemName.ll_tw: LHP2ItemData(base_item_id + 691),
    ItemName.dob_tw: LHP2ItemData(base_item_id + 692),
    ItemName.ttd_tw: LHP2ItemData(base_item_id + 693),
    ItemName.bts_tw: LHP2ItemData(base_item_id + 694),
    ItemName.bb_tw: LHP2ItemData(base_item_id + 695),
    ItemName.fiend_tw: LHP2ItemData(base_item_id + 696),
    ItemName.st_tw: LHP2ItemData(base_item_id + 697),
    ItemName.tfitp_tw: LHP2ItemData(base_item_id + 698),
}

item_data_table = {
    **character_item_table,
    **character_token_item_table,
    **level_unlock_item_table,
    **sip_item_table,
    **house_crest_item_table,
    **true_wizard_item_table,
}


def setup_items(options: LHP2Options):
    temp_item_table = {}
    temp_item_table.update(character_item_table)
    temp_item_table.update(character_token_item_table)
    temp_item_table.update(level_unlock_item_table)
    temp_item_table.update(sip_item_table)
    temp_item_table.update(house_crest_item_table)
    temp_item_table.update(true_wizard_item_table)
    return temp_item_table
