from dataclasses import dataclass
from typing import Optional, Dict

from BaseClasses import Item, ItemClassification
from .Names import ItemName
from .Options import LHP2Options


class LHP2Item(Item):
    game: str = "Lego Harry Potter 5-7"


@dataclass
class LHP2ItemData:
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    qty: int = 1


base_item_id = 400000
ItmClasDeprioSkip = ItemClassification.progression_deprioritized_skip_balancing

# 0 - 212
character_item_table: Dict[str, LHP2ItemData] = {
    ItemName.hagrid_play: LHP2ItemData(base_item_id + 0, ItmClasDeprioSkip),
    ItemName.fang_play: LHP2ItemData(base_item_id + 1, ItmClasDeprioSkip),
    ItemName.hagrid_wed_play: LHP2ItemData(base_item_id + 2, ItmClasDeprioSkip),
    ItemName.prof_flit_play: LHP2ItemData(base_item_id + 3),
    ItemName.madam_malk_play: LHP2ItemData(base_item_id + 4),
    ItemName.dobby_play: LHP2ItemData(base_item_id + 5),
    ItemName.kreacher_play: LHP2ItemData(base_item_id + 6),
    ItemName.tr_orphanage_play: LHP2ItemData(base_item_id + 7),
    ItemName.bogrod_play: LHP2ItemData(base_item_id + 8, ItmClasDeprioSkip),
    ItemName.mund_fletch_play: LHP2ItemData(base_item_id + 9),
    ItemName.griphook_play: LHP2ItemData(base_item_id + 10, ItmClasDeprioSkip),
    ItemName.prof_mcgon_play: LHP2ItemData(base_item_id + 11),
    ItemName.madam_pince_play: LHP2ItemData(base_item_id + 12),
    ItemName.prof_sprout_play: LHP2ItemData(base_item_id + 13),
    ItemName.madam_pomfrey_play: LHP2ItemData(base_item_id + 14),
    ItemName.prof_trelawney_play: LHP2ItemData(base_item_id + 15),
    ItemName.madam_rosmerta_play: LHP2ItemData(base_item_id + 16),
    ItemName.fat_friar_play: LHP2ItemData(base_item_id + 17),
    ItemName.grey_lady_play: LHP2ItemData(base_item_id + 18),
    ItemName.fat_lady_play: LHP2ItemData(base_item_id + 19),
    ItemName.herm_ball_play: LHP2ItemData(base_item_id + 20),
    ItemName.bellatrix_play: LHP2ItemData(base_item_id + 21, ItmClasDeprioSkip),
    ItemName.emmeline_play: LHP2ItemData(base_item_id + 22),
    ItemName.narcissa_play: LHP2ItemData(base_item_id + 23),
    ItemName.mcgon_pyjamas_play: LHP2ItemData(base_item_id + 24),
    ItemName.mary_cattermole_play: LHP2ItemData(base_item_id + 25),
    ItemName.mcgon_black_play: LHP2ItemData(base_item_id + 26),
    ItemName.herm_gringotts_play: LHP2ItemData(base_item_id + 27),
    ItemName.prof_grubbly_play: LHP2ItemData(base_item_id + 28),
    ItemName.bellatrix_azka_play: LHP2ItemData(base_item_id + 29, ItmClasDeprioSkip),
    ItemName.death_eater_play: LHP2ItemData(base_item_id + 30, ItmClasDeprioSkip),
    ItemName.dudley_grey_play: LHP2ItemData(base_item_id + 31, ItmClasDeprioSkip),
    ItemName.prof_dumble_play: LHP2ItemData(base_item_id + 32),
    # ItemName.harry_play: LHP2ItemData(base_item_id + 33),
    # ItemName.herm_play: LHP2ItemData(base_item_id + 34),
    ItemName.argus_play: LHP2ItemData(base_item_id + 35),
    ItemName.madam_hooch_play: LHP2ItemData(base_item_id + 36),
    ItemName.crabbe_play: LHP2ItemData(base_item_id + 37),
    ItemName.goyle_play: LHP2ItemData(base_item_id + 38),
    ItemName.ginny_play: LHP2ItemData(base_item_id + 39),
    ItemName.arthur_play: LHP2ItemData(base_item_id + 40, ItmClasDeprioSkip),
    ItemName.katie_play: LHP2ItemData(base_item_id + 41),
    ItemName.lily_play: LHP2ItemData(base_item_id + 42),
    ItemName.bloody_baron_play: LHP2ItemData(base_item_id + 43),
    ItemName.fudge_play: LHP2ItemData(base_item_id + 44),
    ItemName.justin_play: LHP2ItemData(base_item_id + 45),
    ItemName.cho_play: LHP2ItemData(base_item_id + 46, ItmClasDeprioSkip),
    ItemName.dean_play: LHP2ItemData(base_item_id + 47),
    ItemName.draco_play: LHP2ItemData(base_item_id + 48),
    ItemName.lucius_play: LHP2ItemData(base_item_id + 49, ItmClasDeprioSkip),
    ItemName.draco_suit_play: LHP2ItemData(base_item_id + 50),
    # ItemName.custom_a_play: LHP2ItemData(base_item_id + 51),
    # ItemName.custom_b_play: LHP2ItemData(base_item_id + 52),
    # ItemName.custom_c_play: LHP2ItemData(base_item_id + 53),
    # ItemName.custom_d_play: LHP2ItemData(base_item_id + 54),
    # ItemName.custom_e_play: LHP2ItemData(base_item_id + 55),
    # ItemName.custom_g_play: LHP2ItemData(base_item_id + 56),
    # ItemName.custom_h_play: LHP2ItemData(base_item_id + 57),
    # ItemName.custom_i_play: LHP2ItemData(base_item_id + 58),
    # ItemName.custom_j_play: LHP2ItemData(base_item_id + 59),
    ItemName.harry_pyjamas_play: LHP2ItemData(base_item_id + 60),
    ItemName.myrtle_play: LHP2ItemData(base_item_id + 61),
    ItemName.james_ghost_play: LHP2ItemData(base_item_id + 62),
    ItemName.madeye_play: LHP2ItemData(base_item_id + 63),
    ItemName.hannah_play: LHP2ItemData(base_item_id + 64),
    # ItemName.custom_f_play: LHP2ItemData(base_item_id + 65),
    ItemName.kingsley_play: LHP2ItemData(base_item_id + 66),
    ItemName.aberforth_play: LHP2ItemData(base_item_id + 67),
    ItemName.runcorn_play: LHP2ItemData(base_item_id + 68),
    ItemName.alecto_play: LHP2ItemData(base_item_id + 69, ItmClasDeprioSkip),
    ItemName.amycus_play: LHP2ItemData(base_item_id + 70, ItmClasDeprioSkip),
    ItemName.anthony_play: LHP2ItemData(base_item_id + 71),
    ItemName.bathilda_snake_play: LHP2ItemData(base_item_id + 72),
    ItemName.blaise_play: LHP2ItemData(base_item_id + 73),
    ItemName.charity_play: LHP2ItemData(base_item_id + 74),
    ItemName.charlie_play: LHP2ItemData(base_item_id + 75),
    ItemName.cormac_play: LHP2ItemData(base_item_id + 76),
    ItemName.dedalus_play: LHP2ItemData(base_item_id + 77),
    ItemName.dirk_play: LHP2ItemData(base_item_id + 78),
    ItemName.dolohov_play: LHP2ItemData(base_item_id + 79, ItmClasDeprioSkip),
    ItemName.dragomir_play: LHP2ItemData(base_item_id + 80),
    ItemName.elphias_play: LHP2ItemData(base_item_id + 81),
    ItemName.fenrir_play: LHP2ItemData(base_item_id + 82, ItmClasDeprioSkip),
    ItemName.grindel_young_play: LHP2ItemData(base_item_id + 83, ItmClasDeprioSkip),
    ItemName.grindel_old_play: LHP2ItemData(base_item_id + 84, ItmClasDeprioSkip),
    ItemName.gregorovitch_play: LHP2ItemData(base_item_id + 85),
    ItemName.hestia_play: LHP2ItemData(base_item_id + 86),
    ItemName.prof_slughorn_play: LHP2ItemData(base_item_id + 87),
    ItemName.james_young_play: LHP2ItemData(base_item_id + 88),
    ItemName.lavender_play: LHP2ItemData(base_item_id + 89),
    ItemName.mafalda_play: LHP2ItemData(base_item_id + 90),
    ItemName.belby_play: LHP2ItemData(base_item_id + 91, ItmClasDeprioSkip),
    ItemName.luna_purple_coat_play: LHP2ItemData(base_item_id + 92, ItmClasDeprioSkip),
    ItemName.herm_grey_coat_play: LHP2ItemData(base_item_id + 93),
    ItemName.harry_godric_play: LHP2ItemData(base_item_id + 94),
    ItemName.prof_umbridge_play: LHP2ItemData(base_item_id + 95),
    ItemName.fred_play: LHP2ItemData(base_item_id + 96),
    ItemName.george_play: LHP2ItemData(base_item_id + 97),
    ItemName.molly_apron_play: LHP2ItemData(base_item_id + 98),
    ItemName.crabbe_jumper_play: LHP2ItemData(base_item_id + 99),
    ItemName.draco_sweater_play: LHP2ItemData(base_item_id + 100),
    ItemName.goyle_jumper_play: LHP2ItemData(base_item_id + 101),
    ItemName.milk_man_play: LHP2ItemData(base_item_id + 102),
    ItemName.twin_2_play: LHP2ItemData(base_item_id + 103),
    ItemName.herm_mafalda_play: LHP2ItemData(base_item_id + 104),
    ItemName.ministry_guard_play: LHP2ItemData(base_item_id + 105),
    ItemName.harry_winter_play: LHP2ItemData(base_item_id + 106),
    ItemName.arthur_torn_suit_play: LHP2ItemData(base_item_id + 107, ItmClasDeprioSkip),
    ItemName.fred_winter_play: LHP2ItemData(base_item_id + 108),
    ItemName.cho_winter_play: LHP2ItemData(base_item_id + 109, ItmClasDeprioSkip),
    ItemName.george_winter_play: LHP2ItemData(base_item_id + 110),
    ItemName.herm_scarf_play: LHP2ItemData(base_item_id + 111),
    ItemName.luna_blue_jumper_play: LHP2ItemData(base_item_id + 112, ItmClasDeprioSkip),
    ItemName.fred_owls_play: LHP2ItemData(base_item_id + 113),
    ItemName.fred_pyjamas_play: LHP2ItemData(base_item_id + 114),
    ItemName.george_owls_play: LHP2ItemData(base_item_id + 115),
    ItemName.george_pyjamas_play: LHP2ItemData(base_item_id + 116),
    ItemName.herm_jumper_play: LHP2ItemData(base_item_id + 117),
    ItemName.fudge_wizengamot_play: LHP2ItemData(base_item_id + 118),
    ItemName.dudley_play: LHP2ItemData(base_item_id + 119, ItmClasDeprioSkip),
    ItemName.gang_mem_play: LHP2ItemData(base_item_id + 120),
    ItemName.harry_albert_runcorn_play: LHP2ItemData(base_item_id + 121),
    ItemName.harry_brown_jacket_play: LHP2ItemData(base_item_id + 122),
    ItemName.dumble_cursed_play: LHP2ItemData(base_item_id + 123),
    ItemName.lucius_death_eater_play: LHP2ItemData(base_item_id + 124, ItmClasDeprioSkip),
    ItemName.luna_play: LHP2ItemData(base_item_id + 125, ItmClasDeprioSkip),
    ItemName.umbridge_wizengamot_play: LHP2ItemData(base_item_id + 126),
    ItemName.dolohov_workman_play: LHP2ItemData(base_item_id + 127, ItmClasDeprioSkip),
    ItemName.michael_play: LHP2ItemData(base_item_id + 128),
    ItemName.dean_winter_play: LHP2ItemData(base_item_id + 129),
    ItemName.arthur_cardigan_play: LHP2ItemData(base_item_id + 130, ItmClasDeprioSkip),
    ItemName.luna_pink_dress_play: LHP2ItemData(base_item_id + 131, ItmClasDeprioSkip),
    ItemName.marietta_play: LHP2ItemData(base_item_id + 132),
    ItemName.dumble_young_play: LHP2ItemData(base_item_id + 133),
    ItemName.slughorn_young_play: LHP2ItemData(base_item_id + 134),
    ItemName.slughorn_pyjamas_play: LHP2ItemData(base_item_id + 135),
    ItemName.lily_young_casual_play: LHP2ItemData(base_item_id + 136),
    ItemName.ginny_dress_play: LHP2ItemData(base_item_id + 137),
    ItemName.ginny_pyjamas_play: LHP2ItemData(base_item_id + 138),
    ItemName.blaise_black_shirt_play: LHP2ItemData(base_item_id + 139),
    ItemName.cormac_suit_play: LHP2ItemData(base_item_id + 140),
    ItemName.muggle_orphan_play: LHP2ItemData(base_item_id + 141),
    ItemName.luna_overalls_play: LHP2ItemData(base_item_id + 142, ItmClasDeprioSkip),
    ItemName.molly_play: LHP2ItemData(base_item_id + 143),
    ItemName.herm_cardigan_play: LHP2ItemData(base_item_id + 144),
    ItemName.luna_yellow_dress_play: LHP2ItemData(base_item_id + 145, ItmClasDeprioSkip),
    ItemName.dudley_shirt_play: LHP2ItemData(base_item_id + 146, ItmClasDeprioSkip),
    ItemName.bill_wedding_play: LHP2ItemData(base_item_id + 147),
    ItemName.fleur_play: LHP2ItemData(base_item_id + 148),
    ItemName.herm_red_dress_play: LHP2ItemData(base_item_id + 149),
    ItemName.figg_play: LHP2ItemData(base_item_id + 150),
    ItemName.harry_locket_play: LHP2ItemData(base_item_id + 151),
    ItemName.twin_1_play: LHP2ItemData(base_item_id + 152),
    ItemName.cole_play: LHP2ItemData(base_item_id + 153, ItmClasDeprioSkip),
    ItemName.herm_ministry_play: LHP2ItemData(base_item_id + 154),
    ItemName.arthur_suit_play: LHP2ItemData(base_item_id + 155, ItmClasDeprioSkip),
    ItemName.harry_christmas_play: LHP2ItemData(base_item_id + 156),
    ItemName.ernie_play: LHP2ItemData(base_item_id + 157),
    ItemName.prof_snape_play: LHP2ItemData(base_item_id + 158),
    ItemName.neville_play: LHP2ItemData(base_item_id + 159),
    # ItemName.ron_play: LHP2ItemData(base_item_id + 160),
    ItemName.ron_quidditch_play: LHP2ItemData(base_item_id + 161),
    ItemName.vernon_play: LHP2ItemData(base_item_id + 162, ItmClasDeprioSkip),
    ItemName.tom_riddle_play: LHP2ItemData(base_item_id + 163, ItmClasDeprioSkip),
    ItemName.sirius_black_play: LHP2ItemData(base_item_id + 164, ItmClasDeprioSkip),
    ItemName.remus_lupin_play: LHP2ItemData(base_item_id + 165, ItmClasDeprioSkip),
    ItemName.wormtail_play: LHP2ItemData(base_item_id + 166, ItmClasDeprioSkip),
    ItemName.rita_skeeter_play: LHP2ItemData(base_item_id + 167),
    ItemName.padma_patil_play: LHP2ItemData(base_item_id + 168, ItmClasDeprioSkip),
    ItemName.station_guard_play: LHP2ItemData(base_item_id + 169),
    ItemName.prof_binns_play: LHP2ItemData(base_item_id + 170),
    ItemName.penelope_play: LHP2ItemData(base_item_id + 171, ItmClasDeprioSkip),
    ItemName.susan_play: LHP2ItemData(base_item_id + 172),
    ItemName.tonks_play: LHP2ItemData(base_item_id + 173),
    ItemName.pius_play: LHP2ItemData(base_item_id + 174, ItmClasDeprioSkip),
    ItemName.reg_play: LHP2ItemData(base_item_id + 175),
    ItemName.regulus_play: LHP2ItemData(base_item_id + 176),
    ItemName.scrimgeour_play: LHP2ItemData(base_item_id + 177),
    ItemName.scabior_play: LHP2ItemData(base_item_id + 178, ItmClasDeprioSkip),
    ItemName.xeno_play: LHP2ItemData(base_item_id + 179),
    ItemName.yaxley_play: LHP2ItemData(base_item_id + 180, ItmClasDeprioSkip),
    ItemName.zacharias_play: LHP2ItemData(base_item_id + 181),
    ItemName.waitress_treats_play: LHP2ItemData(base_item_id + 182),
    ItemName.lord_voldemort_play: LHP2ItemData(base_item_id + 183, ItemClassification.progression),
    ItemName.ron_blue_pyjamas_play: LHP2ItemData(base_item_id + 184),
    ItemName.neville_cardigan_play: LHP2ItemData(base_item_id + 185),
    ItemName.neville_pyjamas_play: LHP2ItemData(base_item_id + 186),
    ItemName.percy_play: LHP2ItemData(base_item_id + 187),
    ItemName.sirius_azkaban_play: LHP2ItemData(base_item_id + 188, ItmClasDeprioSkip),
    ItemName.black_play: LHP2ItemData(base_item_id + 189, ItmClasDeprioSkip),
    ItemName.xeno_luna_play: LHP2ItemData(base_item_id + 190),
    ItemName.ron_reg_cattermole_play: LHP2ItemData(base_item_id + 191),
    ItemName.tonks_pink_coat_play: LHP2ItemData(base_item_id + 192),
    ItemName.ron_winter_clothes_play: LHP2ItemData(base_item_id + 193),
    ItemName.snape_underwear_play: LHP2ItemData(base_item_id + 194),
    ItemName.rowle_play: LHP2ItemData(base_item_id + 195, ItmClasDeprioSkip),
    ItemName.petunia_play: LHP2ItemData(base_item_id + 196),
    ItemName.neville_tank_top_play: LHP2ItemData(base_item_id + 197),
    ItemName.neville_winter_play: LHP2ItemData(base_item_id + 198),
    ItemName.parvati_play: LHP2ItemData(base_item_id + 199),
    ItemName.ron_red_sweater_play: LHP2ItemData(base_item_id + 200),
    ItemName.ollivander_play: LHP2ItemData(base_item_id + 201),
    ItemName.seamus_winter_play: LHP2ItemData(base_item_id + 202),
    ItemName.ron_underwear_play: LHP2ItemData(base_item_id + 203),
    ItemName.ron_wedding_play: LHP2ItemData(base_item_id + 204),
    ItemName.waitress_luchino_play: LHP2ItemData(base_item_id + 205),
    ItemName.petunia_green_coat_play: LHP2ItemData(base_item_id + 206),
    ItemName.seamus_play: LHP2ItemData(base_item_id + 207),
    ItemName.snatcher_play: LHP2ItemData(base_item_id + 208, ItmClasDeprioSkip),
    ItemName.ron_green_shirt_play: LHP2ItemData(base_item_id + 209),
    ItemName.neville_waiter_play: LHP2ItemData(base_item_id + 210),
    ItemName.xeno_wedding_play: LHP2ItemData(base_item_id + 211),
    ItemName.skeleton_play: LHP2ItemData(base_item_id + 212),
}

# 213 - 425
character_token_item_table: Dict[str, LHP2ItemData] = {
    ItemName.hagrid_token: LHP2ItemData(base_item_id + 213, ItemClassification.progression),
    ItemName.fang_token: LHP2ItemData(base_item_id + 214, ItemClassification.progression),
    ItemName.hagrid_wed_token: LHP2ItemData(base_item_id + 215, ItemClassification.progression),
    ItemName.prof_flit_token: LHP2ItemData(base_item_id + 216, ItemClassification.progression),
    ItemName.madam_malk_token: LHP2ItemData(base_item_id + 217, ItemClassification.progression),
    ItemName.dobby_token: LHP2ItemData(base_item_id + 218, ItemClassification.progression),
    ItemName.kreacher_token: LHP2ItemData(base_item_id + 219, ItemClassification.progression),
    ItemName.tr_orphanage_token: LHP2ItemData(base_item_id + 220, ItemClassification.progression),
    ItemName.bogrod_token: LHP2ItemData(base_item_id + 221, ItemClassification.progression),
    ItemName.mund_fletch_token: LHP2ItemData(base_item_id + 222, ItemClassification.progression),
    ItemName.griphook_token: LHP2ItemData(base_item_id + 223, ItemClassification.progression),
    ItemName.prof_mcgon_token: LHP2ItemData(base_item_id + 224, ItemClassification.progression),
    ItemName.madam_pince_token: LHP2ItemData(base_item_id + 225, ItemClassification.progression),
    ItemName.prof_sprout_token: LHP2ItemData(base_item_id + 226, ItemClassification.progression),
    ItemName.madam_pomfrey_token: LHP2ItemData(base_item_id + 227, ItemClassification.progression),
    ItemName.prof_trelawney_token: LHP2ItemData(base_item_id + 228, ItemClassification.progression),
    ItemName.madam_rosmerta_token: LHP2ItemData(base_item_id + 229, ItemClassification.progression),
    ItemName.fat_friar_token: LHP2ItemData(base_item_id + 230, ItemClassification.progression),
    ItemName.grey_lady_token: LHP2ItemData(base_item_id + 231, ItemClassification.progression),
    ItemName.fat_lady_token: LHP2ItemData(base_item_id + 232, ItemClassification.progression),
    ItemName.herm_ball_token: LHP2ItemData(base_item_id + 233, ItemClassification.progression),
    ItemName.bellatrix_token: LHP2ItemData(base_item_id + 234, ItemClassification.progression),
    ItemName.emmeline_token: LHP2ItemData(base_item_id + 235, ItemClassification.progression),
    ItemName.narcissa_token: LHP2ItemData(base_item_id + 236, ItemClassification.progression),
    ItemName.mcgon_pyjamas_token: LHP2ItemData(base_item_id + 237, ItemClassification.progression),
    ItemName.mary_cattermole_token: LHP2ItemData(base_item_id + 238, ItemClassification.progression),
    ItemName.mcgon_black_token: LHP2ItemData(base_item_id + 239, ItemClassification.progression),
    ItemName.herm_gringotts_token: LHP2ItemData(base_item_id + 240, ItemClassification.progression),
    ItemName.prof_grubbly_token: LHP2ItemData(base_item_id + 241, ItemClassification.progression),
    ItemName.bellatrix_azka_token: LHP2ItemData(base_item_id + 242, ItemClassification.progression),
    ItemName.death_eater_token: LHP2ItemData(base_item_id + 243, ItemClassification.progression),
    ItemName.dudley_grey_token: LHP2ItemData(base_item_id + 244, ItemClassification.progression),
    ItemName.prof_dumble_token: LHP2ItemData(base_item_id + 245, ItemClassification.progression),
    # ItemName.harry_token: LHP2ItemData(base_item_id + 246, ItemClassification.progression),
    # ItemName.herm_token: LHP2ItemData(base_item_id + 247, ItemClassification.progression),
    ItemName.argus_token: LHP2ItemData(base_item_id + 248, ItemClassification.progression),
    ItemName.madam_hooch_token: LHP2ItemData(base_item_id + 249, ItemClassification.progression),
    ItemName.crabbe_token: LHP2ItemData(base_item_id + 250, ItemClassification.progression),
    ItemName.goyle_token: LHP2ItemData(base_item_id + 251, ItemClassification.progression),
    ItemName.ginny_token: LHP2ItemData(base_item_id + 252, ItemClassification.progression),
    ItemName.arthur_token: LHP2ItemData(base_item_id + 253, ItemClassification.progression),
    ItemName.katie_token: LHP2ItemData(base_item_id + 254, ItemClassification.progression),
    ItemName.lily_token: LHP2ItemData(base_item_id + 255, ItemClassification.progression),
    ItemName.bloody_baron_token: LHP2ItemData(base_item_id + 256, ItemClassification.progression),
    ItemName.fudge_token: LHP2ItemData(base_item_id + 257, ItemClassification.progression),
    ItemName.justin_token: LHP2ItemData(base_item_id + 258, ItemClassification.progression),
    ItemName.cho_token: LHP2ItemData(base_item_id + 259, ItemClassification.progression),
    ItemName.dean_token: LHP2ItemData(base_item_id + 260, ItemClassification.progression),
    ItemName.draco_token: LHP2ItemData(base_item_id + 261, ItemClassification.progression),
    ItemName.lucius_token: LHP2ItemData(base_item_id + 262, ItemClassification.progression),
    ItemName.draco_suit_token: LHP2ItemData(base_item_id + 263, ItemClassification.progression),
    # ItemName.custom_a_token: LHP2ItemData(base_item_id + 264, ItemClassification.progression),
    # ItemName.custom_b_token: LHP2ItemData(base_item_id + 265, ItemClassification.progression),
    # ItemName.custom_c_token: LHP2ItemData(base_item_id + 266, ItemClassification.progression),
    # ItemName.custom_d_token: LHP2ItemData(base_item_id + 267, ItemClassification.progression),
    # ItemName.custom_e_token: LHP2ItemData(base_item_id + 268, ItemClassification.progression),
    # ItemName.custom_g_token: LHP2ItemData(base_item_id + 269, ItemClassification.progression),
    # ItemName.custom_h_token: LHP2ItemData(base_item_id + 270, ItemClassification.progression),
    # ItemName.custom_i_token: LHP2ItemData(base_item_id + 271, ItemClassification.progression),
    # ItemName.custom_j_token: LHP2ItemData(base_item_id + 272, ItemClassification.progression),
    ItemName.harry_pyjamas_token: LHP2ItemData(base_item_id + 273, ItemClassification.progression),
    ItemName.myrtle_token: LHP2ItemData(base_item_id + 274, ItemClassification.progression),
    ItemName.james_ghost_token: LHP2ItemData(base_item_id + 275, ItemClassification.progression),
    ItemName.madeye_token: LHP2ItemData(base_item_id + 276, ItemClassification.progression),
    ItemName.hannah_token: LHP2ItemData(base_item_id + 277, ItemClassification.progression),
    # ItemName.custom_f_token: LHP2ItemData(base_item_id + 278, ItemClassification.progression),
    ItemName.kingsley_token: LHP2ItemData(base_item_id + 279, ItemClassification.progression),
    ItemName.aberforth_token: LHP2ItemData(base_item_id + 280, ItemClassification.progression),
    ItemName.runcorn_token: LHP2ItemData(base_item_id + 281, ItemClassification.progression),
    ItemName.alecto_token: LHP2ItemData(base_item_id + 282, ItemClassification.progression),
    ItemName.amycus_token: LHP2ItemData(base_item_id + 283, ItemClassification.progression),
    ItemName.anthony_token: LHP2ItemData(base_item_id + 284, ItemClassification.progression),
    ItemName.bathilda_snake_token: LHP2ItemData(base_item_id + 285, ItemClassification.progression),
    ItemName.blaise_token: LHP2ItemData(base_item_id + 286, ItemClassification.progression),
    ItemName.charity_token: LHP2ItemData(base_item_id + 287, ItemClassification.progression),
    ItemName.charlie_token: LHP2ItemData(base_item_id + 288, ItemClassification.progression),
    ItemName.cormac_token: LHP2ItemData(base_item_id + 289, ItemClassification.progression),
    ItemName.dedalus_token: LHP2ItemData(base_item_id + 290, ItemClassification.progression),
    ItemName.dirk_token: LHP2ItemData(base_item_id + 291, ItemClassification.progression),
    ItemName.dolohov_token: LHP2ItemData(base_item_id + 292, ItemClassification.progression),
    ItemName.dragomir_token: LHP2ItemData(base_item_id + 293, ItemClassification.progression),
    ItemName.elphias_token: LHP2ItemData(base_item_id + 294, ItemClassification.progression),
    ItemName.fenrir_token: LHP2ItemData(base_item_id + 295, ItemClassification.progression),
    ItemName.grindel_young_token: LHP2ItemData(base_item_id + 296, ItemClassification.progression),
    ItemName.grindel_old_token: LHP2ItemData(base_item_id + 297, ItemClassification.progression),
    ItemName.gregorovitch_token: LHP2ItemData(base_item_id + 298, ItemClassification.progression),
    ItemName.hestia_token: LHP2ItemData(base_item_id + 299, ItemClassification.progression),
    ItemName.prof_slughorn_token: LHP2ItemData(base_item_id + 300, ItemClassification.progression),
    ItemName.james_young_token: LHP2ItemData(base_item_id + 301, ItemClassification.progression),
    ItemName.lavender_token: LHP2ItemData(base_item_id + 302, ItemClassification.progression),
    ItemName.mafalda_token: LHP2ItemData(base_item_id + 303, ItemClassification.progression),
    ItemName.belby_token: LHP2ItemData(base_item_id + 304, ItemClassification.progression),
    ItemName.luna_purple_coat_token: LHP2ItemData(base_item_id + 305, ItemClassification.progression),
    ItemName.herm_grey_coat_token: LHP2ItemData(base_item_id + 306, ItemClassification.progression),
    ItemName.harry_godric_token: LHP2ItemData(base_item_id + 307, ItemClassification.progression),
    ItemName.prof_umbridge_token: LHP2ItemData(base_item_id + 308, ItemClassification.progression),
    ItemName.fred_token: LHP2ItemData(base_item_id + 309, ItemClassification.progression),
    ItemName.george_token: LHP2ItemData(base_item_id + 310, ItemClassification.progression),
    ItemName.molly_apron_token: LHP2ItemData(base_item_id + 311, ItemClassification.progression),
    ItemName.crabbe_jumper_token: LHP2ItemData(base_item_id + 312, ItemClassification.progression),
    ItemName.draco_sweater_token: LHP2ItemData(base_item_id + 313, ItemClassification.progression),
    ItemName.goyle_jumper_token: LHP2ItemData(base_item_id + 314, ItemClassification.progression),
    ItemName.milk_man_token: LHP2ItemData(base_item_id + 315, ItemClassification.progression),
    ItemName.twin_2_token: LHP2ItemData(base_item_id + 316, ItemClassification.progression),
    ItemName.herm_mafalda_token: LHP2ItemData(base_item_id + 317, ItemClassification.progression),
    ItemName.ministry_guard_token: LHP2ItemData(base_item_id + 318, ItemClassification.progression),
    ItemName.harry_winter_token: LHP2ItemData(base_item_id + 319, ItemClassification.progression),
    ItemName.arthur_torn_suit_token: LHP2ItemData(base_item_id + 320, ItemClassification.progression),
    ItemName.fred_winter_token: LHP2ItemData(base_item_id + 321, ItemClassification.progression),
    ItemName.cho_winter_token: LHP2ItemData(base_item_id + 322, ItemClassification.progression),
    ItemName.george_winter_token: LHP2ItemData(base_item_id + 323, ItemClassification.progression),
    ItemName.herm_scarf_token: LHP2ItemData(base_item_id + 324, ItemClassification.progression),
    ItemName.luna_blue_jumper_token: LHP2ItemData(base_item_id + 325, ItemClassification.progression),
    ItemName.fred_owls_token: LHP2ItemData(base_item_id + 326, ItemClassification.progression),
    ItemName.fred_pyjamas_token: LHP2ItemData(base_item_id + 327, ItemClassification.progression),
    ItemName.george_owls_token: LHP2ItemData(base_item_id + 328, ItemClassification.progression),
    ItemName.george_pyjamas_token: LHP2ItemData(base_item_id + 329, ItemClassification.progression),
    ItemName.herm_jumper_token: LHP2ItemData(base_item_id + 330, ItemClassification.progression),
    ItemName.fudge_wizengamot_token: LHP2ItemData(base_item_id + 331, ItemClassification.progression),
    ItemName.dudley_token: LHP2ItemData(base_item_id + 332, ItemClassification.progression),
    ItemName.gang_mem_token: LHP2ItemData(base_item_id + 333, ItemClassification.progression),
    ItemName.harry_albert_runcorn_token: LHP2ItemData(base_item_id + 334, ItemClassification.progression),
    ItemName.harry_brown_jacket_token: LHP2ItemData(base_item_id + 335, ItemClassification.progression),
    ItemName.dumble_cursed_token: LHP2ItemData(base_item_id + 336, ItemClassification.progression),
    ItemName.lucius_death_eater_token: LHP2ItemData(base_item_id + 337, ItemClassification.progression),
    ItemName.luna_token: LHP2ItemData(base_item_id + 338, ItemClassification.progression),
    ItemName.umbridge_wizengamot_token: LHP2ItemData(base_item_id + 339, ItemClassification.progression),
    ItemName.dolohov_workman_token: LHP2ItemData(base_item_id + 340, ItemClassification.progression),
    ItemName.michael_token: LHP2ItemData(base_item_id + 341, ItemClassification.progression),
    ItemName.dean_winter_token: LHP2ItemData(base_item_id + 342, ItemClassification.progression),
    ItemName.arthur_cardigan_token: LHP2ItemData(base_item_id + 343, ItemClassification.progression),
    ItemName.luna_pink_dress_token: LHP2ItemData(base_item_id + 344, ItemClassification.progression),
    ItemName.marietta_token: LHP2ItemData(base_item_id + 345, ItemClassification.progression),
    ItemName.dumble_young_token: LHP2ItemData(base_item_id + 346, ItemClassification.progression),
    ItemName.slughorn_young_token: LHP2ItemData(base_item_id + 347, ItemClassification.progression),
    ItemName.slughorn_pyjamas_token: LHP2ItemData(base_item_id + 348, ItemClassification.progression),
    ItemName.lily_young_casual_token: LHP2ItemData(base_item_id + 349, ItemClassification.progression),
    ItemName.ginny_dress_token: LHP2ItemData(base_item_id + 350, ItemClassification.progression),
    ItemName.ginny_pyjamas_token: LHP2ItemData(base_item_id + 351, ItemClassification.progression),
    ItemName.blaise_black_shirt_token: LHP2ItemData(base_item_id + 352, ItemClassification.progression),
    ItemName.cormac_suit_token: LHP2ItemData(base_item_id + 353, ItemClassification.progression),
    ItemName.muggle_orphan_token: LHP2ItemData(base_item_id + 354, ItemClassification.progression),
    ItemName.luna_overalls_token: LHP2ItemData(base_item_id + 355, ItemClassification.progression),
    ItemName.molly_token: LHP2ItemData(base_item_id + 356, ItemClassification.progression),
    ItemName.herm_cardigan_token: LHP2ItemData(base_item_id + 357, ItemClassification.progression),
    ItemName.luna_yellow_dress_token: LHP2ItemData(base_item_id + 358, ItemClassification.progression),
    ItemName.dudley_shirt_token: LHP2ItemData(base_item_id + 359, ItemClassification.progression),
    ItemName.bill_wedding_token: LHP2ItemData(base_item_id + 360, ItemClassification.progression),
    ItemName.fleur_token: LHP2ItemData(base_item_id + 361, ItemClassification.progression),
    ItemName.herm_red_dress_token: LHP2ItemData(base_item_id + 362, ItemClassification.progression),
    ItemName.figg_token: LHP2ItemData(base_item_id + 363, ItemClassification.progression),
    ItemName.harry_locket_token: LHP2ItemData(base_item_id + 364, ItemClassification.progression),
    ItemName.twin_1_token: LHP2ItemData(base_item_id + 365, ItemClassification.progression),
    ItemName.cole_token: LHP2ItemData(base_item_id + 366, ItemClassification.progression),
    ItemName.herm_ministry_token: LHP2ItemData(base_item_id + 367, ItemClassification.progression),
    ItemName.arthur_suit_token: LHP2ItemData(base_item_id + 368, ItemClassification.progression),
    ItemName.harry_christmas_token: LHP2ItemData(base_item_id + 369, ItemClassification.progression),
    ItemName.ernie_token: LHP2ItemData(base_item_id + 370, ItemClassification.progression),
    ItemName.prof_snape_token: LHP2ItemData(base_item_id + 371, ItemClassification.progression),
    ItemName.neville_token: LHP2ItemData(base_item_id + 372, ItemClassification.progression),
    # ItemName.ron_token: LHP2ItemData(base_item_id + 373, ItemClassification.progression),
    ItemName.ron_quidditch_token: LHP2ItemData(base_item_id + 374, ItemClassification.progression),
    ItemName.vernon_token: LHP2ItemData(base_item_id + 375, ItemClassification.progression),
    ItemName.tom_riddle_token: LHP2ItemData(base_item_id + 376, ItemClassification.progression),
    ItemName.sirius_black_token: LHP2ItemData(base_item_id + 377, ItemClassification.progression),
    ItemName.remus_lupin_token: LHP2ItemData(base_item_id + 378, ItemClassification.progression),
    ItemName.wormtail_token: LHP2ItemData(base_item_id + 379, ItemClassification.progression),
    ItemName.rita_skeeter_token: LHP2ItemData(base_item_id + 380, ItemClassification.progression),
    ItemName.padma_patil_token: LHP2ItemData(base_item_id + 381, ItemClassification.progression),
    ItemName.station_guard_token: LHP2ItemData(base_item_id + 382, ItemClassification.progression),
    ItemName.prof_binns_token: LHP2ItemData(base_item_id + 383, ItemClassification.progression),
    ItemName.penelope_token: LHP2ItemData(base_item_id + 384, ItemClassification.progression),
    ItemName.susan_token: LHP2ItemData(base_item_id + 385, ItemClassification.progression),
    ItemName.tonks_token: LHP2ItemData(base_item_id + 386, ItemClassification.progression),
    ItemName.pius_token: LHP2ItemData(base_item_id + 387, ItemClassification.progression),
    ItemName.reg_token: LHP2ItemData(base_item_id + 388, ItemClassification.progression),
    ItemName.regulus_token: LHP2ItemData(base_item_id + 389, ItemClassification.progression),
    ItemName.scrimgeour_token: LHP2ItemData(base_item_id + 390, ItemClassification.progression),
    ItemName.scabior_token: LHP2ItemData(base_item_id + 391, ItemClassification.progression),
    ItemName.xeno_token: LHP2ItemData(base_item_id + 392, ItemClassification.progression),
    ItemName.yaxley_token: LHP2ItemData(base_item_id + 393, ItemClassification.progression),
    ItemName.zacharias_token: LHP2ItemData(base_item_id + 394, ItemClassification.progression),
    ItemName.waitress_treats_token: LHP2ItemData(base_item_id + 395, ItemClassification.progression),
    ItemName.lord_voldemort_token: LHP2ItemData(base_item_id + 396, ItemClassification.progression),
    ItemName.ron_blue_pyjamas_token: LHP2ItemData(base_item_id + 397, ItemClassification.progression),
    ItemName.neville_cardigan_token: LHP2ItemData(base_item_id + 398, ItemClassification.progression),
    ItemName.neville_pyjamas_token: LHP2ItemData(base_item_id + 399, ItemClassification.progression),
    ItemName.percy_token: LHP2ItemData(base_item_id + 400, ItemClassification.progression),
    ItemName.sirius_azkaban_token: LHP2ItemData(base_item_id + 401, ItemClassification.progression),
    ItemName.black_token: LHP2ItemData(base_item_id + 402, ItemClassification.progression),
    ItemName.xeno_luna_token: LHP2ItemData(base_item_id + 403, ItemClassification.progression),
    ItemName.ron_reg_cattermole_token: LHP2ItemData(base_item_id + 404, ItemClassification.progression),
    ItemName.tonks_pink_coat_token: LHP2ItemData(base_item_id + 405, ItemClassification.progression),
    ItemName.ron_winter_clothes_token: LHP2ItemData(base_item_id + 406, ItemClassification.progression),
    ItemName.snape_underwear_token: LHP2ItemData(base_item_id + 407, ItemClassification.progression),
    ItemName.rowle_token: LHP2ItemData(base_item_id + 408, ItemClassification.progression),
    ItemName.petunia_token: LHP2ItemData(base_item_id + 409, ItemClassification.progression),
    ItemName.neville_tank_top_token: LHP2ItemData(base_item_id + 410, ItemClassification.progression),
    ItemName.neville_winter_token: LHP2ItemData(base_item_id + 411, ItemClassification.progression),
    ItemName.parvati_token: LHP2ItemData(base_item_id + 412, ItemClassification.progression),
    ItemName.ron_red_sweater_token: LHP2ItemData(base_item_id + 413, ItemClassification.progression),
    ItemName.ollivander_token: LHP2ItemData(base_item_id + 414, ItemClassification.progression),
    ItemName.seamus_winter_token: LHP2ItemData(base_item_id + 415, ItemClassification.progression),
    ItemName.ron_underwear_token: LHP2ItemData(base_item_id + 416, ItemClassification.progression),
    ItemName.ron_wedding_token: LHP2ItemData(base_item_id + 417, ItemClassification.progression),
    ItemName.waitress_luchino_token: LHP2ItemData(base_item_id + 418, ItemClassification.progression),
    ItemName.petunia_green_coat_token: LHP2ItemData(base_item_id + 419, ItemClassification.progression),
    ItemName.seamus_token: LHP2ItemData(base_item_id + 420, ItemClassification.progression),
    ItemName.snatcher_token: LHP2ItemData(base_item_id + 421, ItemClassification.progression),
    ItemName.ron_green_shirt_token: LHP2ItemData(base_item_id + 422, ItemClassification.progression),
    ItemName.neville_waiter_token: LHP2ItemData(base_item_id + 423, ItemClassification.progression),
    ItemName.xeno_wedding_token: LHP2ItemData(base_item_id + 424, ItemClassification.progression),
    ItemName.skeleton_token: LHP2ItemData(base_item_id + 425, ItemClassification.progression),
}


# 440 - 446
horcrux_item_table: Dict[str, LHP2ItemData] = {
    ItemName.tr_diary: LHP2ItemData(base_item_id + 440, ItemClassification.progression),
    ItemName.gaunt_ring: LHP2ItemData(base_item_id + 441, ItemClassification.progression),
    ItemName.locket: LHP2ItemData(base_item_id + 442, ItemClassification.progression),
    ItemName.cup: LHP2ItemData(base_item_id + 443, ItemClassification.progression),
    ItemName.diadem: LHP2ItemData(base_item_id + 444, ItemClassification.progression),
    ItemName.nagini: LHP2ItemData(base_item_id + 445, ItemClassification.progression),
    ItemName.horharry: LHP2ItemData(base_item_id + 446, ItemClassification.progression),
}

# 450 - 473
level_unlock_item_table: Dict[str, LHP2ItemData] = {
    ItemName.dt_unlock: LHP2ItemData(base_item_id + 450, ItemClassification.progression),
    ItemName.da_unlock: LHP2ItemData(base_item_id + 451, ItemClassification.progression),
    ItemName.foc_unlock: LHP2ItemData(base_item_id + 452, ItemClassification.progression),
    ItemName.kd_unlock: LHP2ItemData(base_item_id + 453, ItemClassification.progression),
    ItemName.agv_unlock: LHP2ItemData(base_item_id + 454, ItemClassification.progression),
    ItemName.avt_unlock: LHP2ItemData(base_item_id + 455, ItemClassification.progression),
    ItemName.oor_unlock: LHP2ItemData(base_item_id + 456, ItemClassification.progression),
    ItemName.jd_unlock: LHP2ItemData(base_item_id + 457, ItemClassification.progression),
    ItemName.ansmc_unlock: LHP2ItemData(base_item_id + 458, ItemClassification.progression),
    ItemName.lh_unlock: LHP2ItemData(base_item_id + 459, ItemClassification.progression),
    ItemName.ff_unlock: LHP2ItemData(base_item_id + 460, ItemClassification.progression),
    ItemName.thath_unlock: LHP2ItemData(base_item_id + 461, ItemClassification.progression),
    ItemName.tsh_unlock: LHP2ItemData(base_item_id + 462, ItemClassification.progression),
    ItemName.mim_unlock: LHP2ItemData(base_item_id + 463, ItemClassification.progression),
    ItemName.igd_unlock: LHP2ItemData(base_item_id + 464, ItemClassification.progression),
    ItemName.sal_unlock: LHP2ItemData(base_item_id + 465, ItemClassification.progression),
    ItemName.ll_unlock: LHP2ItemData(base_item_id + 466, ItemClassification.progression),
    ItemName.dob_unlock: LHP2ItemData(base_item_id + 467, ItemClassification.progression),
    ItemName.ttd_unlock: LHP2ItemData(base_item_id + 468, ItemClassification.progression),
    ItemName.bts_unlock: LHP2ItemData(base_item_id + 469, ItemClassification.progression),
    ItemName.bb_unlock: LHP2ItemData(base_item_id + 470, ItemClassification.progression),
    ItemName.fiend_unlock: LHP2ItemData(base_item_id + 471, ItemClassification.progression),
    ItemName.st_unlock: LHP2ItemData(base_item_id + 472, ItemClassification.progression),
    ItemName.tfitp_unlock: LHP2ItemData(base_item_id + 473, ItemClassification.progression),
}

# 475 - 498
level_sip_item_table: Dict[str, LHP2ItemData] = {
    ItemName.dt_sip: LHP2ItemData(base_item_id + 475),
    ItemName.da_sip: LHP2ItemData(base_item_id + 476),
    ItemName.foc_sip: LHP2ItemData(base_item_id + 477),
    ItemName.kd_sip: LHP2ItemData(base_item_id + 478),
    ItemName.agv_sip: LHP2ItemData(base_item_id + 479),
    ItemName.avt_sip: LHP2ItemData(base_item_id + 480),
    ItemName.oor_sip: LHP2ItemData(base_item_id + 481),
    ItemName.jd_sip: LHP2ItemData(base_item_id + 482),
    ItemName.ansmc_sip: LHP2ItemData(base_item_id + 483),
    ItemName.lh_sip: LHP2ItemData(base_item_id + 484),
    ItemName.ff_sip: LHP2ItemData(base_item_id + 485),
    ItemName.thath_sip: LHP2ItemData(base_item_id + 486),
    ItemName.tsh_sip: LHP2ItemData(base_item_id + 487),
    ItemName.mim_sip: LHP2ItemData(base_item_id + 488),
    ItemName.igd_sip: LHP2ItemData(base_item_id + 489),
    ItemName.sal_sip: LHP2ItemData(base_item_id + 490),
    ItemName.ll_sip: LHP2ItemData(base_item_id + 491),
    ItemName.dob_sip: LHP2ItemData(base_item_id + 492),
    ItemName.ttd_sip: LHP2ItemData(base_item_id + 493),
    ItemName.bts_sip: LHP2ItemData(base_item_id + 494),
    ItemName.bb_sip: LHP2ItemData(base_item_id + 495),
    ItemName.fiend_sip: LHP2ItemData(base_item_id + 496),
    ItemName.st_sip: LHP2ItemData(base_item_id + 497),
    ItemName.tfitp_sip: LHP2ItemData(base_item_id + 498),
}

# 499 - 538
hub_sip_item_table: Dict[str, LHP2ItemData] = {
    ItemName.tent_sip: LHP2ItemData(base_item_id + 499),
    ItemName.wild_sip: LHP2ItemData(base_item_id + 500),
    ItemName.cafe_sip: LHP2ItemData(base_item_id + 501),
    ItemName.lond_sip: LHP2ItemData(base_item_id + 502),
    ItemName.kcs_sip: LHP2ItemData(base_item_id + 503),
    ItemName.hogspath_sip: LHP2ItemData(base_item_id + 504),
    ItemName.hogs_sip: LHP2ItemData(base_item_id + 505),
    ItemName.hogstat_sip: LHP2ItemData(base_item_id + 506),
    ItemName.hogwpath_sip: LHP2ItemData(base_item_id + 507),
    ItemName.herb_sip: LHP2ItemData(base_item_id + 508),
    ItemName.tg_sip: LHP2ItemData(base_item_id + 509),
    ItemName.quad_sip: LHP2ItemData(base_item_id + 510),
    ItemName.ror_sip: LHP2ItemData(base_item_id + 511),
    ItemName.wcs_sip: LHP2ItemData(base_item_id + 512),
    ItemName.wc_sip: LHP2ItemData(base_item_id + 513),
    ItemName.gh_sip: LHP2ItemData(base_item_id + 514),
    ItemName.ghl_sip: LHP2ItemData(base_item_id + 515),
    ItemName.lake_sip: LHP2ItemData(base_item_id + 516),
    # ItemName.qp_sip: LHP2ItemData(base_item_id + 517),
    ItemName.thest_sip: LHP2ItemData(base_item_id + 518),
    ItemName.ground_sip: LHP2ItemData(base_item_id + 519),
    ItemName.raven_sip: LHP2ItemData(base_item_id + 520),
    ItemName.gryf_sip: LHP2ItemData(base_item_id + 521),
    ItemName.dormlob_sip: LHP2ItemData(base_item_id + 522),
    ItemName.ast_sip: LHP2ItemData(base_item_id + 523),
    ItemName.y6c_sip: LHP2ItemData(base_item_id + 524),
    ItemName.y5c_sip: LHP2ItemData(base_item_id + 525),
    ItemName.pot_sip: LHP2ItemData(base_item_id + 526),
    ItemName.div_sip: LHP2ItemData(base_item_id + 527),
    ItemName.dada_sip: LHP2ItemData(base_item_id + 528),
    ItemName.divc_sip: LHP2ItemData(base_item_id + 529),
    ItemName.cl_sip: LHP2ItemData(base_item_id + 530),
    ItemName.stair_sip: LHP2ItemData(base_item_id + 531),
    ItemName.lib_sip: LHP2ItemData(base_item_id + 532),
    ItemName.foyer_sip: LHP2ItemData(base_item_id + 533),
    ItemName.mm_sip: LHP2ItemData(base_item_id + 534),
    ItemName.knock_sip: LHP2ItemData(base_item_id + 535),
    ItemName.leaky_sip: LHP2ItemData(base_item_id + 536),
    ItemName.www_sip: LHP2ItemData(base_item_id + 537),
    # ItemName.diag_sip: LHP2ItemData(base_item_id + 538),
}

# 550 - 575
house_crest_item_table: Dict[str, LHP2ItemData] = {
    # Gryff Crests
    ItemName.dt_gc: LHP2ItemData(base_item_id + 550),
    ItemName.da_gc: LHP2ItemData(base_item_id + 551),
    ItemName.foc_gc: LHP2ItemData(base_item_id + 552),
    ItemName.kd_gc: LHP2ItemData(base_item_id + 553),
    ItemName.agv_gc: LHP2ItemData(base_item_id + 554),
    ItemName.avt_gc: LHP2ItemData(base_item_id + 555),
    ItemName.oor_gc: LHP2ItemData(base_item_id + 556),
    ItemName.jd_gc: LHP2ItemData(base_item_id + 557),
    ItemName.ansmc_gc: LHP2ItemData(base_item_id + 558),
    ItemName.lh_gc: LHP2ItemData(base_item_id + 559),
    ItemName.ff_gc: LHP2ItemData(base_item_id + 560),
    ItemName.thath_gc: LHP2ItemData(base_item_id + 561),
    ItemName.tsh_gc: LHP2ItemData(base_item_id + 562),
    ItemName.mim_gc: LHP2ItemData(base_item_id + 563),
    ItemName.igd_gc: LHP2ItemData(base_item_id + 564),
    ItemName.sal_gc: LHP2ItemData(base_item_id + 565),
    ItemName.ll_gc: LHP2ItemData(base_item_id + 566),
    ItemName.dob_gc: LHP2ItemData(base_item_id + 567),
    ItemName.ttd_gc: LHP2ItemData(base_item_id + 568),
    ItemName.bts_gc: LHP2ItemData(base_item_id + 569),
    ItemName.bb_gc: LHP2ItemData(base_item_id + 570),
    ItemName.fiend_gc: LHP2ItemData(base_item_id + 571),
    ItemName.st_gc: LHP2ItemData(base_item_id + 572),
    ItemName.tfitp_gc: LHP2ItemData(base_item_id + 573),
    # Slyth Crests
    ItemName.dt_sc: LHP2ItemData(base_item_id + 574),
    ItemName.da_sc: LHP2ItemData(base_item_id + 575),
    ItemName.foc_sc: LHP2ItemData(base_item_id + 576),
    ItemName.kd_sc: LHP2ItemData(base_item_id + 577),
    ItemName.agv_sc: LHP2ItemData(base_item_id + 578),
    ItemName.avt_sc: LHP2ItemData(base_item_id + 579),
    ItemName.oor_sc: LHP2ItemData(base_item_id + 580),
    ItemName.jd_sc: LHP2ItemData(base_item_id + 581),
    ItemName.ansmc_sc: LHP2ItemData(base_item_id + 582),
    ItemName.lh_sc: LHP2ItemData(base_item_id + 583),
    ItemName.ff_sc: LHP2ItemData(base_item_id + 584),
    ItemName.thath_sc: LHP2ItemData(base_item_id + 585),
    ItemName.tsh_sc: LHP2ItemData(base_item_id + 586),
    ItemName.mim_sc: LHP2ItemData(base_item_id + 587),
    ItemName.igd_sc: LHP2ItemData(base_item_id + 588),
    ItemName.sal_sc: LHP2ItemData(base_item_id + 589),
    ItemName.ll_sc: LHP2ItemData(base_item_id + 590),
    ItemName.dob_sc: LHP2ItemData(base_item_id + 591),
    ItemName.ttd_sc: LHP2ItemData(base_item_id + 592),
    ItemName.bts_sc: LHP2ItemData(base_item_id + 593),
    ItemName.bb_sc: LHP2ItemData(base_item_id + 594),
    ItemName.fiend_sc: LHP2ItemData(base_item_id + 595),
    ItemName.st_sc: LHP2ItemData(base_item_id + 596),
    ItemName.tfitp_sc: LHP2ItemData(base_item_id + 597),
    # Raven Crests
    ItemName.dt_rc: LHP2ItemData(base_item_id + 598),
    ItemName.da_rc: LHP2ItemData(base_item_id + 599),
    ItemName.foc_rc: LHP2ItemData(base_item_id + 600),
    ItemName.kd_rc: LHP2ItemData(base_item_id + 601),
    ItemName.agv_rc: LHP2ItemData(base_item_id + 602),
    ItemName.avt_rc: LHP2ItemData(base_item_id + 603),
    ItemName.oor_rc: LHP2ItemData(base_item_id + 604),
    ItemName.jd_rc: LHP2ItemData(base_item_id + 605),
    ItemName.ansmc_rc: LHP2ItemData(base_item_id + 606),
    ItemName.lh_rc: LHP2ItemData(base_item_id + 607),
    ItemName.ff_rc: LHP2ItemData(base_item_id + 608),
    ItemName.thath_rc: LHP2ItemData(base_item_id + 609),
    ItemName.tsh_rc: LHP2ItemData(base_item_id + 610),
    ItemName.mim_rc: LHP2ItemData(base_item_id + 611),
    ItemName.igd_rc: LHP2ItemData(base_item_id + 612),
    ItemName.sal_rc: LHP2ItemData(base_item_id + 613),
    ItemName.ll_rc: LHP2ItemData(base_item_id + 614),
    ItemName.dob_rc: LHP2ItemData(base_item_id + 615),
    ItemName.ttd_rc: LHP2ItemData(base_item_id + 616),
    ItemName.bts_rc: LHP2ItemData(base_item_id + 617),
    ItemName.bb_rc: LHP2ItemData(base_item_id + 618),
    ItemName.fiend_rc: LHP2ItemData(base_item_id + 619),
    ItemName.st_rc: LHP2ItemData(base_item_id + 620),
    ItemName.tfitp_rc: LHP2ItemData(base_item_id + 621),
    # Huffle Crests
    ItemName.dt_hc: LHP2ItemData(base_item_id + 622),
    ItemName.da_hc: LHP2ItemData(base_item_id + 623),
    ItemName.foc_hc: LHP2ItemData(base_item_id + 624),
    ItemName.kd_hc: LHP2ItemData(base_item_id + 625),
    ItemName.agv_hc: LHP2ItemData(base_item_id + 626),
    ItemName.avt_hc: LHP2ItemData(base_item_id + 627),
    ItemName.oor_hc: LHP2ItemData(base_item_id + 628),
    ItemName.jd_hc: LHP2ItemData(base_item_id + 629),
    ItemName.ansmc_hc: LHP2ItemData(base_item_id + 630),
    ItemName.lh_hc: LHP2ItemData(base_item_id + 631),
    ItemName.ff_hc: LHP2ItemData(base_item_id + 632),
    ItemName.thath_hc: LHP2ItemData(base_item_id + 633),
    ItemName.tsh_hc: LHP2ItemData(base_item_id + 634),
    ItemName.mim_hc: LHP2ItemData(base_item_id + 635),
    ItemName.igd_hc: LHP2ItemData(base_item_id + 636),
    ItemName.sal_hc: LHP2ItemData(base_item_id + 637),
    ItemName.ll_hc: LHP2ItemData(base_item_id + 638),
    ItemName.dob_hc: LHP2ItemData(base_item_id + 639),
    ItemName.ttd_hc: LHP2ItemData(base_item_id + 640),
    ItemName.bts_hc: LHP2ItemData(base_item_id + 641),
    ItemName.bb_hc: LHP2ItemData(base_item_id + 642),
    ItemName.fiend_hc: LHP2ItemData(base_item_id + 643),
    ItemName.st_hc: LHP2ItemData(base_item_id + 644),
    ItemName.tfitp_hc: LHP2ItemData(base_item_id + 645),
}

# 650 - 673
# House Crest Completed

# 675 - 698
true_wizard_item_table: Dict[str, LHP2ItemData] = {
    ItemName.dt_tw: LHP2ItemData(base_item_id + 675),
    ItemName.da_tw: LHP2ItemData(base_item_id + 676),
    ItemName.foc_tw: LHP2ItemData(base_item_id + 677),
    ItemName.kd_tw: LHP2ItemData(base_item_id + 678),
    ItemName.agv_tw: LHP2ItemData(base_item_id + 679),
    ItemName.avt_tw: LHP2ItemData(base_item_id + 680),
    ItemName.oor_tw: LHP2ItemData(base_item_id + 681),
    ItemName.jd_tw: LHP2ItemData(base_item_id + 682),
    ItemName.ansmc_tw: LHP2ItemData(base_item_id + 683),
    ItemName.lh_tw: LHP2ItemData(base_item_id + 684),
    ItemName.ff_tw: LHP2ItemData(base_item_id + 685),
    ItemName.thath_tw: LHP2ItemData(base_item_id + 686),
    ItemName.tsh_tw: LHP2ItemData(base_item_id + 687),
    ItemName.mim_tw: LHP2ItemData(base_item_id + 688),
    ItemName.igd_tw: LHP2ItemData(base_item_id + 689),
    ItemName.sal_tw: LHP2ItemData(base_item_id + 690),
    ItemName.ll_tw: LHP2ItemData(base_item_id + 691),
    ItemName.dob_tw: LHP2ItemData(base_item_id + 692),
    ItemName.ttd_tw: LHP2ItemData(base_item_id + 693),
    ItemName.bts_tw: LHP2ItemData(base_item_id + 694),
    ItemName.bb_tw: LHP2ItemData(base_item_id + 695),
    ItemName.fiend_tw: LHP2ItemData(base_item_id + 696),
    ItemName.st_tw: LHP2ItemData(base_item_id + 697),
    ItemName.tfitp_tw: LHP2ItemData(base_item_id + 698),
}

purp_stud_item_table: Dict[str, LHP2ItemData] = {
    ItemName.purp_stud: LHP2ItemData(base_item_id + 699, qty=0),
}

# Gold Bricks 700 - 899
gold_brick_item_table: Dict[str, LHP2ItemData] = {
    ItemName.gb: LHP2ItemData(base_item_id + 700, qty=0),
    ItemName.gb5: LHP2ItemData(base_item_id + 701, qty=40),
}

# Red Brick Purchasable 900 - 933
red_brick_purchasable_table: Dict[str, LHP2ItemData] = {
    ItemName.christmas_purchasable: LHP2ItemData(base_item_id + 901, ItemClassification.progression),
    ItemName.gb_detect_purchasable: LHP2ItemData(base_item_id + 903, ItemClassification.progression),
    ItemName.score_x4_purchasable: LHP2ItemData(base_item_id + 904, ItemClassification.progression),
    ItemName.score_x6_purchasable: LHP2ItemData(base_item_id + 905, ItemClassification.progression),
    ItemName.score_x2_purchasable: LHP2ItemData(base_item_id + 906, ItemClassification.progression),
    ItemName.red_brick_detect_purchasable: LHP2ItemData(base_item_id + 907, ItemClassification.progression),
    ItemName.score_x8_purchasable: LHP2ItemData(base_item_id + 908, ItemClassification.progression),
    ItemName.ghost_studs_purchasable: LHP2ItemData(base_item_id + 911, ItemClassification.progression),
    ItemName.stud_mag_purchasable: LHP2ItemData(base_item_id + 912, ItemClassification.progression),
    ItemName.super_strength_purchasable: LHP2ItemData(base_item_id + 914, ItemClassification.progression),
    ItemName.char_studs_purchasable: LHP2ItemData(base_item_id + 915, ItemClassification.progression),
    ItemName.crest_detect_purchasable: LHP2ItemData(base_item_id + 916, ItemClassification.progression),
    ItemName.score_x10_purchasable: LHP2ItemData(base_item_id + 917, ItemClassification.progression),
    ItemName.regen_hearts_purchasable: LHP2ItemData(base_item_id + 919, ItemClassification.progression),
    ItemName.fast_dig_purchasable: LHP2ItemData(base_item_id + 920, ItemClassification.progression),
    ItemName.fast_magic_purchasable: LHP2ItemData(base_item_id + 924, ItemClassification.progression),
    ItemName.char_token_detect_purchasable: LHP2ItemData(base_item_id + 928, ItemClassification.progression),
    ItemName.extra_hears_purchasable: LHP2ItemData(base_item_id + 929, ItemClassification.progression),
    ItemName.invincibility_purchasable: LHP2ItemData(base_item_id + 930, ItemClassification.progression),
    ItemName.fall_rescue_purchasable: LHP2ItemData(base_item_id + 933, ItemClassification.progression),
}

# Red Brick Unlocks 950 - 973
red_brick_unlock_table: Dict[str, LHP2ItemData] = {
    ItemName.com_spec_unlock: LHP2ItemData(base_item_id + 950),
    ItemName.adv_guide_unlock: LHP2ItemData(base_item_id + 951),
    ItemName.disguise_unlock: LHP2ItemData(base_item_id + 952),
    ItemName.carrot_wand_unlock: LHP2ItemData(base_item_id + 953),
    ItemName.super_strength_unlock: LHP2ItemData(base_item_id + 954, ItmClasDeprioSkip),
    ItemName.char_token_detect_unlock: LHP2ItemData(base_item_id + 955, ItemClassification.useful),
    ItemName.fall_rescue_unlock: LHP2ItemData(base_item_id + 956, ItemClassification.useful),
    ItemName.char_studs_unlock: LHP2ItemData(base_item_id + 957, ItemClassification.useful),
    ItemName.score_x2_unlock: LHP2ItemData(base_item_id + 958, ItmClasDeprioSkip),
    ItemName.score_x4_unlock: LHP2ItemData(base_item_id + 959, ItmClasDeprioSkip),
    ItemName.score_x6_unlock: LHP2ItemData(base_item_id + 960, ItmClasDeprioSkip),
    ItemName.score_x8_unlock: LHP2ItemData(base_item_id + 961, ItmClasDeprioSkip),
    ItemName.score_x10_unlock: LHP2ItemData(base_item_id + 962, ItmClasDeprioSkip),
    ItemName.stud_mag_unlock: LHP2ItemData(base_item_id + 963, ItemClassification.useful),
    ItemName.regen_hearts_unlock: LHP2ItemData(base_item_id + 964, ItemClassification.useful),
    ItemName.extra_hears_unlock: LHP2ItemData(base_item_id + 965, ItemClassification.useful),
    ItemName.invincibility_unlock: LHP2ItemData(base_item_id + 966, ItemClassification.useful),
    ItemName.red_brick_detect_unlock: LHP2ItemData(base_item_id + 967, ItemClassification.useful),
    ItemName.crest_detect_unlock: LHP2ItemData(base_item_id + 968, ItemClassification.useful),
    ItemName.gb_detect_unlock: LHP2ItemData(base_item_id + 969, ItemClassification.useful),
    ItemName.christmas_unlock: LHP2ItemData(base_item_id + 970),
    ItemName.ghost_studs_unlock: LHP2ItemData(base_item_id + 971, ItemClassification.useful),
    ItemName.fast_magic_unlock: LHP2ItemData(base_item_id + 972, ItemClassification.useful),
    ItemName.fast_dig_unlock: LHP2ItemData(base_item_id + 973, ItemClassification.useful),
}

# 975 - 1005
joke_spell_table: Dict[str, LHP2ItemData] = {
    # ItemName.wingarad_unlock: LHP2ItemData(base_item_id + 975),
    ItemName.slug_unlock: LHP2ItemData(base_item_id + 976),
    ItemName.rictu_unlock: LHP2ItemData(base_item_id + 977),
    ItemName.entomo_unlock: LHP2ItemData(base_item_id + 978),
    ItemName.taranta_unlock: LHP2ItemData(base_item_id + 979),
    ItemName.loco_unlock: LHP2ItemData(base_item_id + 980),
    ItemName.redact_unlock: LHP2ItemData(base_item_id + 981),
    ItemName.colo_unlock: LHP2ItemData(base_item_id + 982),
    ItemName.calvo_unlock: LHP2ItemData(base_item_id + 983),
    ItemName.anteo_unlock: LHP2ItemData(base_item_id + 984),
    ItemName.herbi_unlock: LHP2ItemData(base_item_id + 985),
    ItemName.glaci_unlock: LHP2ItemData(base_item_id + 986),
    ItemName.incarc_unlock: LHP2ItemData(base_item_id + 987),
    ItemName.expel_unlock: LHP2ItemData(base_item_id + 988),
    ItemName.flip_unlock: LHP2ItemData(base_item_id + 989),
    ItemName.trip_unlock: LHP2ItemData(base_item_id + 990),
    ItemName.stup_unlock: LHP2ItemData(base_item_id + 991),
    ItemName.transfig_unlock: LHP2ItemData(base_item_id + 992),
    ItemName.engorg_unlock: LHP2ItemData(base_item_id + 993),
    ItemName.immob_unlock: LHP2ItemData(base_item_id + 994),
}


spell_item_table: Dict[str, LHP2ItemData] = {
    # ItemName.pets_unlock: LHP2ItemData(base_item_id + 995),
    # ItemName.invis_unlock: LHP2ItemData(base_item_id + 996),
    # ItemName.avada_unlock: LHP2ItemData(base_item_id + 997),
    ItemName.diffindo_unlock: LHP2ItemData(base_item_id + 998, ItemClassification.progression),
    # ItemName.lumos_unlock: LHP2ItemData(base_item_id + 999),
    # lumos has 2 bits
    ItemName.delum_unlock: LHP2ItemData(base_item_id + 1001, ItemClassification.progression),
    ItemName.agua_unlock: LHP2ItemData(base_item_id + 1002, ItemClassification.progression),
    ItemName.focus_unlock: LHP2ItemData(base_item_id + 1003, ItemClassification.progression),
    ItemName.expecto_unlock: LHP2ItemData(base_item_id + 1004, ItemClassification.progression),
    ItemName.reducto_unlock: LHP2ItemData(base_item_id + 1005, ItemClassification.progression),
}

ability_item_table: Dict[str, LHP2ItemData] = {
    # ItemName.draught_unlock: LHP2ItemData(base_item_id + 1017),
    # ItemName.thest_unlock: LHP2ItemData(base_item_id + 1018, ItmClasDeprioSkip),
    # ItemName.dueling_unlock: LHP2ItemData(base_item_id + 1019),
    ItemName.apparition_unlock: LHP2ItemData(base_item_id + 1020, ItemClassification.progression),
    # ItemName.dada_unlock: LHP2ItemData(base_item_id + 1021),
    # ItemName.grawp_unlock: LHP2ItemData(base_item_id + 1022),
    # ItemName.slug_vial_unlock: LHP2ItemData(base_item_id + 1023),
    ItemName.www_box_unlock: LHP2ItemData(base_item_id + 1024, ItemClassification.progression),
    ItemName.specs_unlock: LHP2ItemData(base_item_id + 1025, ItemClassification.progression),
    ItemName.herm_bag_unlock: LHP2ItemData(base_item_id + 1026, ItemClassification.progression),
}

item_data_table = {
    **character_item_table,
    **character_token_item_table,
    **joke_spell_table,
    **spell_item_table,
    **level_unlock_item_table,
    **level_sip_item_table,
    **hub_sip_item_table,
    **house_crest_item_table,
    **true_wizard_item_table,
    **gold_brick_item_table,
    **red_brick_purchasable_table,
    **red_brick_unlock_table,
    **ability_item_table,
    **purp_stud_item_table,
    **horcrux_item_table,
}


def setup_items(options: LHP2Options):
    temp_item_table = {}
    temp_item_table.update(character_item_table)
    temp_item_table.update(character_token_item_table)
    if options.ShuffleJokeSpells == 1:
        temp_item_table.update(joke_spell_table)
    temp_item_table.update(spell_item_table)
    temp_item_table.update(level_unlock_item_table)
    temp_item_table.update(level_sip_item_table)
    temp_item_table.update(hub_sip_item_table)
    temp_item_table.update(house_crest_item_table)
    temp_item_table.update(true_wizard_item_table)
    temp_item_table.update(gold_brick_item_table)
    if options.ShuffleGoldBrickPurchases == 0:
        temp_item_table[ItemName.gb5].qty = 24
    temp_item_table.update(red_brick_purchasable_table)
    temp_item_table.update(red_brick_unlock_table)
    temp_item_table.update(ability_item_table)
    temp_item_table.update(purp_stud_item_table)
    temp_item_table.update(horcrux_item_table)
    return temp_item_table


spell_and_ability_table = {
    **spell_item_table,
    **ability_item_table,
}

student_in_peril_table = {
    **level_sip_item_table,
    **hub_sip_item_table,
}

horcrux_names_set = set(horcrux_item_table.keys())
progression_spells = [
    name
    for table in (spell_item_table, ability_item_table)
    for name, data in table.items()
    if data.classification == ItemClassification.progression
]

item_name_groups = {
    "Token": {name: data for name, data in character_token_item_table.items()},
    "Character": {name: data for name, data in character_item_table.items()},
    "Spell": {name: data for name, data in spell_and_ability_table.items()},
    "Level Unlock": {name: data for name, data in level_unlock_item_table.items()},
    "Student In Peril": {name: data for name, data in student_in_peril_table.items()},
    "House Crest": {name: data for name, data in house_crest_item_table.items()},
    "True Wizard": {name: data for name, data in true_wizard_item_table.items()},
    "Red Brick Purchasable": {name: data for name, data in red_brick_purchasable_table.items()},
    "Red Brick Unlocked": {name: data for name, data in red_brick_unlock_table.items()},
    "Horcrux": {name: data for name, data in horcrux_item_table.items()},
}
