from typing import Dict, NamedTuple

from BaseClasses import Location
from .Options import LHP2Options
from .Names import LocationName, RegionName


class LHP2Location(Location):
    game: str = "Lego Harry Potter 5-7"


class LocationData(NamedTuple):
    id: int = 0
    region: str = ""
    price: int = 0


base_location_id = 400000

character_location_table: Dict[str, LocationData] = {
    LocationName.hagrid_purch: LocationData(base_location_id + 0, RegionName.mm, 500000),
    LocationName.fang_purch: LocationData(base_location_id + 1, RegionName.mm, 10000),
    LocationName.hagrid_wed_purch: LocationData(base_location_id + 2, RegionName.mm, 500000),
    LocationName.prof_flit_purch: LocationData(base_location_id + 3, RegionName.mm, 200000),
    LocationName.madam_malk_purch: LocationData(base_location_id + 4, RegionName.mm, 30000),
    LocationName.dobby_purch: LocationData(base_location_id + 5, RegionName.mm, 750000),
    LocationName.kreacher_purch: LocationData(base_location_id + 6, RegionName.mm, 100000),
    LocationName.tr_orphanage_purch: LocationData(base_location_id + 7, RegionName.mm, 2000000),
    LocationName.bogrod_purch: LocationData(base_location_id + 8, RegionName.mm, 100000),
    LocationName.mund_fletch_purch: LocationData(base_location_id + 9, RegionName.mm, 80000),
    LocationName.griphook_purch: LocationData(base_location_id + 10, RegionName.mm, 150000),
    LocationName.prof_mcgon_purch: LocationData(base_location_id + 11, RegionName.mm, 80000),
    LocationName.madam_pince_purch: LocationData(base_location_id + 12, RegionName.mm, 20000),
    LocationName.prof_sprout_purch: LocationData(base_location_id + 13, RegionName.mm, 250000),
    LocationName.madam_pomfrey_purch: LocationData(base_location_id + 14, RegionName.mm, 10000),
    LocationName.prof_trelawney_purch: LocationData(base_location_id + 15, RegionName.mm, 200000),
    LocationName.madam_rosmerta_purch: LocationData(base_location_id + 16, RegionName.mm, 50000),
    LocationName.fat_friar_purch: LocationData(base_location_id + 17, RegionName.mm, 50000),
    LocationName.grey_lady_purch: LocationData(base_location_id + 18, RegionName.mm, 50000),
    LocationName.fat_lady_purch: LocationData(base_location_id + 19, RegionName.mm, 30000),
    LocationName.herm_ball_purch: LocationData(base_location_id + 20, RegionName.mm, 25000),
    LocationName.bellatrix_purch: LocationData(base_location_id + 21, RegionName.mm, 3750000),
    LocationName.emmeline_purch: LocationData(base_location_id + 22, RegionName.mm, 30000),
    LocationName.narcissa_purch: LocationData(base_location_id + 23, RegionName.mm, 70000),
    LocationName.mcgon_pyjamas_purch: LocationData(base_location_id + 24, RegionName.mm, 80000),
    LocationName.mary_cattermole_purch: LocationData(base_location_id + 25, RegionName.mm, 10000),
    LocationName.mcgon_black_purch: LocationData(base_location_id + 26, RegionName.mm, 80000),
    LocationName.herm_gringotts_purch: LocationData(base_location_id + 27, RegionName.mm, 85000),
    LocationName.prof_grubbly_purch: LocationData(base_location_id + 28, RegionName.mm, 20000),
    LocationName.bellatrix_azka_purch: LocationData(base_location_id + 29, RegionName.mm, 3750000),
    LocationName.death_eater_purch: LocationData(base_location_id + 30, RegionName.mm, 250000),
    LocationName.dudley_grey_purch: LocationData(base_location_id + 31, RegionName.mm, 120000),
    LocationName.prof_dumble_purch: LocationData(base_location_id + 32, RegionName.mm, 1000000),
    # LocationName.harry_purch: LocationData(base_location_id + 33, RegionName.mm),
    # LocationName.herm_purch: LocationData(base_location_id + 34, RegionName.mm),
    LocationName.argus_purch: LocationData(base_location_id + 35, RegionName.mm, 20000),
    LocationName.madam_hooch_purch: LocationData(base_location_id + 36, RegionName.mm, 30000),
    LocationName.crabbe_purch: LocationData(base_location_id + 37, RegionName.mm, 60000),
    LocationName.goyle_purch: LocationData(base_location_id + 38, RegionName.mm, 30000),
    LocationName.ginny_purch: LocationData(base_location_id + 39, RegionName.mm, 100000),
    LocationName.arthur_purch: LocationData(base_location_id + 40, RegionName.mm, 20000),
    LocationName.katie_purch: LocationData(base_location_id + 41, RegionName.mm, 70000),
    LocationName.lily_purch: LocationData(base_location_id + 42, RegionName.mm, 200000),
    LocationName.bloody_baron_purch: LocationData(base_location_id + 43, RegionName.mm, 50000),
    LocationName.fudge_purch: LocationData(base_location_id + 44, RegionName.mm, 200000),
    LocationName.justin_purch: LocationData(base_location_id + 45, RegionName.mm, 20000),
    LocationName.cho_purch: LocationData(base_location_id + 46, RegionName.mm, 75000),
    LocationName.dean_purch: LocationData(base_location_id + 47, RegionName.mm, 50000),
    LocationName.draco_purch: LocationData(base_location_id + 48, RegionName.mm, 1000000),
    LocationName.lucius_purch: LocationData(base_location_id + 49, RegionName.mm, 250000),
    LocationName.draco_suit_purch: LocationData(base_location_id + 50, RegionName.mm, 1000000),
    # LocationName.custom_a_purch: LocationData(base_location_id + 51, RegionName.mm),
    # LocationName.custom_b_purch: LocationData(base_location_id + 52, RegionName.mm),
    # LocationName.custom_c_purch: LocationData(base_location_id + 53, RegionName.mm),
    # LocationName.custom_d_purch: LocationData(base_location_id + 54, RegionName.mm),
    # LocationName.custom_e_purch: LocationData(base_location_id + 55, RegionName.mm),
    # LocationName.custom_g_purch: LocationData(base_location_id + 56, RegionName.mm),
    # LocationName.custom_h_purch: LocationData(base_location_id + 57, RegionName.mm),
    # LocationName.custom_i_purch: LocationData(base_location_id + 58, RegionName.mm),
    # LocationName.custom_j_purch: LocationData(base_location_id + 59, RegionName.mm),
    LocationName.harry_pyjamas_purch: LocationData(base_location_id + 60, RegionName.mm, 135000),
    LocationName.myrtle_purch: LocationData(base_location_id + 61, RegionName.mm, 200000),
    LocationName.james_ghost_purch: LocationData(base_location_id + 62, RegionName.mm, 200000),
    LocationName.madeye_purch: LocationData(base_location_id + 63, RegionName.mm, 10000),
    LocationName.hannah_purch: LocationData(base_location_id + 64, RegionName.mm, 10000),
    # LocationName.custom_f_purch: LocationData(base_location_id + 65, RegionName.mm),
    LocationName.kingsley_purch: LocationData(base_location_id + 66, RegionName.mm, 20000),
    LocationName.aberforth_purch: LocationData(base_location_id + 67, RegionName.mm, 20000),
    LocationName.runcorn_purch: LocationData(base_location_id + 68, RegionName.mm, 20000),
    LocationName.alecto_purch: LocationData(base_location_id + 69, RegionName.mm, 20000),
    LocationName.amycus_purch: LocationData(base_location_id + 70, RegionName.mm, 20000),
    LocationName.anthony_purch: LocationData(base_location_id + 71, RegionName.mm, 20000),
    LocationName.bathilda_snake_purch: LocationData(base_location_id + 72, RegionName.mm, 200000),
    LocationName.blaise_purch: LocationData(base_location_id + 73, RegionName.mm, 80000),
    LocationName.charity_purch: LocationData(base_location_id + 74, RegionName.mm, 20000),
    LocationName.charlie_purch: LocationData(base_location_id + 75, RegionName.mm, 30000),
    LocationName.cormac_purch: LocationData(base_location_id + 76, RegionName.mm, 55000),
    LocationName.dedalus_purch: LocationData(base_location_id + 77, RegionName.mm, 20000),
    LocationName.dirk_purch: LocationData(base_location_id + 78, RegionName.mm, 10000),
    LocationName.dolohov_purch: LocationData(base_location_id + 79, RegionName.mm, 200000),
    LocationName.dragomir_purch: LocationData(base_location_id + 80, RegionName.mm, 40000),
    LocationName.elphias_purch: LocationData(base_location_id + 81, RegionName.mm, 10000),
    LocationName.fenrir_purch: LocationData(base_location_id + 82, RegionName.mm, 1000000),
    LocationName.grindel_young_purch: LocationData(base_location_id + 83, RegionName.mm, 200000),
    LocationName.grindel_old_purch: LocationData(base_location_id + 84, RegionName.mm, 200000),
    LocationName.gregorovitch_purch: LocationData(base_location_id + 85, RegionName.mm, 750000),
    LocationName.hestia_purch: LocationData(base_location_id + 86, RegionName.mm, 20000),
    LocationName.prof_slughorn_purch: LocationData(base_location_id + 87, RegionName.mm, 10000),
    LocationName.james_young_purch: LocationData(base_location_id + 88, RegionName.mm, 200000),
    LocationName.lavender_purch: LocationData(base_location_id + 89, RegionName.mm, 10000),
    LocationName.mafalda_purch: LocationData(base_location_id + 90, RegionName.mm, 60000),
    LocationName.belby_purch: LocationData(base_location_id + 91, RegionName.mm, 90000),
    LocationName.luna_purple_coat_purch: LocationData(base_location_id + 92, RegionName.mm, 50000),
    LocationName.herm_grey_coat_purch: LocationData(base_location_id + 93, RegionName.mm, 62500),
    LocationName.harry_godric_purch: LocationData(base_location_id + 94, RegionName.mm, 25000),
    LocationName.prof_umbridge_purch: LocationData(base_location_id + 95, RegionName.mm, 125000),
    LocationName.fred_purch: LocationData(base_location_id + 96, RegionName.mm, 60000),
    LocationName.george_purch: LocationData(base_location_id + 97, RegionName.mm, 60000),
    LocationName.molly_apron_purch: LocationData(base_location_id + 98, RegionName.mm, 750000),
    LocationName.crabbe_jumper_purch: LocationData(base_location_id + 99, RegionName.mm, 60000),
    LocationName.draco_sweater_purch: LocationData(base_location_id + 100, RegionName.mm, 1000000),
    LocationName.goyle_jumper_purch: LocationData(base_location_id + 101, RegionName.mm, 30000),
    LocationName.milk_man_purch: LocationData(base_location_id + 102, RegionName.mm, 80000),
    LocationName.twin_2_purch: LocationData(base_location_id + 103, RegionName.mm, 20000),
    LocationName.herm_mafalda_purch: LocationData(base_location_id + 104, RegionName.mm, 125000),
    LocationName.ministry_guard_purch: LocationData(base_location_id + 105, RegionName.mm, 70000),
    LocationName.harry_winter_purch: LocationData(base_location_id + 106, RegionName.mm, 85000),
    LocationName.arthur_torn_suit_purch: LocationData(base_location_id + 107, RegionName.mm, 20000),
    LocationName.fred_winter_purch: LocationData(base_location_id + 108, RegionName.mm, 60000),
    LocationName.cho_winter_purch: LocationData(base_location_id + 109, RegionName.mm, 75000),
    LocationName.george_winter_purch: LocationData(base_location_id + 110, RegionName.mm, 60000),
    LocationName.herm_scarf_purch: LocationData(base_location_id + 111, RegionName.mm, 125000),
    LocationName.luna_blue_jumper_purch: LocationData(base_location_id + 112, RegionName.mm, 50000),
    LocationName.fred_owls_purch: LocationData(base_location_id + 113, RegionName.mm, 60000),
    LocationName.fred_pyjamas_purch: LocationData(base_location_id + 114, RegionName.mm, 60000),
    LocationName.george_owls_purch: LocationData(base_location_id + 115, RegionName.mm, 60000),
    LocationName.george_pyjamas_purch: LocationData(base_location_id + 116, RegionName.mm, 60000),
    LocationName.herm_jumper_purch: LocationData(base_location_id + 117, RegionName.mm, 125000),
    LocationName.fudge_wizengamot_purch: LocationData(base_location_id + 118, RegionName.mm, 200000),
    LocationName.dudley_purch: LocationData(base_location_id + 119, RegionName.mm, 80000),
    LocationName.gang_mem_purch: LocationData(base_location_id + 120, RegionName.mm, 10000),
    LocationName.harry_albert_runcorn_purch: LocationData(base_location_id + 121, RegionName.mm, 30000),
    LocationName.harry_brown_jacket_purch: LocationData(base_location_id + 122, RegionName.mm, 32500),
    LocationName.dumble_cursed_purch: LocationData(base_location_id + 123, RegionName.mm, 1000000),
    LocationName.lucius_death_eater_purch: LocationData(base_location_id + 124, RegionName.mm, 250000),
    LocationName.luna_purch: LocationData(base_location_id + 125, RegionName.mm, 50000),
    LocationName.umbridge_wizengamot_purch: LocationData(base_location_id + 126, RegionName.mm, 125000),
    LocationName.dolohov_workman_purch: LocationData(base_location_id + 127, RegionName.mm, 200000),
    LocationName.michael_purch: LocationData(base_location_id + 128, RegionName.mm, 50000),
    LocationName.dean_winter_purch: LocationData(base_location_id + 129, RegionName.mm, 50000),
    LocationName.arthur_cardigan_purch: LocationData(base_location_id + 130, RegionName.mm, 20000),
    LocationName.luna_pink_dress_purch: LocationData(base_location_id + 131, RegionName.mm, 150000),
    LocationName.marietta_purch: LocationData(base_location_id + 132, RegionName.mm, 10000),
    LocationName.dumble_young_purch: LocationData(base_location_id + 133, RegionName.mm, 1000000),
    LocationName.slughorn_young_purch: LocationData(base_location_id + 134, RegionName.mm, 10000),
    LocationName.slughorn_pyjamas_purch: LocationData(base_location_id + 135, RegionName.mm, 10000),
    LocationName.lily_young_casual_purch: LocationData(base_location_id + 136, RegionName.mm, 200000),
    LocationName.ginny_dress_purch: LocationData(base_location_id + 137, RegionName.mm, 100000),
    LocationName.ginny_pyjamas_purch: LocationData(base_location_id + 138, RegionName.mm, 100000),
    LocationName.blaise_black_shirt_purch: LocationData(base_location_id + 139, RegionName.mm, 80000),
    LocationName.cormac_suit_purch: LocationData(base_location_id + 140, RegionName.mm, 55000),
    LocationName.muggle_orphan_purch: LocationData(base_location_id + 141, RegionName.mm, 250000),
    LocationName.luna_overalls_purch: LocationData(base_location_id + 142, RegionName.mm, 50000),
    LocationName.molly_purch: LocationData(base_location_id + 143, RegionName.mm, 750000),
    LocationName.herm_cardigan_purch: LocationData(base_location_id + 144, RegionName.mm, 125000),
    LocationName.luna_yellow_dress_purch: LocationData(base_location_id + 145, RegionName.mm, 150000),
    LocationName.dudley_shirt_purch: LocationData(base_location_id + 146, RegionName.mm, 120000),
    LocationName.bill_wedding_purch: LocationData(base_location_id + 147, RegionName.mm, 10000),
    LocationName.fleur_purch: LocationData(base_location_id + 148, RegionName.mm, 10000),
    LocationName.herm_red_dress_purch: LocationData(base_location_id + 149, RegionName.mm, 57500),
    LocationName.figg_purch: LocationData(base_location_id + 150, RegionName.mm, 60000),
    LocationName.harry_locket_purch: LocationData(base_location_id + 151, RegionName.mm, 105000),
    LocationName.twin_1_purch: LocationData(base_location_id + 152, RegionName.mm, 30000),
    LocationName.cole_purch: LocationData(base_location_id + 153, RegionName.mm, 40000),
    LocationName.herm_ministry_purch: LocationData(base_location_id + 154, RegionName.mm, 57500),
    LocationName.arthur_suit_purch: LocationData(base_location_id + 155, RegionName.mm, 20000),
    LocationName.harry_christmas_purch: LocationData(base_location_id + 156, RegionName.mm, 110000),
    LocationName.ernie_purch: LocationData(base_location_id + 157, RegionName.mm, 100000),
    LocationName.prof_snape_purch: LocationData(base_location_id + 158, RegionName.mm, 250000),
    LocationName.neville_purch: LocationData(base_location_id + 159, RegionName.mm, 50000),
    # LocationName.ron_purch: LocationData(base_location_id + 160, RegionName.mm),
    LocationName.ron_quidditch_purch: LocationData(base_location_id + 161, RegionName.mm, 82500),
    LocationName.vernon_purch: LocationData(base_location_id + 162, RegionName.mm, 50000),
    LocationName.tom_riddle_purch: LocationData(base_location_id + 163, RegionName.mm, 2000000),
    LocationName.sirius_black_purch: LocationData(base_location_id + 164, RegionName.mm, 10000),
    LocationName.remus_lupin_purch: LocationData(base_location_id + 165, RegionName.mm, 10000),
    LocationName.wormtail_purch: LocationData(base_location_id + 166, RegionName.mm, 1000000),
    LocationName.rita_skeeter_purch: LocationData(base_location_id + 167, RegionName.mm, 30000),
    LocationName.padma_patil_purch: LocationData(base_location_id + 168, RegionName.mm, 10000),
    LocationName.station_guard_purch: LocationData(base_location_id + 169, RegionName.mm, 10000),
    LocationName.prof_binns_purch: LocationData(base_location_id + 170, RegionName.mm, 50000),
    LocationName.penelope_purch: LocationData(base_location_id + 171, RegionName.mm, 60000),
    LocationName.susan_purch: LocationData(base_location_id + 172, RegionName.mm, 50000),
    LocationName.tonks_purch: LocationData(base_location_id + 173, RegionName.mm, 1250000),
    LocationName.pius_purch: LocationData(base_location_id + 174, RegionName.mm, 30000),
    LocationName.reg_purch: LocationData(base_location_id + 175, RegionName.mm, 60000),
    LocationName.regulus_purch: LocationData(base_location_id + 176, RegionName.mm, 1000000),
    LocationName.scrimgeour_purch: LocationData(base_location_id + 177, RegionName.mm, 900000),
    LocationName.scabior_purch: LocationData(base_location_id + 178, RegionName.mm, 650000),
    LocationName.xeno_purch: LocationData(base_location_id + 179, RegionName.mm, 30000),
    LocationName.yaxley_purch: LocationData(base_location_id + 180, RegionName.mm, 260000),
    LocationName.zacharias_purch: LocationData(base_location_id + 181, RegionName.mm, 20000),
    LocationName.waitress_treats_purch: LocationData(base_location_id + 182, RegionName.mm, 10000),
    LocationName.lord_voldemort_purch: LocationData(base_location_id + 183, RegionName.mm, 25000000),
    LocationName.ron_blue_pyjamas_purch: LocationData(base_location_id + 184, RegionName.mm, 25000),
    LocationName.neville_cardigan_purch: LocationData(base_location_id + 185, RegionName.mm, 50000),
    LocationName.neville_pyjamas_purch: LocationData(base_location_id + 186, RegionName.mm, 50000),
    LocationName.percy_purch: LocationData(base_location_id + 187, RegionName.mm, 50000),
    LocationName.sirius_azkaban_purch: LocationData(base_location_id + 188, RegionName.mm, 250000),
    LocationName.black_purch: LocationData(base_location_id + 189, RegionName.mm, 250000),
    LocationName.xeno_luna_purch: LocationData(base_location_id + 190, RegionName.mm, 30000),
    LocationName.ron_reg_cattermole_purch: LocationData(base_location_id + 191, RegionName.mm, 75000),
    LocationName.tonks_pink_coat_purch: LocationData(base_location_id + 192, RegionName.mm, 125000),
    LocationName.ron_winter_clothes_purch: LocationData(base_location_id + 193, RegionName.mm, 45000),
    LocationName.snape_underwear_purch: LocationData(base_location_id + 194, RegionName.mm, 250000),
    LocationName.rowle_purch: LocationData(base_location_id + 195, RegionName.mm, 60000),
    LocationName.petunia_purch: LocationData(base_location_id + 196, RegionName.mm, 60000),
    LocationName.neville_tank_top_purch: LocationData(base_location_id + 197, RegionName.mm, 50000),
    LocationName.neville_winter_purch: LocationData(base_location_id + 198, RegionName.mm, 50000),
    LocationName.parvati_purch: LocationData(base_location_id + 199, RegionName.mm, 10000),
    LocationName.ron_red_sweater_purch: LocationData(base_location_id + 200, RegionName.mm, 62500),
    LocationName.ollivander_purch: LocationData(base_location_id + 201, RegionName.mm, 60000),
    LocationName.seamus_winter_purch: LocationData(base_location_id + 202, RegionName.mm, 10000),
    LocationName.ron_underwear_purch: LocationData(base_location_id + 203, RegionName.mm, 60000),
    LocationName.ron_wedding_purch: LocationData(base_location_id + 204, RegionName.mm, 95000),
    LocationName.waitress_luchino_purch: LocationData(base_location_id + 205, RegionName.mm, 30000),
    LocationName.petunia_green_coat_purch: LocationData(base_location_id + 206, RegionName.mm, 60000),
    LocationName.seamus_purch: LocationData(base_location_id + 207, RegionName.mm, 10000),
    LocationName.snatcher_purch: LocationData(base_location_id + 208, RegionName.mm, 30000),
    LocationName.ron_green_shirt_purch: LocationData(base_location_id + 209, RegionName.mm, 60000),
    LocationName.neville_waiter_purch: LocationData(base_location_id + 210, RegionName.mm, 250000),
    LocationName.xeno_wedding_purch: LocationData(base_location_id + 211, RegionName.mm, 30000),
    LocationName.skeleton_purch: LocationData(base_location_id + 212, RegionName.mm, 5000000),
}

# 213 - 425
character_token_location_table: Dict[str, LocationData] = {
    LocationName.hagrid_token: LocationData(base_location_id + 213, RegionName.fff),
    LocationName.fang_token: LocationData(base_location_id + 214, RegionName.fff),
    LocationName.hagrid_wed_token: LocationData(base_location_id + 215, RegionName.thathf),
    LocationName.prof_flit_token: LocationData(base_location_id + 216, RegionName.y5c),
    LocationName.madam_malk_token: LocationData(base_location_id + 217, RegionName.mm),
    LocationName.dobby_token: LocationData(base_location_id + 218, RegionName.dobf),
    LocationName.kreacher_token: LocationData(base_location_id + 219, RegionName.kd),
    LocationName.tr_orphanage_token: LocationData(base_location_id + 220, RegionName.thathf),
    LocationName.bogrod_token: LocationData(base_location_id + 221, RegionName.ttdf),
    LocationName.mund_fletch_token: LocationData(base_location_id + 222, RegionName.diag),
    LocationName.griphook_token: LocationData(base_location_id + 223, RegionName.ttd),
    LocationName.prof_mcgon_token: LocationData(base_location_id + 224, RegionName.ast),
    LocationName.madam_pince_token: LocationData(base_location_id + 225, RegionName.lib),
    LocationName.prof_sprout_token: LocationData(base_location_id + 226, RegionName.ff),
    LocationName.madam_pomfrey_token: LocationData(base_location_id + 227, RegionName.huff),
    LocationName.prof_trelawney_token: LocationData(base_location_id + 228, RegionName.div),
    LocationName.madam_rosmerta_token: LocationData(base_location_id + 229, RegionName.jd),
    LocationName.fat_friar_token: LocationData(base_location_id + 230, RegionName.gh),
    LocationName.grey_lady_token: LocationData(base_location_id + 231, RegionName.bbf),
    LocationName.fat_lady_token: LocationData(base_location_id + 232, RegionName.dormlob),
    LocationName.herm_ball_token: LocationData(base_location_id + 233, RegionName.gryf),
    LocationName.bellatrix_token: LocationData(base_location_id + 234, RegionName.tfitpf),
    LocationName.emmeline_token: LocationData(base_location_id + 235, RegionName.agv),
    LocationName.narcissa_token: LocationData(base_location_id + 236, RegionName.knock),
    LocationName.mcgon_pyjamas_token: LocationData(base_location_id + 237, RegionName.gryf),
    LocationName.mary_cattermole_token: LocationData(base_location_id + 238, RegionName.lond),
    LocationName.mcgon_black_token: LocationData(base_location_id + 239, RegionName.quad),
    LocationName.herm_gringotts_token: LocationData(base_location_id + 240, RegionName.ttdf),
    LocationName.prof_grubbly_token: LocationData(base_location_id + 241, RegionName.ground),
    LocationName.bellatrix_azka_token: LocationData(base_location_id + 242, RegionName.ground),
    LocationName.death_eater_token: LocationData(base_location_id + 243, RegionName.stf),
    LocationName.dudley_grey_token: LocationData(base_location_id + 244, RegionName.dt),
    LocationName.prof_dumble_token: LocationData(base_location_id + 245, RegionName.thath),
    # LocationName.harry_token: LocationData(base_location_id + 246, RegionName.mm),
    # LocationName.herm_token: LocationData(base_location_id + 247, RegionName.mm),
    LocationName.argus_token: LocationData(base_location_id + 248, RegionName.wcs),
    LocationName.madam_hooch_token: LocationData(base_location_id + 249, RegionName.qp),
    LocationName.crabbe_token: LocationData(base_location_id + 250, RegionName.ror),
    LocationName.goyle_token: LocationData(base_location_id + 251, RegionName.fiendf),
    LocationName.ginny_token: LocationData(base_location_id + 252, RegionName.lh),
    LocationName.arthur_token: LocationData(base_location_id + 253, RegionName.kd),
    LocationName.katie_token: LocationData(base_location_id + 254, RegionName.thest),
    LocationName.lily_token: LocationData(base_location_id + 255, RegionName.igd),
    LocationName.bloody_baron_token: LocationData(base_location_id + 256, RegionName.gh),
    LocationName.fudge_token: LocationData(base_location_id + 257, RegionName.tg),
    LocationName.justin_token: LocationData(base_location_id + 258, RegionName.y5c),
    LocationName.cho_token: LocationData(base_location_id + 259, RegionName.y6c),
    LocationName.dean_token: LocationData(base_location_id + 260, RegionName.ghl),
    LocationName.draco_token: LocationData(base_location_id + 261, RegionName.dada),
    LocationName.lucius_token: LocationData(base_location_id + 262, RegionName.wild),
    LocationName.draco_suit_token: LocationData(base_location_id + 263, RegionName.lhf),
    # LocationName.custom_a_token: LocationData(base_location_id + 264, RegionName.mm),
    # LocationName.custom_b_token: LocationData(base_location_id + 265, RegionName.mm),
    # LocationName.custom_c_token: LocationData(base_location_id + 266, RegionName.mm),
    # LocationName.custom_d_token: LocationData(base_location_id + 267, RegionName.mm),
    # LocationName.custom_e_token: LocationData(base_location_id + 268, RegionName.mm),
    # LocationName.custom_g_token: LocationData(base_location_id + 269, RegionName.mm),
    # LocationName.custom_h_token: LocationData(base_location_id + 270, RegionName.mm),
    # LocationName.custom_i_token: LocationData(base_location_id + 271, RegionName.mm),
    # LocationName.custom_j_token: LocationData(base_location_id + 272, RegionName.mm),
    LocationName.harry_pyjamas_token: LocationData(base_location_id + 273, RegionName.gryf),
    LocationName.myrtle_token: LocationData(base_location_id + 274, RegionName.raven),
    LocationName.james_ghost_token: LocationData(base_location_id + 275, RegionName.wild),
    LocationName.madeye_token: LocationData(base_location_id + 276, RegionName.tsh),
    LocationName.hannah_token: LocationData(base_location_id + 277, RegionName.y5c),
    # LocationName.custom_f_token: LocationData(base_location_id + 278, RegionName.mm),
    LocationName.kingsley_token: LocationData(base_location_id + 279, RegionName.tfitpf),
    LocationName.aberforth_token: LocationData(base_location_id + 280, RegionName.bts),
    LocationName.runcorn_token: LocationData(base_location_id + 281, RegionName.wild),
    LocationName.alecto_token: LocationData(base_location_id + 282, RegionName.bts),
    LocationName.amycus_token: LocationData(base_location_id + 283, RegionName.btsf),
    LocationName.anthony_token: LocationData(base_location_id + 284, RegionName.lib),
    LocationName.bathilda_snake_token: LocationData(base_location_id + 285, RegionName.igdf),
    LocationName.blaise_token: LocationData(base_location_id + 286, RegionName.slyth),
    LocationName.charity_token: LocationData(base_location_id + 287, RegionName.pot),
    LocationName.charlie_token: LocationData(base_location_id + 288, RegionName.wc),
    LocationName.cormac_token: LocationData(base_location_id + 289, RegionName.ror),
    LocationName.dedalus_token: LocationData(base_location_id + 290, RegionName.upper_stair),
    LocationName.dirk_token: LocationData(base_location_id + 291, RegionName.ror),
    LocationName.dolohov_token: LocationData(base_location_id + 292, RegionName.ast),
    LocationName.dragomir_token: LocationData(base_location_id + 293, RegionName.wild),
    LocationName.elphias_token: LocationData(base_location_id + 294, RegionName.dt),
    LocationName.fenrir_token: LocationData(base_location_id + 295, RegionName.st),
    LocationName.grindel_young_token: LocationData(base_location_id + 296, RegionName.ast),
    LocationName.grindel_old_token: LocationData(base_location_id + 297, RegionName.ast),
    LocationName.gregorovitch_token: LocationData(base_location_id + 298, RegionName.diag),
    LocationName.hestia_token: LocationData(base_location_id + 299, RegionName.leaky),
    LocationName.prof_slughorn_token: LocationData(base_location_id + 300, RegionName.lh),
    LocationName.james_young_token: LocationData(base_location_id + 301, RegionName.hogwpath),
    LocationName.lavender_token: LocationData(base_location_id + 302, RegionName.y6c),
    LocationName.mafalda_token: LocationData(base_location_id + 303, RegionName.lond),
    LocationName.belby_token: LocationData(base_location_id + 304, RegionName.raven),
    LocationName.luna_purple_coat_token: LocationData(base_location_id + 305, RegionName.llf),
    LocationName.herm_grey_coat_token: LocationData(base_location_id + 306, RegionName.sal),
    LocationName.harry_godric_token: LocationData(base_location_id + 307, RegionName.igdf),
    LocationName.prof_umbridge_token: LocationData(base_location_id + 308, RegionName.agv),
    LocationName.fred_token: LocationData(base_location_id + 309, RegionName.www),
    LocationName.george_token: LocationData(base_location_id + 310, RegionName.www),
    LocationName.molly_apron_token: LocationData(base_location_id + 311, RegionName.focf),
    LocationName.crabbe_jumper_token: LocationData(base_location_id + 312, RegionName.lake),
    LocationName.draco_sweater_token: LocationData(base_location_id + 313, RegionName.slyth),
    LocationName.goyle_jumper_token: LocationData(base_location_id + 314, RegionName.slyth),
    LocationName.milk_man_token: LocationData(base_location_id + 315, RegionName.oorf),
    LocationName.twin_2_token: LocationData(base_location_id + 316, RegionName.knock),
    LocationName.herm_mafalda_token: LocationData(base_location_id + 317, RegionName.mimf),
    LocationName.ministry_guard_token: LocationData(base_location_id + 318, RegionName.lond),
    LocationName.harry_winter_token: LocationData(base_location_id + 319, RegionName.hogs),
    LocationName.arthur_torn_suit_token: LocationData(base_location_id + 320, RegionName.wcs),
    LocationName.fred_winter_token: LocationData(base_location_id + 321, RegionName.hogspath),
    LocationName.cho_winter_token: LocationData(base_location_id + 322, RegionName.da),
    LocationName.george_winter_token: LocationData(base_location_id + 323, RegionName.hogspath),
    LocationName.herm_scarf_token: LocationData(base_location_id + 324, RegionName.da),
    LocationName.luna_blue_jumper_token: LocationData(base_location_id + 325, RegionName.thest),
    LocationName.fred_owls_token: LocationData(base_location_id + 326, RegionName.wc),
    LocationName.fred_pyjamas_token: LocationData(base_location_id + 327, RegionName.www),
    LocationName.george_owls_token: LocationData(base_location_id + 328, RegionName.wc),
    LocationName.george_pyjamas_token: LocationData(base_location_id + 329, RegionName.www),
    LocationName.herm_jumper_token: LocationData(base_location_id + 330, RegionName.avt),
    LocationName.fudge_wizengamot_token: LocationData(base_location_id + 331, RegionName.avt),
    LocationName.dudley_token: LocationData(base_location_id + 332, RegionName.cafe),
    LocationName.gang_mem_token: LocationData(base_location_id + 333, RegionName.foc),
    LocationName.harry_albert_runcorn_token: LocationData(base_location_id + 334, RegionName.mim),
    LocationName.harry_brown_jacket_token: LocationData(base_location_id + 335, RegionName.fiendf),
    LocationName.dumble_cursed_token: LocationData(base_location_id + 336, RegionName.oorf),
    LocationName.lucius_death_eater_token: LocationData(base_location_id + 337, RegionName.avt),
    LocationName.luna_token: LocationData(base_location_id + 338, RegionName.hogwpath),
    LocationName.umbridge_wizengamot_token: LocationData(base_location_id + 339, RegionName.dada),
    LocationName.dolohov_workman_token: LocationData(base_location_id + 340, RegionName.cafe),
    LocationName.michael_token: LocationData(base_location_id + 341, RegionName.hogspath),
    LocationName.dean_winter_token: LocationData(base_location_id + 342, RegionName.hogs),
    LocationName.arthur_cardigan_token: LocationData(base_location_id + 343, RegionName.herb),
    LocationName.luna_pink_dress_token: LocationData(base_location_id + 344, RegionName.raven),
    LocationName.marietta_token: LocationData(base_location_id + 345, RegionName.hogs),
    LocationName.dumble_young_token: LocationData(base_location_id + 346, RegionName.dumble_office),
    LocationName.slughorn_young_token: LocationData(base_location_id + 347, RegionName.herb),
    LocationName.slughorn_pyjamas_token: LocationData(base_location_id + 348, RegionName.oorf),
    LocationName.lily_young_casual_token: LocationData(base_location_id + 349, RegionName.hogwpath),
    LocationName.ginny_dress_token: LocationData(base_location_id + 350, RegionName.divc),
    LocationName.ginny_pyjamas_token: LocationData(base_location_id + 351, RegionName.gryf),
    LocationName.blaise_black_shirt_token: LocationData(base_location_id + 352, RegionName.ror),
    LocationName.cormac_suit_token: LocationData(base_location_id + 353, RegionName.jd),
    LocationName.muggle_orphan_token: LocationData(base_location_id + 354, RegionName.kcs),
    LocationName.luna_overalls_token: LocationData(base_location_id + 355, RegionName.hogstat),
    LocationName.molly_token: LocationData(base_location_id + 356, RegionName.ansmcf),
    LocationName.herm_cardigan_token: LocationData(base_location_id + 357, RegionName.cl),
    LocationName.luna_yellow_dress_token: LocationData(base_location_id + 358, RegionName.ror),
    LocationName.dudley_shirt_token: LocationData(base_location_id + 359, RegionName.kcs),
    LocationName.bill_wedding_token: LocationData(base_location_id + 360, RegionName.ansmc),
    LocationName.fleur_token: LocationData(base_location_id + 361, RegionName.wild),
    LocationName.herm_red_dress_token: LocationData(base_location_id + 362, RegionName.tshf),
    LocationName.figg_token: LocationData(base_location_id + 363, RegionName.leaky),
    LocationName.harry_locket_token: LocationData(base_location_id + 364, RegionName.sal),
    LocationName.twin_1_token: LocationData(base_location_id + 365, RegionName.knock),
    LocationName.cole_token: LocationData(base_location_id + 366, RegionName.cafe),
    LocationName.herm_ministry_token: LocationData(base_location_id + 367, RegionName.wild),
    LocationName.arthur_suit_token: LocationData(base_location_id + 368, RegionName.dt),
    LocationName.harry_christmas_token: LocationData(base_location_id + 369, RegionName.jd),
    LocationName.ernie_token: LocationData(base_location_id + 370, RegionName.dumble_office),
    LocationName.prof_snape_token: LocationData(base_location_id + 371, RegionName.stf),
    LocationName.neville_token: LocationData(base_location_id + 372, RegionName.agv),
    # LocationName.ron_token: LocationData(base_location_id + 373, RegionName.mm),
    LocationName.ron_quidditch_token: LocationData(base_location_id + 374, RegionName.qp),
    LocationName.vernon_token: LocationData(base_location_id + 375, RegionName.cafe),
    LocationName.tom_riddle_token: LocationData(base_location_id + 376, RegionName.fiendf),
    LocationName.sirius_black_token: LocationData(base_location_id + 377, RegionName.kd),
    LocationName.remus_lupin_token: LocationData(base_location_id + 378, RegionName.wild),
    LocationName.wormtail_token: LocationData(base_location_id + 379, RegionName.dob),
    LocationName.rita_skeeter_token: LocationData(base_location_id + 380, RegionName.foyer),
    LocationName.padma_patil_token: LocationData(base_location_id + 381, RegionName.thest),
    LocationName.station_guard_token: LocationData(base_location_id + 382, RegionName.hogstat),
    LocationName.prof_binns_token: LocationData(base_location_id + 383, RegionName.lake),
    LocationName.penelope_token: LocationData(base_location_id + 384, RegionName.gh),
    LocationName.susan_token: LocationData(base_location_id + 385, RegionName.foyer),
    LocationName.tonks_token: LocationData(base_location_id + 386, RegionName.qp),
    LocationName.pius_token: LocationData(base_location_id + 387, RegionName.knock),
    LocationName.reg_token: LocationData(base_location_id + 388, RegionName.wild),
    LocationName.regulus_token: LocationData(base_location_id + 389, RegionName.dumble_office),
    LocationName.scrimgeour_token: LocationData(base_location_id + 390, RegionName.lond),
    LocationName.scabior_token: LocationData(base_location_id + 391, RegionName.wild),
    LocationName.xeno_token: LocationData(base_location_id + 392, RegionName.wild),
    LocationName.yaxley_token: LocationData(base_location_id + 393, RegionName.wild),
    LocationName.zacharias_token: LocationData(base_location_id + 394, RegionName.mid_stair),
    LocationName.waitress_treats_token: LocationData(base_location_id + 395, RegionName.kcs),
    LocationName.lord_voldemort_token: LocationData(base_location_id + 396, RegionName.tfitpf),
    LocationName.ron_blue_pyjamas_token: LocationData(base_location_id + 397, RegionName.dormlob),
    LocationName.neville_cardigan_token: LocationData(base_location_id + 398, RegionName.bbf),
    LocationName.neville_pyjamas_token: LocationData(base_location_id + 399, RegionName.div),
    LocationName.percy_token: LocationData(base_location_id + 400, RegionName.wild),
    LocationName.sirius_azkaban_token: LocationData(base_location_id + 401, RegionName.knock),
    LocationName.black_token: LocationData(base_location_id + 402, RegionName.knock),
    LocationName.xeno_luna_token: LocationData(base_location_id + 403, RegionName.ll),
    LocationName.ron_reg_cattermole_token: LocationData(base_location_id + 404, RegionName.mim),
    LocationName.tonks_pink_coat_token: LocationData(base_location_id + 405, RegionName.ansmcf),
    LocationName.ron_winter_clothes_token: LocationData(base_location_id + 406, RegionName.wild),
    LocationName.snape_underwear_token: LocationData(base_location_id + 407, RegionName.focf),
    LocationName.rowle_token: LocationData(base_location_id + 408, RegionName.cafe),
    LocationName.petunia_token: LocationData(base_location_id + 409, RegionName.cafe),
    LocationName.neville_tank_top_token: LocationData(base_location_id + 410, RegionName.huff),
    LocationName.neville_winter_token: LocationData(base_location_id + 411, RegionName.da),
    LocationName.parvati_token: LocationData(base_location_id + 412, RegionName.hogs),
    LocationName.ron_red_sweater_token: LocationData(base_location_id + 413, RegionName.cl),
    LocationName.ollivander_token: LocationData(base_location_id + 414, RegionName.dob),
    LocationName.seamus_winter_token: LocationData(base_location_id + 415, RegionName.hogs),
    LocationName.ron_underwear_token: LocationData(base_location_id + 416, RegionName.sal),
    LocationName.ron_wedding_token: LocationData(base_location_id + 417, RegionName.tshf),
    LocationName.waitress_luchino_token: LocationData(base_location_id + 418, RegionName.cafe),
    LocationName.petunia_green_coat_token: LocationData(base_location_id + 419, RegionName.cafe),
    LocationName.seamus_token: LocationData(base_location_id + 420, RegionName.bbf),
    LocationName.snatcher_token: LocationData(base_location_id + 421, RegionName.wild),
    LocationName.ron_green_shirt_token: LocationData(base_location_id + 422, RegionName.ghl),
    LocationName.neville_waiter_token: LocationData(base_location_id + 423, RegionName.divc),
    LocationName.xeno_wedding_token: LocationData(base_location_id + 424, RegionName.tent),
    LocationName.skeleton_token: LocationData(base_location_id + 425, RegionName.llf),
}


# 450 - 473
level_beaten_loc_table: Dict[str, LocationData] = {
    LocationName.dt_beat: LocationData(base_location_id + 450, RegionName.dt),
    LocationName.da_beat: LocationData(base_location_id + 451, RegionName.da),
    LocationName.foc_beat: LocationData(base_location_id + 452, RegionName.focf),
    LocationName.kd_beat: LocationData(base_location_id + 453, RegionName.kd),
    LocationName.agv_beat: LocationData(base_location_id + 454, RegionName.agv),
    LocationName.avt_beat: LocationData(base_location_id + 455, RegionName.avt),
    LocationName.oor_beat: LocationData(base_location_id + 456, RegionName.oorf),
    LocationName.jd_beat: LocationData(base_location_id + 457, RegionName.jd),
    LocationName.ansmc_beat: LocationData(base_location_id + 458, RegionName.ansmcf),
    LocationName.lh_beat: LocationData(base_location_id + 459, RegionName.lhf),
    LocationName.ff_beat: LocationData(base_location_id + 460, RegionName.fff),
    LocationName.thath_beat: LocationData(base_location_id + 461, RegionName.thathf),
    LocationName.tsh_beat: LocationData(base_location_id + 462, RegionName.tshf),
    LocationName.mim_beat: LocationData(base_location_id + 463, RegionName.mimf),
    LocationName.igd_beat: LocationData(base_location_id + 464, RegionName.igdf),
    LocationName.sal_beat: LocationData(base_location_id + 465, RegionName.sal),
    LocationName.ll_beat: LocationData(base_location_id + 466, RegionName.llf),
    LocationName.dob_beat: LocationData(base_location_id + 467, RegionName.dobf),
    LocationName.ttd_beat: LocationData(base_location_id + 468, RegionName.ttdf),
    LocationName.bts_beat: LocationData(base_location_id + 469, RegionName.btsf),
    LocationName.bb_beat: LocationData(base_location_id + 470, RegionName.bbf),
    LocationName.fiend_beat: LocationData(base_location_id + 471, RegionName.fiendf),
    LocationName.st_beat: LocationData(base_location_id + 472, RegionName.stf),
    LocationName.tfitp_beat: LocationData(base_location_id + 473, RegionName.tfitpf),
}

# 475 - 498
leve_sip_loc_table: Dict[str, LocationData] = {
    LocationName.dt_sip: LocationData(base_location_id + 475, RegionName.dt),
    LocationName.da_sip: LocationData(base_location_id + 476, RegionName.da),
    LocationName.foc_sip: LocationData(base_location_id + 477, RegionName.focf),
    LocationName.kd_sip: LocationData(base_location_id + 478, RegionName.kd),
    LocationName.agv_sip: LocationData(base_location_id + 479, RegionName.agv),
    LocationName.avt_sip: LocationData(base_location_id + 480, RegionName.avt),
    LocationName.oor_sip: LocationData(base_location_id + 481, RegionName.oorf),
    LocationName.jd_sip: LocationData(base_location_id + 482, RegionName.jd),
    LocationName.ansmc_sip: LocationData(base_location_id + 483, RegionName.ansmcf),
    LocationName.lh_sip: LocationData(base_location_id + 484, RegionName.lhf),
    LocationName.ff_sip: LocationData(base_location_id + 485, RegionName.fff),
    LocationName.thath_sip: LocationData(base_location_id + 486, RegionName.thathf),
    LocationName.tsh_sip: LocationData(base_location_id + 487, RegionName.tsh),
    LocationName.mim_sip: LocationData(base_location_id + 488, RegionName.mimf),
    LocationName.igd_sip: LocationData(base_location_id + 489, RegionName.igd),
    LocationName.sal_sip: LocationData(base_location_id + 490, RegionName.sal),
    LocationName.ll_sip: LocationData(base_location_id + 491, RegionName.ll),
    LocationName.dob_sip: LocationData(base_location_id + 492, RegionName.dob),
    LocationName.ttd_sip: LocationData(base_location_id + 493, RegionName.ttdf),
    LocationName.bts_sip: LocationData(base_location_id + 494, RegionName.bts),
    LocationName.bb_sip: LocationData(base_location_id + 495, RegionName.bbf),
    LocationName.fiend_sip: LocationData(base_location_id + 496, RegionName.fiend),
    LocationName.st_sip: LocationData(base_location_id + 497, RegionName.stf),
    LocationName.tfitp_sip: LocationData(base_location_id + 498, RegionName.tfitp),
}

# 499 - 538
hub_sip_loc_table: Dict[str, LocationData] = {
    LocationName.tent_sip: LocationData(base_location_id + 499, RegionName.tent),
    LocationName.wild_sip: LocationData(base_location_id + 500, RegionName.wild),
    LocationName.cafe_sip: LocationData(base_location_id + 501, RegionName.cafe),
    LocationName.lond_sip: LocationData(base_location_id + 502, RegionName.lond),
    LocationName.kcs_sip: LocationData(base_location_id + 503, RegionName.kcs),
    LocationName.hogspath_sip: LocationData(base_location_id + 504, RegionName.hogspath),
    LocationName.hogs_sip: LocationData(base_location_id + 505, RegionName.hogs),
    LocationName.hogstat_sip: LocationData(base_location_id + 506, RegionName.hogstat),
    LocationName.hogwpath_sip: LocationData(base_location_id + 507, RegionName.hogwpath),
    LocationName.herb_sip: LocationData(base_location_id + 508, RegionName.herb),
    LocationName.tg_sip: LocationData(base_location_id + 509, RegionName.tg),
    LocationName.quad_sip: LocationData(base_location_id + 510, RegionName.quad),
    LocationName.ror_sip: LocationData(base_location_id + 511, RegionName.ror),
    LocationName.wcs_sip: LocationData(base_location_id + 512, RegionName.wcs),
    LocationName.wc_sip: LocationData(base_location_id + 513, RegionName.wc),
    LocationName.gh_sip: LocationData(base_location_id + 514, RegionName.gh),
    LocationName.ghl_sip: LocationData(base_location_id + 515, RegionName.ghl),
    LocationName.lake_sip: LocationData(base_location_id + 516, RegionName.lake),
    # LocationName.qp_sip: LocationData(base_location_id + 517, RegionName.qp),
    LocationName.thest_sip: LocationData(base_location_id + 518, RegionName.thest),
    LocationName.ground_sip: LocationData(base_location_id + 519, RegionName.ground),
    LocationName.raven_sip: LocationData(base_location_id + 520, RegionName.raven),
    LocationName.gryf_sip: LocationData(base_location_id + 521, RegionName.gryf),
    LocationName.dormlob_sip: LocationData(base_location_id + 522, RegionName.dormlob),
    LocationName.ast_sip: LocationData(base_location_id + 523, RegionName.ast),
    LocationName.y6c_sip: LocationData(base_location_id + 524, RegionName.y6c),
    LocationName.y5c_sip: LocationData(base_location_id + 525, RegionName.y5c),
    LocationName.pot_sip: LocationData(base_location_id + 526, RegionName.pot),
    LocationName.div_sip: LocationData(base_location_id + 527, RegionName.div),
    LocationName.dada_sip: LocationData(base_location_id + 528, RegionName.dada),
    LocationName.divc_sip: LocationData(base_location_id + 529, RegionName.divc),
    LocationName.cl_sip: LocationData(base_location_id + 530, RegionName.cl),
    LocationName.stair_sip: LocationData(base_location_id + 531, RegionName.low_stair),
    LocationName.lib_sip: LocationData(base_location_id + 532, RegionName.lib),
    LocationName.foyer_sip: LocationData(base_location_id + 533, RegionName.foyer),
    LocationName.mm_sip: LocationData(base_location_id + 534, RegionName.mm),
    LocationName.knock_sip: LocationData(base_location_id + 535, RegionName.knock),
    LocationName.leaky_sip: LocationData(base_location_id + 536, RegionName.leaky),
    LocationName.www_sip: LocationData(base_location_id + 537, RegionName.www),
    # LocationName.diag_sip: LocationData(base_location_id + 538, RegionName.diag),
}

# 550 - 525
house_crest_loc_table: Dict[str, LocationData] = {
    # Gryff Crests
    LocationName.dt_gc: LocationData(base_location_id + 550, RegionName.dt),
    LocationName.da_gc: LocationData(base_location_id + 551, RegionName.da),
    LocationName.foc_gc: LocationData(base_location_id + 552, RegionName.focf),
    LocationName.kd_gc: LocationData(base_location_id + 553, RegionName.kd),
    LocationName.agv_gc: LocationData(base_location_id + 554, RegionName.agv),
    LocationName.avt_gc: LocationData(base_location_id + 555, RegionName.avt),
    LocationName.oor_gc: LocationData(base_location_id + 556, RegionName.oorf),
    LocationName.jd_gc: LocationData(base_location_id + 557, RegionName.jd),
    LocationName.ansmc_gc: LocationData(base_location_id + 558, RegionName.ansmcf),
    LocationName.lh_gc: LocationData(base_location_id + 559, RegionName.lhf),
    LocationName.ff_gc: LocationData(base_location_id + 560, RegionName.ff),
    LocationName.thath_gc: LocationData(base_location_id + 561, RegionName.thathf),
    LocationName.tsh_gc: LocationData(base_location_id + 562, RegionName.tsh),
    LocationName.mim_gc: LocationData(base_location_id + 563, RegionName.mim),
    LocationName.igd_gc: LocationData(base_location_id + 564, RegionName.igd),
    LocationName.sal_gc: LocationData(base_location_id + 565, RegionName.sal),
    LocationName.ll_gc: LocationData(base_location_id + 566, RegionName.ll),
    LocationName.dob_gc: LocationData(base_location_id + 567, RegionName.dob),
    LocationName.ttd_gc: LocationData(base_location_id + 568, RegionName.ttd),
    LocationName.bts_gc: LocationData(base_location_id + 569, RegionName.bts),
    LocationName.bb_gc: LocationData(base_location_id + 570, RegionName.bbf),
    LocationName.fiend_gc: LocationData(base_location_id + 571, RegionName.fiendf),
    LocationName.st_gc: LocationData(base_location_id + 572, RegionName.st),
    LocationName.tfitp_gc: LocationData(base_location_id + 573, RegionName.tfitpf),
    # Slyth Crests
    LocationName.dt_sc: LocationData(base_location_id + 574, RegionName.dt),
    LocationName.da_sc: LocationData(base_location_id + 575, RegionName.da),
    LocationName.foc_sc: LocationData(base_location_id + 576, RegionName.foc),
    LocationName.kd_sc: LocationData(base_location_id + 577, RegionName.kd),
    LocationName.agv_sc: LocationData(base_location_id + 578, RegionName.agv),
    LocationName.avt_sc: LocationData(base_location_id + 579, RegionName.avt),
    LocationName.oor_sc: LocationData(base_location_id + 580, RegionName.oorf),
    LocationName.jd_sc: LocationData(base_location_id + 581, RegionName.jd),
    LocationName.ansmc_sc: LocationData(base_location_id + 582, RegionName.ansmc),
    LocationName.lh_sc: LocationData(base_location_id + 583, RegionName.lhf),
    LocationName.ff_sc: LocationData(base_location_id + 584, RegionName.ff),
    LocationName.thath_sc: LocationData(base_location_id + 585, RegionName.thathf),
    LocationName.tsh_sc: LocationData(base_location_id + 586, RegionName.tsh),
    LocationName.mim_sc: LocationData(base_location_id + 587, RegionName.mimf),
    LocationName.igd_sc: LocationData(base_location_id + 588, RegionName.igdf),
    LocationName.sal_sc: LocationData(base_location_id + 589, RegionName.sal),
    LocationName.ll_sc: LocationData(base_location_id + 590, RegionName.ll),
    LocationName.dob_sc: LocationData(base_location_id + 591, RegionName.dobf),
    LocationName.ttd_sc: LocationData(base_location_id + 592, RegionName.ttdf),
    LocationName.bts_sc: LocationData(base_location_id + 593, RegionName.btsf),
    LocationName.bb_sc: LocationData(base_location_id + 594, RegionName.bb),
    LocationName.fiend_sc: LocationData(base_location_id + 595, RegionName.fiendf),
    LocationName.st_sc: LocationData(base_location_id + 596, RegionName.stf),
    LocationName.tfitp_sc: LocationData(base_location_id + 597, RegionName.tfitpf),
    # Raven Crests
    LocationName.dt_rc: LocationData(base_location_id + 598, RegionName.dt),
    LocationName.da_rc: LocationData(base_location_id + 599, RegionName.da),
    LocationName.foc_rc: LocationData(base_location_id + 600, RegionName.focf),
    LocationName.kd_rc: LocationData(base_location_id + 601, RegionName.kd),
    LocationName.agv_rc: LocationData(base_location_id + 602, RegionName.agv),
    LocationName.avt_rc: LocationData(base_location_id + 603, RegionName.avt),
    LocationName.oor_rc: LocationData(base_location_id + 604, RegionName.oor),
    LocationName.jd_rc: LocationData(base_location_id + 605, RegionName.jd),
    LocationName.ansmc_rc: LocationData(base_location_id + 606, RegionName.ansmc),
    LocationName.lh_rc: LocationData(base_location_id + 607, RegionName.lh),
    LocationName.ff_rc: LocationData(base_location_id + 608, RegionName.fff),
    LocationName.thath_rc: LocationData(base_location_id + 609, RegionName.thath),
    LocationName.tsh_rc: LocationData(base_location_id + 610, RegionName.tsh),
    LocationName.mim_rc: LocationData(base_location_id + 611, RegionName.mim),
    LocationName.igd_rc: LocationData(base_location_id + 612, RegionName.igd),
    LocationName.sal_rc: LocationData(base_location_id + 613, RegionName.sal),
    LocationName.ll_rc: LocationData(base_location_id + 614, RegionName.llf),
    LocationName.dob_rc: LocationData(base_location_id + 615, RegionName.dobf),
    LocationName.ttd_rc: LocationData(base_location_id + 616, RegionName.ttdf),
    LocationName.bts_rc: LocationData(base_location_id + 617, RegionName.btsf),
    LocationName.bb_rc: LocationData(base_location_id + 618, RegionName.bbf),
    LocationName.fiend_rc: LocationData(base_location_id + 619, RegionName.fiend),
    LocationName.st_rc: LocationData(base_location_id + 620, RegionName.stf),
    LocationName.tfitp_rc: LocationData(base_location_id + 621, RegionName.tfitpf),
    # Huffle Crests
    LocationName.dt_hc: LocationData(base_location_id + 622, RegionName.dt),
    LocationName.da_hc: LocationData(base_location_id + 623, RegionName.da),
    LocationName.foc_hc: LocationData(base_location_id + 624, RegionName.focf),
    LocationName.kd_hc: LocationData(base_location_id + 625, RegionName.kd),
    LocationName.agv_hc: LocationData(base_location_id + 626, RegionName.agv),
    LocationName.avt_hc: LocationData(base_location_id + 627, RegionName.avt),
    LocationName.oor_hc: LocationData(base_location_id + 628, RegionName.oorf),
    LocationName.jd_hc: LocationData(base_location_id + 629, RegionName.jd),
    LocationName.ansmc_hc: LocationData(base_location_id + 630, RegionName.ansmcf),
    LocationName.lh_hc: LocationData(base_location_id + 631, RegionName.lhf),
    LocationName.ff_hc: LocationData(base_location_id + 632, RegionName.fff),
    LocationName.thath_hc: LocationData(base_location_id + 633, RegionName.thathf),
    LocationName.tsh_hc: LocationData(base_location_id + 634, RegionName.tshf),
    LocationName.mim_hc: LocationData(base_location_id + 635, RegionName.mimf),
    LocationName.igd_hc: LocationData(base_location_id + 636, RegionName.igd),
    LocationName.sal_hc: LocationData(base_location_id + 637, RegionName.sal),
    LocationName.ll_hc: LocationData(base_location_id + 638, RegionName.llf),
    LocationName.dob_hc: LocationData(base_location_id + 639, RegionName.dob),
    LocationName.ttd_hc: LocationData(base_location_id + 640, RegionName.ttdf),
    LocationName.bts_hc: LocationData(base_location_id + 641, RegionName.bts),
    LocationName.bb_hc: LocationData(base_location_id + 642, RegionName.bbf),
    LocationName.fiend_hc: LocationData(base_location_id + 643, RegionName.fiendf),
    LocationName.st_hc: LocationData(base_location_id + 644, RegionName.stf),
    LocationName.tfitp_hc: LocationData(base_location_id + 645, RegionName.tfitp),
}

# 650 - 673
# House Crest Completed

# 675 - 698
true_wizard_loc_table: Dict[str, LocationData] = {
    LocationName.dt_tw: LocationData(base_location_id + 675, RegionName.dt),
    LocationName.da_tw: LocationData(base_location_id + 676, RegionName.da),
    LocationName.foc_tw: LocationData(base_location_id + 677, RegionName.focf),
    LocationName.kd_tw: LocationData(base_location_id + 678, RegionName.kd),
    LocationName.agv_tw: LocationData(base_location_id + 679, RegionName.agv),
    LocationName.avt_tw: LocationData(base_location_id + 680, RegionName.avt),
    LocationName.oor_tw: LocationData(base_location_id + 681, RegionName.oorf),
    LocationName.jd_tw: LocationData(base_location_id + 682, RegionName.jd),
    LocationName.ansmc_tw: LocationData(base_location_id + 683, RegionName.ansmcf),
    LocationName.lh_tw: LocationData(base_location_id + 684, RegionName.lhf),
    LocationName.ff_tw: LocationData(base_location_id + 685, RegionName.fff),
    LocationName.thath_tw: LocationData(base_location_id + 686, RegionName.thathf),
    LocationName.tsh_tw: LocationData(base_location_id + 687, RegionName.tshf),
    LocationName.mim_tw: LocationData(base_location_id + 688, RegionName.mimf),
    LocationName.igd_tw: LocationData(base_location_id + 689, RegionName.igdf),
    LocationName.sal_tw: LocationData(base_location_id + 690, RegionName.sal),
    LocationName.ll_tw: LocationData(base_location_id + 691, RegionName.llf),
    LocationName.dob_tw: LocationData(base_location_id + 692, RegionName.dobf),
    LocationName.ttd_tw: LocationData(base_location_id + 693, RegionName.ttdf),
    LocationName.bts_tw: LocationData(base_location_id + 694, RegionName.btsf),
    LocationName.bb_tw: LocationData(base_location_id + 695, RegionName.bbf),
    LocationName.fiend_tw: LocationData(base_location_id + 696, RegionName.fiendf),
    LocationName.st_tw: LocationData(base_location_id + 697, RegionName.stf),
    LocationName.tfitp_tw: LocationData(base_location_id + 698, RegionName.tfitpf),
}

# 700 - 715
bb_gb_loc_table: Dict[str, LocationData] = {
    LocationName.bb_gb1: LocationData(base_location_id + 700, RegionName.knock),
    LocationName.bb_gb2: LocationData(base_location_id + 701, RegionName.knock, 100000),
    LocationName.bb_gb3: LocationData(base_location_id + 702, RegionName.knock, 200000),
    LocationName.bb_gb4: LocationData(base_location_id + 703, RegionName.knock, 300000),
    LocationName.bb_gb5: LocationData(base_location_id + 704, RegionName.knock, 400000),
    LocationName.bb_gb6: LocationData(base_location_id + 705, RegionName.knock, 500000),
    LocationName.bb_gb7: LocationData(base_location_id + 706, RegionName.knock, 600000),
    LocationName.bb_gb8: LocationData(base_location_id + 707, RegionName.knock, 700000),
    LocationName.bb_gb9: LocationData(base_location_id + 708, RegionName.knock, 800000),
    LocationName.bb_gb10: LocationData(base_location_id + 709, RegionName.knock, 900000),
    LocationName.bb_gb11: LocationData(base_location_id + 710, RegionName.knock, 1000000),
    LocationName.bb_gb12: LocationData(base_location_id + 711, RegionName.knock, 1100000),
    LocationName.bb_gb13: LocationData(base_location_id + 712, RegionName.knock, 1200000),
    LocationName.bb_gb14: LocationData(base_location_id + 713, RegionName.knock, 1300000),
    LocationName.bb_gb15: LocationData(base_location_id + 714, RegionName.knock, 1400000),
    LocationName.bb_gb16: LocationData(base_location_id + 715, RegionName.knock, 1500000),
}

# 716 - 755
hub_gb_loc_table: Dict[str, LocationData] = {
    LocationName.tent_gb: LocationData(base_location_id + 716, RegionName.tent),
    LocationName.wild_gb: LocationData(base_location_id + 717, RegionName.wild),
    LocationName.cafe_gb: LocationData(base_location_id + 718, RegionName.cafe),
    LocationName.lond_gb: LocationData(base_location_id + 719, RegionName.lond),
    LocationName.kcs_gb: LocationData(base_location_id + 720, RegionName.kcs),
    LocationName.hogspath_gb: LocationData(base_location_id + 721, RegionName.hogspath),
    LocationName.hogs_gb: LocationData(base_location_id + 722, RegionName.hogs),
    LocationName.hogstat_gb: LocationData(base_location_id + 723, RegionName.hogstat),
    LocationName.hogwpath_gb: LocationData(base_location_id + 724, RegionName.hogwpath),
    LocationName.herb_gb: LocationData(base_location_id + 725, RegionName.herb),
    LocationName.tg_gb: LocationData(base_location_id + 726, RegionName.tg),
    LocationName.quad_gb: LocationData(base_location_id + 727, RegionName.quad),
    LocationName.ror_gb: LocationData(base_location_id + 728, RegionName.ror),
    # LocationName.wcs_gb: LocationData(base_location_id + 729, RegionName.wcs),
    LocationName.wc_gb: LocationData(base_location_id + 730, RegionName.wc),
    LocationName.gh_gb: LocationData(base_location_id + 731, RegionName.gh),
    LocationName.ghl_gb: LocationData(base_location_id + 732, RegionName.ghl),
    LocationName.lake_gb: LocationData(base_location_id + 733, RegionName.lake),
    LocationName.qp_gb: LocationData(base_location_id + 734, RegionName.qp),
    LocationName.thest_gb: LocationData(base_location_id + 735, RegionName.thest),
    LocationName.ground_gb: LocationData(base_location_id + 736, RegionName.ground),
    # LocationName.raven_gb: LocationData(base_location_id + 737, RegionName.raven),
    LocationName.gryf_gb: LocationData(base_location_id + 738, RegionName.gryf),
    LocationName.dormlob_gb: LocationData(base_location_id + 739, RegionName.dormlob),
    # LocationName.ast_gb: LocationData(base_location_id + 740, RegionName.ast),
    LocationName.y6c_gb: LocationData(base_location_id + 741, RegionName.y6c),
    LocationName.y5c_gb: LocationData(base_location_id + 742, RegionName.y5c),
    LocationName.pot_gb: LocationData(base_location_id + 743, RegionName.pot),
    LocationName.div_gb: LocationData(base_location_id + 744, RegionName.div),
    LocationName.dada_gb: LocationData(base_location_id + 745, RegionName.dada),
    LocationName.divc_gb: LocationData(base_location_id + 746, RegionName.divc),
    LocationName.cl_gb: LocationData(base_location_id + 747, RegionName.cl),
    LocationName.stair_gb: LocationData(base_location_id + 748, RegionName.mid_stair),
    LocationName.lib_gb: LocationData(base_location_id + 749, RegionName.lib),
    LocationName.foyer_gb: LocationData(base_location_id + 750, RegionName.foyer),
    LocationName.mm_gb: LocationData(base_location_id + 751, RegionName.mm),
    LocationName.knock_gb: LocationData(base_location_id + 752, RegionName.knock),
    LocationName.leaky_gb: LocationData(base_location_id + 753, RegionName.leaky),
    LocationName.www_gb: LocationData(base_location_id + 754, RegionName.www),
    LocationName.diag_gb: LocationData(base_location_id + 755, RegionName.diag),
}

# Red Brick Locations 900 - 939
red_brick_loc_table: Dict[str, LocationData] = {
    # LocationName.tent_rb: LocationData(base_location_id + 900, RegionName.tent),
    LocationName.wild_rb: LocationData(base_location_id + 901, RegionName.wild),
    # LocationName.cafe_rb: LocationData(base_location_id + 902, RegionName.cafe),
    LocationName.lond_rb: LocationData(base_location_id + 903, RegionName.lond),
    LocationName.kcs_rb: LocationData(base_location_id + 904, RegionName.kcs),
    LocationName.hogspath_rb: LocationData(base_location_id + 905, RegionName.hogspath),
    LocationName.hogs_rb: LocationData(base_location_id + 906, RegionName.hogs),
    LocationName.hogstat_rb: LocationData(base_location_id + 907, RegionName.hogstat),
    LocationName.hogwpath_rb: LocationData(base_location_id + 908, RegionName.hogwpath),
    # LocationName.herb_rb: LocationData(base_location_id + 909, RegionName.herb),
    # LocationName.tg_rb: LocationData(base_location_id + 910, RegionName.tg),
    LocationName.quad_rb: LocationData(base_location_id + 911, RegionName.quad),
    LocationName.ror_rb: LocationData(base_location_id + 912, RegionName.ror),
    # LocationName.wcs_rb: LocationData(base_location_id + 913, RegionName.wcs),
    LocationName.wc_rb: LocationData(base_location_id + 914, RegionName.wc),
    LocationName.gh_rb: LocationData(base_location_id + 915, RegionName.gh),
    LocationName.ghl_rb: LocationData(base_location_id + 916, RegionName.ghl),
    LocationName.lake_rb: LocationData(base_location_id + 917, RegionName.lake),
    # LocationName.qp_rb: LocationData(base_location_id + 918, RegionName.qp),
    LocationName.thest_rb: LocationData(base_location_id + 919, RegionName.thest),
    LocationName.ground_rb: LocationData(base_location_id + 920, RegionName.ground),
    # LocationName.raven_rb: LocationData(base_location_id + 921, RegionName.raven),
    # LocationName.gryf_rb: LocationData(base_location_id + 922, RegionName.gryf),
    # LocationName.dormlob_rb: LocationData(base_location_id + 923, RegionName.house),
    LocationName.ast_rb: LocationData(base_location_id + 924, RegionName.ast),
    # LocationName.y6c_rb: LocationData(base_location_id + 925, RegionName.y6c),
    # LocationName.y5c_rb: LocationData(base_location_id + 926, RegionName.y5c),
    # LocationName.pot_rb: LocationData(base_location_id + 927, RegionName.pot),
    LocationName.div_rb: LocationData(base_location_id + 928, RegionName.div),
    LocationName.dada_rb: LocationData(base_location_id + 929, RegionName.dada),
    LocationName.divc_rb: LocationData(base_location_id + 930, RegionName.divc),
    # LocationName.cl_rb: LocationData(base_location_id + 931, RegionName.cl),
    # LocationName.stair_rb: LocationData(base_location_id + 932, RegionName.low_stair),
    LocationName.lib_rb: LocationData(base_location_id + 933, RegionName.lib),
    # LocationName.foyer_rb: LocationData(base_location_id + 934, RegionName.foyer),
    # LocationName.mm_rb: LocationData(base_location_id + 935, RegionName.mm),
    # LocationName.knock_rb: LocationData(base_location_id + 936, RegionName.knock),
    # LocationName.leaky_rb: LocationData(base_location_id + 937, RegionName.leaky),
    # LocationName.www_rb: LocationData(base_location_id + 938, RegionName.www),
    # LocationName.diag_rb: LocationData(base_location_id + 939, RegionName.diag),
}

# Red Brick Purchases 950 - 973
red_brick_purch_table: Dict[str, LocationData] = {
    LocationName.com_spec_purch: LocationData(base_location_id + 950, RegionName.leaky, 1250),
    LocationName.adv_guide_purch: LocationData(base_location_id + 951, RegionName.leaky, 2500),
    LocationName.disguise_purch: LocationData(base_location_id + 952, RegionName.leaky, 5000),
    LocationName.carrot_wand_purch: LocationData(base_location_id + 953, RegionName.leaky, 10000),
    LocationName.super_strength_purch: LocationData(base_location_id + 954, RegionName.leaky, 75000),
    LocationName.char_token_detect_purch: LocationData(base_location_id + 955, RegionName.leaky, 250000),
    LocationName.fall_rescue_purch: LocationData(base_location_id + 956, RegionName.leaky, 125000),
    LocationName.char_studs_purch: LocationData(base_location_id + 957, RegionName.leaky, 75000),
    LocationName.score_x2_purch: LocationData(base_location_id + 958, RegionName.leaky, 200000),
    LocationName.score_x4_purch: LocationData(base_location_id + 959, RegionName.leaky, 400000),
    LocationName.score_x6_purch: LocationData(base_location_id + 960, RegionName.leaky, 600000),
    LocationName.score_x8_purch: LocationData(base_location_id + 961, RegionName.leaky, 800000),
    LocationName.score_x10_purch: LocationData(base_location_id + 962, RegionName.leaky, 1000000),
    LocationName.stud_mag_purch: LocationData(base_location_id + 963, RegionName.leaky, 250000),
    LocationName.regen_hearts_purch: LocationData(base_location_id + 964, RegionName.leaky, 50000),
    LocationName.extra_hears_purch: LocationData(base_location_id + 965, RegionName.leaky, 75000),
    LocationName.invincibility_purch: LocationData(base_location_id + 966, RegionName.leaky, 500000),
    LocationName.red_brick_detect_purch: LocationData(base_location_id + 967, RegionName.leaky, 250000),
    LocationName.crest_detect_purch: LocationData(base_location_id + 968, RegionName.leaky, 250000),
    LocationName.gb_detect_purch: LocationData(base_location_id + 969, RegionName.leaky, 250000),
    LocationName.christmas_purch: LocationData(base_location_id + 970, RegionName.leaky, 80000),
    LocationName.ghost_studs_purch: LocationData(base_location_id + 971, RegionName.leaky, 99000),
    LocationName.fast_magic_purch: LocationData(base_location_id + 972, RegionName.leaky, 75000),
    LocationName.fast_dig_purch: LocationData(base_location_id + 973, RegionName.leaky, 60000),
}

# 975 - 1005
spell_loc_table: Dict[str, LocationData] = {
    # LocationName.wingard_purch: LocationData(base_location_id + 975, RegionName.www, 0),
    LocationName.slug_purch: LocationData(base_location_id + 976, RegionName.www, 500000),
    LocationName.rictu_purch: LocationData(base_location_id + 977, RegionName.www, 65000),
    LocationName.entomo_purch: LocationData(base_location_id + 978, RegionName.www, 80000),
    LocationName.taranta_purch: LocationData(base_location_id + 979, RegionName.www, 75000),
    LocationName.loco_purch: LocationData(base_location_id + 980, RegionName.www, 30000),
    LocationName.redact_purch: LocationData(base_location_id + 981, RegionName.www, 10000),
    LocationName.colo_purch: LocationData(base_location_id + 982, RegionName.www, 75000),
    LocationName.calvo_purch: LocationData(base_location_id + 983, RegionName.www, 20000),
    LocationName.anteo_purch: LocationData(base_location_id + 984, RegionName.www, 95000),
    LocationName.herbi_purch: LocationData(base_location_id + 985, RegionName.www, 15000),
    LocationName.glaci_purch: LocationData(base_location_id + 986, RegionName.www, 110000),
    LocationName.incarc_purch: LocationData(base_location_id + 987, RegionName.www, 100000),
    LocationName.expel_purch: LocationData(base_location_id + 988, RegionName.www, 10000),
    LocationName.flip_purch: LocationData(base_location_id + 989, RegionName.www, 125000),
    LocationName.trip_purch: LocationData(base_location_id + 990, RegionName.www, 40000),
    LocationName.stup_purch: LocationData(base_location_id + 991, RegionName.www, 150000),
    LocationName.transfig_purch: LocationData(base_location_id + 992, RegionName.www, 200000),
    LocationName.engorg_purch: LocationData(base_location_id + 993, RegionName.www, 10000),
    LocationName.immob_purch: LocationData(base_location_id + 994, RegionName.www, 400000),
    # LocationName.pets_purch: LocationData(base_location_id + 995, RegionName.www),
    # LocationName.invis_purch: LocationData(base_location_id + 996, RegionName.www),
    # # LocationName.avada_purch: LocationData(base_location_id + 997, RegionName.www),
    # LocationName.diffindo_purch: LocationData(base_location_id + 998, RegionName.y5c),
    # # LocationName.lumos_purch: LocationData(base_location_id + 999, RegionName.www),
    # # lumos has 2 bits

    # LocationName.agua_purch: LocationData(base_location_id + 1002, RegionName.y6c),
    # LocationName.focus_purch: LocationData(base_location_id + 1003, RegionName.cl),
    # LocationName.expecto_purch: LocationData(base_location_id + 1004, RegionName.ror),
    # LocationName.reducto_purch: LocationData(base_location_id + 1005, RegionName.y6c),
}

hub_progress_loc_table: Dict[str, LocationData] = {
    LocationName.delum_lesson: LocationData(base_location_id + 1001, RegionName.tsh),
    LocationName.y5_hogwarts: LocationData(base_location_id + 1006, RegionName.hogwpath),
    LocationName.dada_lesson: LocationData(base_location_id + 1007, RegionName.dada),
    LocationName.thestral_lesson: LocationData(base_location_id + 1008, RegionName.thest),
    LocationName.dueling_lesson: LocationData(base_location_id + 1009, RegionName.ror),
    LocationName.diffindo_lesson: LocationData(base_location_id + 1010, RegionName.y5c),
    LocationName.patroneous_lesson: LocationData(base_location_id + 1011, RegionName.ror),
    LocationName.grawp_lesson: LocationData(base_location_id + 1012, RegionName.ground),
    LocationName.focus_lesson: LocationData(base_location_id + 1013, RegionName.cl),
    LocationName.owls_lesson: LocationData(base_location_id + 1014, RegionName.wc),
    LocationName.y5_story_complete: LocationData(base_location_id + 1015, RegionName.wc),
    LocationName.specs_lesson: LocationData(base_location_id + 1016, RegionName.hogstat),
    LocationName.y6_hogwarts: LocationData(base_location_id + 1017, RegionName.hogwpath),
    LocationName.draught_lesson: LocationData(base_location_id + 1018, RegionName.pot),
    LocationName.vial_lesson: LocationData(base_location_id + 1019, RegionName.dumble_office),
    LocationName.agua_lesson: LocationData(base_location_id + 1020, RegionName.y6c),
    LocationName.reducto_lesson: LocationData(base_location_id + 1021, RegionName.y5c),
    LocationName.dumble_lesson: LocationData(base_location_id + 1022, RegionName.dumble_office),
    LocationName.y6_story_complete: LocationData(base_location_id + 1023, RegionName.dumble_office),
    # LocationName.delum_lesson: LocationData(base_location_id + 1024, RegionName.tsh),
    LocationName.bag_lesson: LocationData(base_location_id + 1025, RegionName.tshf),
    LocationName.apparition_lesson: LocationData(base_location_id + 1026, RegionName.tshf),
    LocationName.cafe_lesson: LocationData(base_location_id + 1027, RegionName.cafe),
}

hub_event_loc_table: Dict[str, LocationData] = {
    LocationName.y5_hogwarts_event: LocationData(0, RegionName.hogwpath),
    LocationName.dada_lesson_event: LocationData(0, RegionName.dada),
    LocationName.thestral_lesson_event: LocationData(0, RegionName.thest),
    LocationName.dueling_lesson_event: LocationData(0, RegionName.ror),
    LocationName.diffindo_lesson_event: LocationData(0, RegionName.y5c),
    LocationName.patroneous_lesson_event: LocationData(0, RegionName.ror),
    LocationName.grawp_lesson_event: LocationData(0, RegionName.ground),
    LocationName.focus_lesson_event: LocationData(0, RegionName.cl),
    LocationName.owls_lesson_event: LocationData(0, RegionName.wc),
    LocationName.y5_story_complete_event: LocationData(0, RegionName.wc),
    LocationName.specs_lesson_event: LocationData(0, RegionName.hogstat),
    LocationName.y6_hogwarts_event: LocationData(0, RegionName.hogwpath),
    LocationName.draught_lesson_event: LocationData(0, RegionName.pot),
    LocationName.vial_lesson_event: LocationData(0, RegionName.dumble_office),
    LocationName.agua_lesson_event: LocationData(0, RegionName.y6c),
    LocationName.reducto_lesson_event: LocationData(0, RegionName.y5c),
    LocationName.dumble_lesson_event: LocationData(0, RegionName.dumble_office),
    LocationName.y6_story_complete_event: LocationData(0, RegionName.dumble_office),
    # LocationName.delum_lesson_event: LocationData(0, RegionName.tshf),
    # LocationName.bag_lesson_event: LocationData(0, RegionName.tshf),
    # LocationName.apparition_lesson_event: LocationData(0, RegionName.tshf),
    LocationName.cafe_lesson_event: LocationData(0, RegionName.cafe),
}

all_location_table = {
    **character_location_table,
    **character_token_location_table,
    **spell_loc_table,
    **level_beaten_loc_table,
    **leve_sip_loc_table,
    **hub_sip_loc_table,
    **house_crest_loc_table,
    **true_wizard_loc_table,
    **bb_gb_loc_table,
    **hub_gb_loc_table,
    **red_brick_loc_table,
    **red_brick_purch_table,
    **hub_progress_loc_table,
}


def setup_locations(options: LHP2Options):
    temp_location_table: Dict[str, LocationData] = {}
    temp_location_table.update(character_location_table)
    temp_location_table.update(character_token_location_table)
    if options.ShuffleJokeSpells == 1:
        temp_location_table.update(spell_loc_table)
    temp_location_table.update(level_beaten_loc_table)
    temp_location_table.update(leve_sip_loc_table)
    temp_location_table.update(hub_sip_loc_table)
    temp_location_table.update(house_crest_loc_table)
    temp_location_table.update(true_wizard_loc_table)
    if options.ShuffleGoldBrickPurchases == 1:
        temp_location_table.update(bb_gb_loc_table)
    temp_location_table.update(hub_gb_loc_table)
    temp_location_table.update(red_brick_loc_table)
    temp_location_table.update(red_brick_purch_table)
    temp_location_table.update(hub_progress_loc_table)
    return temp_location_table


location_name_groups = {
    RegionName.dt:    {name for name, data in all_location_table.items() if data.region == RegionName.dt},
    RegionName.da:    {name for name, data in all_location_table.items() if data.region == RegionName.da},
    RegionName.foc:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.foc or data.region == RegionName.focf},
    RegionName.kd:    {name for name, data in all_location_table.items() if data.region == RegionName.kd},
    RegionName.agv:   {name for name, data in all_location_table.items() if data.region == RegionName.agv},
    RegionName.avt:   {name for name, data in all_location_table.items() if data.region == RegionName.avt},
    RegionName.oor:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.oor or data.region == RegionName.oorf},
    RegionName.jd:    {name for name, data in all_location_table.items() if data.region == RegionName.jd},
    RegionName.ansmc: {name for name, data in all_location_table.items()
                       if data.region == RegionName.ansmc or data.region == RegionName.ansmcf},
    RegionName.lh:    {name for name, data in all_location_table.items()
                       if data.region == RegionName.lh or data.region == RegionName.lhf},
    RegionName.ff:    {name for name, data in all_location_table.items()
                       if data.region == RegionName.ff or data.region == RegionName.fff},
    RegionName.thath: {name for name, data in all_location_table.items()
                       if data.region == RegionName.thath or data.region == RegionName.thathf},
    RegionName.tsh:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.tsh or data.region == RegionName.tshf},
    RegionName.mim:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.mim or data.region == RegionName.mimf},
    RegionName.igd:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.igd or data.region == RegionName.igdf},
    RegionName.sal:   {name for name, data in all_location_table.items() if data.region == RegionName.sal},
    RegionName.ll:    {name for name, data in all_location_table.items()
                       if data.region == RegionName.ll or data.region == RegionName.llf},
    RegionName.dob:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.dob or data.region == RegionName.dobf},
    RegionName.ttd:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.ttd or data.region == RegionName.ttdf},
    RegionName.bts:   {name for name, data in all_location_table.items()
                       if data.region == RegionName.bts or data.region == RegionName.btsf},
    RegionName.bb:    {name for name, data in all_location_table.items()
                       if data.region == RegionName.bb or data.region == RegionName.bbf},
    RegionName.fiend: {name for name, data in all_location_table.items()
                       if data.region == RegionName.fiend or data.region == RegionName.fiendf},
    RegionName.st:    {name for name, data in all_location_table.items()
                       if data.region == RegionName.st or data.region == RegionName.stf},
    RegionName.tfitp: {name for name, data in all_location_table.items()
                       if data.region == RegionName.tfitp or data.region == RegionName.tfitpf},
}
