from typing import Dict, NamedTuple

from BaseClasses import Location
from .Options import LHP2Options
from .Data import LocationName, RegionName


class LHP2Location(Location):
    game: str = "Lego Harry Potter 5-7"


class LocationData(NamedTuple):
    id: int = 0
    region: str = ""
    price: int = 0
    token_region: str = ""


regn = RegionName

base_location_id = 400000

character_location_table: Dict[str, LocationData] = {
    LocationName.hagrid_purch: LocationData(base_location_id + 0, regn.mm, 500000),
    LocationName.fang_purch: LocationData(base_location_id + 1, regn.mm, 10000),
    LocationName.hagrid_wed_purch: LocationData(base_location_id + 2, regn.mm, 500000),
    LocationName.prof_flit_purch: LocationData(base_location_id + 3, regn.mm, 200000),
    LocationName.madam_malk_purch: LocationData(base_location_id + 4, regn.mm, 30000),
    LocationName.dobby_purch: LocationData(base_location_id + 5, regn.mm, 750000),
    LocationName.kreacher_purch: LocationData(base_location_id + 6, regn.mm, 100000),
    LocationName.tr_orphanage_purch: LocationData(base_location_id + 7, regn.mm, 2000000),
    LocationName.bogrod_purch: LocationData(base_location_id + 8, regn.mm, 100000),
    LocationName.mund_fletch_purch: LocationData(base_location_id + 9, regn.mm, 80000),
    LocationName.griphook_purch: LocationData(base_location_id + 10, regn.mm, 150000),
    LocationName.prof_mcgon_purch: LocationData(base_location_id + 11, regn.mm, 80000),
    LocationName.madam_pince_purch: LocationData(base_location_id + 12, regn.mm, 20000),
    LocationName.prof_sprout_purch: LocationData(base_location_id + 13, regn.mm, 250000),
    LocationName.madam_pomfrey_purch: LocationData(base_location_id + 14, regn.mm, 10000),
    LocationName.prof_trelawney_purch: LocationData(base_location_id + 15, regn.mm, 200000),
    LocationName.madam_rosmerta_purch: LocationData(base_location_id + 16, regn.mm, 50000),
    LocationName.fat_friar_purch: LocationData(base_location_id + 17, regn.mm, 50000),
    LocationName.grey_lady_purch: LocationData(base_location_id + 18, regn.mm, 50000),
    LocationName.fat_lady_purch: LocationData(base_location_id + 19, regn.mm, 30000),
    LocationName.herm_ball_purch: LocationData(base_location_id + 20, regn.mm, 25000),
    LocationName.bellatrix_purch: LocationData(base_location_id + 21, regn.mm, 3750000),
    LocationName.emmeline_purch: LocationData(base_location_id + 22, regn.mm, 30000),
    LocationName.narcissa_purch: LocationData(base_location_id + 23, regn.mm, 70000),
    LocationName.mcgon_pyjamas_purch: LocationData(base_location_id + 24, regn.mm, 80000),
    LocationName.mary_cattermole_purch: LocationData(base_location_id + 25, regn.mm, 10000),
    LocationName.mcgon_black_purch: LocationData(base_location_id + 26, regn.mm, 80000),
    LocationName.herm_gringotts_purch: LocationData(base_location_id + 27, regn.mm, 85000),
    LocationName.prof_grubbly_purch: LocationData(base_location_id + 28, regn.mm, 20000),
    LocationName.bellatrix_azka_purch: LocationData(base_location_id + 29, regn.mm, 3750000),
    LocationName.death_eater_purch: LocationData(base_location_id + 30, regn.mm, 250000),
    LocationName.dudley_grey_purch: LocationData(base_location_id + 31, regn.mm, 120000),
    LocationName.prof_dumble_purch: LocationData(base_location_id + 32, regn.mm, 1000000),
    # LocationName.harry_purch: LocationData(base_location_id + 33, regn.mm),
    # LocationName.herm_purch: LocationData(base_location_id + 34, regn.mm),
    LocationName.argus_purch: LocationData(base_location_id + 35, regn.mm, 20000),
    LocationName.madam_hooch_purch: LocationData(base_location_id + 36, regn.mm, 30000),
    LocationName.crabbe_purch: LocationData(base_location_id + 37, regn.mm, 60000),
    LocationName.goyle_purch: LocationData(base_location_id + 38, regn.mm, 30000),
    LocationName.ginny_purch: LocationData(base_location_id + 39, regn.mm, 100000),
    LocationName.arthur_purch: LocationData(base_location_id + 40, regn.mm, 20000),
    LocationName.katie_purch: LocationData(base_location_id + 41, regn.mm, 70000),
    LocationName.lily_purch: LocationData(base_location_id + 42, regn.mm, 200000),
    LocationName.bloody_baron_purch: LocationData(base_location_id + 43, regn.mm, 50000),
    LocationName.fudge_purch: LocationData(base_location_id + 44, regn.mm, 200000),
    LocationName.justin_purch: LocationData(base_location_id + 45, regn.mm, 20000),
    LocationName.cho_purch: LocationData(base_location_id + 46, regn.mm, 75000),
    LocationName.dean_purch: LocationData(base_location_id + 47, regn.mm, 50000),
    LocationName.draco_purch: LocationData(base_location_id + 48, regn.mm, 1000000),
    LocationName.lucius_purch: LocationData(base_location_id + 49, regn.mm, 250000),
    LocationName.draco_suit_purch: LocationData(base_location_id + 50, regn.mm, 1000000),
    # LocationName.custom_a_purch: LocationData(base_location_id + 51, regn.mm),
    # LocationName.custom_b_purch: LocationData(base_location_id + 52, regn.mm),
    # LocationName.custom_c_purch: LocationData(base_location_id + 53, regn.mm),
    # LocationName.custom_d_purch: LocationData(base_location_id + 54, regn.mm),
    # LocationName.custom_e_purch: LocationData(base_location_id + 55, regn.mm),
    # LocationName.custom_g_purch: LocationData(base_location_id + 56, regn.mm),
    # LocationName.custom_h_purch: LocationData(base_location_id + 57, regn.mm),
    # LocationName.custom_i_purch: LocationData(base_location_id + 58, regn.mm),
    # LocationName.custom_j_purch: LocationData(base_location_id + 59, regn.mm),
    LocationName.harry_pyjamas_purch: LocationData(base_location_id + 60, regn.mm, 135000),
    LocationName.myrtle_purch: LocationData(base_location_id + 61, regn.mm, 200000),
    LocationName.james_ghost_purch: LocationData(base_location_id + 62, regn.mm, 200000),
    LocationName.madeye_purch: LocationData(base_location_id + 63, regn.mm, 10000),
    LocationName.hannah_purch: LocationData(base_location_id + 64, regn.mm, 10000),
    # LocationName.custom_f_purch: LocationData(base_location_id + 65, regn.mm),
    LocationName.kingsley_purch: LocationData(base_location_id + 66, regn.mm, 20000),
    LocationName.aberforth_purch: LocationData(base_location_id + 67, regn.mm, 20000),
    LocationName.runcorn_purch: LocationData(base_location_id + 68, regn.mm, 20000),
    LocationName.alecto_purch: LocationData(base_location_id + 69, regn.mm, 20000),
    LocationName.amycus_purch: LocationData(base_location_id + 70, regn.mm, 20000),
    LocationName.anthony_purch: LocationData(base_location_id + 71, regn.mm, 20000),
    LocationName.bathilda_snake_purch: LocationData(base_location_id + 72, regn.mm, 200000),
    LocationName.blaise_purch: LocationData(base_location_id + 73, regn.mm, 80000),
    LocationName.charity_purch: LocationData(base_location_id + 74, regn.mm, 20000),
    LocationName.charlie_purch: LocationData(base_location_id + 75, regn.mm, 30000),
    LocationName.cormac_purch: LocationData(base_location_id + 76, regn.mm, 55000),
    LocationName.dedalus_purch: LocationData(base_location_id + 77, regn.mm, 20000),
    LocationName.dirk_purch: LocationData(base_location_id + 78, regn.mm, 10000),
    LocationName.dolohov_purch: LocationData(base_location_id + 79, regn.mm, 200000),
    LocationName.dragomir_purch: LocationData(base_location_id + 80, regn.mm, 40000),
    LocationName.elphias_purch: LocationData(base_location_id + 81, regn.mm, 10000),
    LocationName.fenrir_purch: LocationData(base_location_id + 82, regn.mm, 1000000),
    LocationName.grindel_young_purch: LocationData(base_location_id + 83, regn.mm, 200000),
    LocationName.grindel_old_purch: LocationData(base_location_id + 84, regn.mm, 200000),
    LocationName.gregorovitch_purch: LocationData(base_location_id + 85, regn.mm, 750000),
    LocationName.hestia_purch: LocationData(base_location_id + 86, regn.mm, 20000),
    LocationName.prof_slughorn_purch: LocationData(base_location_id + 87, regn.mm, 10000),
    LocationName.james_young_purch: LocationData(base_location_id + 88, regn.mm, 200000),
    LocationName.lavender_purch: LocationData(base_location_id + 89, regn.mm, 10000),
    LocationName.mafalda_purch: LocationData(base_location_id + 90, regn.mm, 60000),
    LocationName.belby_purch: LocationData(base_location_id + 91, regn.mm, 90000),
    LocationName.luna_purple_coat_purch: LocationData(base_location_id + 92, regn.mm, 50000),
    LocationName.herm_grey_coat_purch: LocationData(base_location_id + 93, regn.mm, 62500),
    LocationName.harry_godric_purch: LocationData(base_location_id + 94, regn.mm, 25000),
    LocationName.prof_umbridge_purch: LocationData(base_location_id + 95, regn.mm, 125000),
    LocationName.fred_purch: LocationData(base_location_id + 96, regn.mm, 60000),
    LocationName.george_purch: LocationData(base_location_id + 97, regn.mm, 60000),
    LocationName.molly_apron_purch: LocationData(base_location_id + 98, regn.mm, 750000),
    LocationName.crabbe_jumper_purch: LocationData(base_location_id + 99, regn.mm, 60000),
    LocationName.draco_sweater_purch: LocationData(base_location_id + 100, regn.mm, 1000000),
    LocationName.goyle_jumper_purch: LocationData(base_location_id + 101, regn.mm, 30000),
    LocationName.milk_man_purch: LocationData(base_location_id + 102, regn.mm, 80000),
    LocationName.twin_2_purch: LocationData(base_location_id + 103, regn.mm, 20000),
    LocationName.herm_mafalda_purch: LocationData(base_location_id + 104, regn.mm, 125000),
    LocationName.ministry_guard_purch: LocationData(base_location_id + 105, regn.mm, 70000),
    LocationName.harry_winter_purch: LocationData(base_location_id + 106, regn.mm, 85000),
    LocationName.arthur_torn_suit_purch: LocationData(base_location_id + 107, regn.mm, 20000),
    LocationName.fred_winter_purch: LocationData(base_location_id + 108, regn.mm, 60000),
    LocationName.cho_winter_purch: LocationData(base_location_id + 109, regn.mm, 75000),
    LocationName.george_winter_purch: LocationData(base_location_id + 110, regn.mm, 60000),
    LocationName.herm_scarf_purch: LocationData(base_location_id + 111, regn.mm, 125000),
    LocationName.luna_blue_jumper_purch: LocationData(base_location_id + 112, regn.mm, 50000),
    LocationName.fred_owls_purch: LocationData(base_location_id + 113, regn.mm, 60000),
    LocationName.fred_pyjamas_purch: LocationData(base_location_id + 114, regn.mm, 60000),
    LocationName.george_owls_purch: LocationData(base_location_id + 115, regn.mm, 60000),
    LocationName.george_pyjamas_purch: LocationData(base_location_id + 116, regn.mm, 60000),
    LocationName.herm_jumper_purch: LocationData(base_location_id + 117, regn.mm, 125000),
    LocationName.fudge_wizengamot_purch: LocationData(base_location_id + 118, regn.mm, 200000),
    LocationName.dudley_purch: LocationData(base_location_id + 119, regn.mm, 80000),
    LocationName.gang_mem_purch: LocationData(base_location_id + 120, regn.mm, 10000),
    LocationName.harry_albert_runcorn_purch: LocationData(base_location_id + 121, regn.mm, 30000),
    LocationName.harry_brown_jacket_purch: LocationData(base_location_id + 122, regn.mm, 32500),
    LocationName.dumble_cursed_purch: LocationData(base_location_id + 123, regn.mm, 1000000),
    LocationName.lucius_death_eater_purch: LocationData(base_location_id + 124, regn.mm, 250000),
    LocationName.luna_purch: LocationData(base_location_id + 125, regn.mm, 50000),
    LocationName.umbridge_wizengamot_purch: LocationData(base_location_id + 126, regn.mm, 125000),
    LocationName.dolohov_workman_purch: LocationData(base_location_id + 127, regn.mm, 200000),
    LocationName.michael_purch: LocationData(base_location_id + 128, regn.mm, 50000),
    LocationName.dean_winter_purch: LocationData(base_location_id + 129, regn.mm, 50000),
    LocationName.arthur_cardigan_purch: LocationData(base_location_id + 130, regn.mm, 20000),
    LocationName.luna_pink_dress_purch: LocationData(base_location_id + 131, regn.mm, 150000),
    LocationName.marietta_purch: LocationData(base_location_id + 132, regn.mm, 10000),
    LocationName.dumble_young_purch: LocationData(base_location_id + 133, regn.mm, 1000000),
    LocationName.slughorn_young_purch: LocationData(base_location_id + 134, regn.mm, 10000),
    LocationName.slughorn_pyjamas_purch: LocationData(base_location_id + 135, regn.mm, 10000),
    LocationName.lily_young_casual_purch: LocationData(base_location_id + 136, regn.mm, 200000),
    LocationName.ginny_dress_purch: LocationData(base_location_id + 137, regn.mm, 100000),
    LocationName.ginny_pyjamas_purch: LocationData(base_location_id + 138, regn.mm, 100000),
    LocationName.blaise_black_shirt_purch: LocationData(base_location_id + 139, regn.mm, 80000),
    LocationName.cormac_suit_purch: LocationData(base_location_id + 140, regn.mm, 55000),
    LocationName.muggle_orphan_purch: LocationData(base_location_id + 141, regn.mm, 250000),
    LocationName.luna_overalls_purch: LocationData(base_location_id + 142, regn.mm, 50000),
    LocationName.molly_purch: LocationData(base_location_id + 143, regn.mm, 750000),
    LocationName.herm_cardigan_purch: LocationData(base_location_id + 144, regn.mm, 125000),
    LocationName.luna_yellow_dress_purch: LocationData(base_location_id + 145, regn.mm, 150000),
    LocationName.dudley_shirt_purch: LocationData(base_location_id + 146, regn.mm, 120000),
    LocationName.bill_wedding_purch: LocationData(base_location_id + 147, regn.mm, 10000),
    LocationName.fleur_purch: LocationData(base_location_id + 148, regn.mm, 10000),
    LocationName.herm_red_dress_purch: LocationData(base_location_id + 149, regn.mm, 57500),
    LocationName.figg_purch: LocationData(base_location_id + 150, regn.mm, 60000),
    LocationName.harry_locket_purch: LocationData(base_location_id + 151, regn.mm, 105000),
    LocationName.twin_1_purch: LocationData(base_location_id + 152, regn.mm, 30000),
    LocationName.cole_purch: LocationData(base_location_id + 153, regn.mm, 40000),
    LocationName.herm_ministry_purch: LocationData(base_location_id + 154, regn.mm, 57500),
    LocationName.arthur_suit_purch: LocationData(base_location_id + 155, regn.mm, 20000),
    LocationName.harry_christmas_purch: LocationData(base_location_id + 156, regn.mm, 110000),
    LocationName.ernie_purch: LocationData(base_location_id + 157, regn.mm, 100000),
    LocationName.prof_snape_purch: LocationData(base_location_id + 158, regn.mm, 250000),
    LocationName.neville_purch: LocationData(base_location_id + 159, regn.mm, 50000),
    # LocationName.ron_purch: LocationData(base_location_id + 160, regn.mm),
    LocationName.ron_quidditch_purch: LocationData(base_location_id + 161, regn.mm, 82500),
    LocationName.vernon_purch: LocationData(base_location_id + 162, regn.mm, 50000),
    LocationName.tom_riddle_purch: LocationData(base_location_id + 163, regn.mm, 2000000),
    LocationName.sirius_black_purch: LocationData(base_location_id + 164, regn.mm, 10000),
    LocationName.remus_lupin_purch: LocationData(base_location_id + 165, regn.mm, 10000),
    LocationName.wormtail_purch: LocationData(base_location_id + 166, regn.mm, 1000000),
    LocationName.rita_skeeter_purch: LocationData(base_location_id + 167, regn.mm, 30000),
    LocationName.padma_patil_purch: LocationData(base_location_id + 168, regn.mm, 10000),
    LocationName.station_guard_purch: LocationData(base_location_id + 169, regn.mm, 10000),
    LocationName.prof_binns_purch: LocationData(base_location_id + 170, regn.mm, 50000),
    LocationName.penelope_purch: LocationData(base_location_id + 171, regn.mm, 60000),
    LocationName.susan_purch: LocationData(base_location_id + 172, regn.mm, 50000),
    LocationName.tonks_purch: LocationData(base_location_id + 173, regn.mm, 1250000),
    LocationName.pius_purch: LocationData(base_location_id + 174, regn.mm, 30000),
    LocationName.reg_purch: LocationData(base_location_id + 175, regn.mm, 60000),
    LocationName.regulus_purch: LocationData(base_location_id + 176, regn.mm, 1000000),
    LocationName.scrimgeour_purch: LocationData(base_location_id + 177, regn.mm, 900000),
    LocationName.scabior_purch: LocationData(base_location_id + 178, regn.mm, 650000),
    LocationName.xeno_purch: LocationData(base_location_id + 179, regn.mm, 30000),
    LocationName.yaxley_purch: LocationData(base_location_id + 180, regn.mm, 260000),
    LocationName.zacharias_purch: LocationData(base_location_id + 181, regn.mm, 20000),
    LocationName.waitress_treats_purch: LocationData(base_location_id + 182, regn.mm, 10000),
    LocationName.lord_voldemort_purch: LocationData(base_location_id + 183, regn.mm, 25000000),
    LocationName.ron_blue_pyjamas_purch: LocationData(base_location_id + 184, regn.mm, 25000),
    LocationName.neville_cardigan_purch: LocationData(base_location_id + 185, regn.mm, 50000),
    LocationName.neville_pyjamas_purch: LocationData(base_location_id + 186, regn.mm, 50000),
    LocationName.percy_purch: LocationData(base_location_id + 187, regn.mm, 50000),
    LocationName.sirius_azkaban_purch: LocationData(base_location_id + 188, regn.mm, 250000),
    LocationName.black_purch: LocationData(base_location_id + 189, regn.mm, 250000),
    LocationName.xeno_luna_purch: LocationData(base_location_id + 190, regn.mm, 30000),
    LocationName.ron_reg_cattermole_purch: LocationData(base_location_id + 191, regn.mm, 75000),
    LocationName.tonks_pink_coat_purch: LocationData(base_location_id + 192, regn.mm, 125000),
    LocationName.ron_winter_clothes_purch: LocationData(base_location_id + 193, regn.mm, 45000),
    LocationName.snape_underwear_purch: LocationData(base_location_id + 194, regn.mm, 250000),
    LocationName.rowle_purch: LocationData(base_location_id + 195, regn.mm, 60000),
    LocationName.petunia_purch: LocationData(base_location_id + 196, regn.mm, 60000),
    LocationName.neville_tank_top_purch: LocationData(base_location_id + 197, regn.mm, 50000),
    LocationName.neville_winter_purch: LocationData(base_location_id + 198, regn.mm, 50000),
    LocationName.parvati_purch: LocationData(base_location_id + 199, regn.mm, 10000),
    LocationName.ron_red_sweater_purch: LocationData(base_location_id + 200, regn.mm, 62500),
    LocationName.ollivander_purch: LocationData(base_location_id + 201, regn.mm, 60000),
    LocationName.seamus_winter_purch: LocationData(base_location_id + 202, regn.mm, 10000),
    LocationName.ron_underwear_purch: LocationData(base_location_id + 203, regn.mm, 60000),
    LocationName.ron_wedding_purch: LocationData(base_location_id + 204, regn.mm, 95000),
    LocationName.waitress_luchino_purch: LocationData(base_location_id + 205, regn.mm, 30000),
    LocationName.petunia_green_coat_purch: LocationData(base_location_id + 206, regn.mm, 60000),
    LocationName.seamus_purch: LocationData(base_location_id + 207, regn.mm, 10000),
    LocationName.snatcher_purch: LocationData(base_location_id + 208, regn.mm, 30000),
    LocationName.ron_green_shirt_purch: LocationData(base_location_id + 209, regn.mm, 60000),
    LocationName.neville_waiter_purch: LocationData(base_location_id + 210, regn.mm, 250000),
    LocationName.xeno_wedding_purch: LocationData(base_location_id + 211, regn.mm, 30000),
    LocationName.skeleton_purch: LocationData(base_location_id + 212, regn.mm, 5000000),
}

# 213 - 425
character_token_location_table: Dict[str, LocationData] = {
    LocationName.hagrid_token: LocationData(base_location_id + 213, regn.fff),
    LocationName.fang_token: LocationData(base_location_id + 214, regn.fff),
    LocationName.hagrid_wed_token: LocationData(base_location_id + 215, regn.thathf),
    LocationName.prof_flit_token: LocationData(base_location_id + 216, regn.y5c),
    LocationName.madam_malk_token: LocationData(base_location_id + 217, regn.mm),
    LocationName.dobby_token: LocationData(base_location_id + 218, regn.dobf),
    LocationName.kreacher_token: LocationData(base_location_id + 219, regn.kd),
    LocationName.tr_orphanage_token: LocationData(base_location_id + 220, regn.thathf),
    LocationName.bogrod_token: LocationData(base_location_id + 221, regn.ttdf),
    LocationName.mund_fletch_token: LocationData(base_location_id + 222, regn.diag),
    LocationName.griphook_token: LocationData(base_location_id + 223, regn.ttd),
    LocationName.prof_mcgon_token: LocationData(base_location_id + 224, regn.ast),
    LocationName.madam_pince_token: LocationData(base_location_id + 225, regn.lib),
    LocationName.prof_sprout_token: LocationData(base_location_id + 226, regn.ff),
    LocationName.madam_pomfrey_token: LocationData(base_location_id + 227, regn.huff),
    LocationName.prof_trelawney_token: LocationData(base_location_id + 228, regn.div),
    LocationName.madam_rosmerta_token: LocationData(base_location_id + 229, regn.jd),
    LocationName.fat_friar_token: LocationData(base_location_id + 230, regn.gh),
    LocationName.grey_lady_token: LocationData(base_location_id + 231, regn.bbf),
    LocationName.fat_lady_token: LocationData(base_location_id + 232, regn.dormlob),
    LocationName.herm_ball_token: LocationData(base_location_id + 233, regn.gryf),
    LocationName.bellatrix_token: LocationData(base_location_id + 234, regn.tfitpf),
    LocationName.emmeline_token: LocationData(base_location_id + 235, regn.agv),
    LocationName.narcissa_token: LocationData(base_location_id + 236, regn.knock),
    LocationName.mcgon_pyjamas_token: LocationData(base_location_id + 237, regn.gryf),
    LocationName.mary_cattermole_token: LocationData(base_location_id + 238, regn.lond),
    LocationName.mcgon_black_token: LocationData(base_location_id + 239, regn.quad),
    LocationName.herm_gringotts_token: LocationData(base_location_id + 240, regn.ttdf),
    LocationName.prof_grubbly_token: LocationData(base_location_id + 241, regn.ground),
    LocationName.bellatrix_azka_token: LocationData(base_location_id + 242, regn.ground),
    LocationName.death_eater_token: LocationData(base_location_id + 243, regn.stf),
    LocationName.dudley_grey_token: LocationData(base_location_id + 244, regn.dt),
    LocationName.prof_dumble_token: LocationData(base_location_id + 245, regn.thath),
    # LocationName.harry_token: LocationData(base_location_id + 246, regn.mm),
    # LocationName.herm_token: LocationData(base_location_id + 247, regn.mm),
    LocationName.argus_token: LocationData(base_location_id + 248, regn.wcs),
    LocationName.madam_hooch_token: LocationData(base_location_id + 249, regn.qp),
    LocationName.crabbe_token: LocationData(base_location_id + 250, regn.ror),
    LocationName.goyle_token: LocationData(base_location_id + 251, regn.fiendf),
    LocationName.ginny_token: LocationData(base_location_id + 252, regn.lh),
    LocationName.arthur_token: LocationData(base_location_id + 253, regn.kd),
    LocationName.katie_token: LocationData(base_location_id + 254, regn.thest),
    LocationName.lily_token: LocationData(base_location_id + 255, regn.igd),
    LocationName.bloody_baron_token: LocationData(base_location_id + 256, regn.gh),
    LocationName.fudge_token: LocationData(base_location_id + 257, regn.tg),
    LocationName.justin_token: LocationData(base_location_id + 258, regn.y5c),
    LocationName.cho_token: LocationData(base_location_id + 259, regn.y6c),
    LocationName.dean_token: LocationData(base_location_id + 260, regn.ghl),
    LocationName.draco_token: LocationData(base_location_id + 261, regn.dada),
    LocationName.lucius_token: LocationData(base_location_id + 262, regn.wild),
    LocationName.draco_suit_token: LocationData(base_location_id + 263, regn.lhf),
    # LocationName.custom_a_token: LocationData(base_location_id + 264, regn.mm),
    # LocationName.custom_b_token: LocationData(base_location_id + 265, regn.mm),
    # LocationName.custom_c_token: LocationData(base_location_id + 266, regn.mm),
    # LocationName.custom_d_token: LocationData(base_location_id + 267, regn.mm),
    # LocationName.custom_e_token: LocationData(base_location_id + 268, regn.mm),
    # LocationName.custom_g_token: LocationData(base_location_id + 269, regn.mm),
    # LocationName.custom_h_token: LocationData(base_location_id + 270, regn.mm),
    # LocationName.custom_i_token: LocationData(base_location_id + 271, regn.mm),
    # LocationName.custom_j_token: LocationData(base_location_id + 272, regn.mm),
    LocationName.harry_pyjamas_token: LocationData(base_location_id + 273, regn.gryf),
    LocationName.myrtle_token: LocationData(base_location_id + 274, regn.raven),
    LocationName.james_ghost_token: LocationData(base_location_id + 275, regn.wild),
    LocationName.madeye_token: LocationData(base_location_id + 276, regn.tsh),
    LocationName.hannah_token: LocationData(base_location_id + 277, regn.y5c),
    # LocationName.custom_f_token: LocationData(base_location_id + 278, regn.mm),
    LocationName.kingsley_token: LocationData(base_location_id + 279, regn.tfitpf),
    LocationName.aberforth_token: LocationData(base_location_id + 280, regn.bts),
    LocationName.runcorn_token: LocationData(base_location_id + 281, regn.wild),
    LocationName.alecto_token: LocationData(base_location_id + 282, regn.bts),
    LocationName.amycus_token: LocationData(base_location_id + 283, regn.btsf),
    LocationName.anthony_token: LocationData(base_location_id + 284, regn.lib),
    LocationName.bathilda_snake_token: LocationData(base_location_id + 285, regn.igdf),
    LocationName.blaise_token: LocationData(base_location_id + 286, regn.slyth),
    LocationName.charity_token: LocationData(base_location_id + 287, regn.pot),
    LocationName.charlie_token: LocationData(base_location_id + 288, regn.wc),
    LocationName.cormac_token: LocationData(base_location_id + 289, regn.ror),
    LocationName.dedalus_token: LocationData(base_location_id + 290, regn.upper_stair),
    LocationName.dirk_token: LocationData(base_location_id + 291, regn.ror),
    LocationName.dolohov_token: LocationData(base_location_id + 292, regn.ast),
    LocationName.dragomir_token: LocationData(base_location_id + 293, regn.wild),
    LocationName.elphias_token: LocationData(base_location_id + 294, regn.dt),
    LocationName.fenrir_token: LocationData(base_location_id + 295, regn.st),
    LocationName.grindel_young_token: LocationData(base_location_id + 296, regn.ast),
    LocationName.grindel_old_token: LocationData(base_location_id + 297, regn.ast),
    LocationName.gregorovitch_token: LocationData(base_location_id + 298, regn.diag),
    LocationName.hestia_token: LocationData(base_location_id + 299, regn.leaky),
    LocationName.prof_slughorn_token: LocationData(base_location_id + 300, regn.lh),
    LocationName.james_young_token: LocationData(base_location_id + 301, regn.hogwpath),
    LocationName.lavender_token: LocationData(base_location_id + 302, regn.y6c),
    LocationName.mafalda_token: LocationData(base_location_id + 303, regn.lond),
    LocationName.belby_token: LocationData(base_location_id + 304, regn.raven),
    LocationName.luna_purple_coat_token: LocationData(base_location_id + 305, regn.llf),
    LocationName.herm_grey_coat_token: LocationData(base_location_id + 306, regn.sal),
    LocationName.harry_godric_token: LocationData(base_location_id + 307, regn.igdf),
    LocationName.prof_umbridge_token: LocationData(base_location_id + 308, regn.agv),
    LocationName.fred_token: LocationData(base_location_id + 309, regn.www),
    LocationName.george_token: LocationData(base_location_id + 310, regn.www),
    LocationName.molly_apron_token: LocationData(base_location_id + 311, regn.focf),
    LocationName.crabbe_jumper_token: LocationData(base_location_id + 312, regn.lake),
    LocationName.draco_sweater_token: LocationData(base_location_id + 313, regn.slyth),
    LocationName.goyle_jumper_token: LocationData(base_location_id + 314, regn.slyth),
    LocationName.milk_man_token: LocationData(base_location_id + 315, regn.oorf),
    LocationName.twin_2_token: LocationData(base_location_id + 316, regn.knock),
    LocationName.herm_mafalda_token: LocationData(base_location_id + 317, regn.mimf),
    LocationName.ministry_guard_token: LocationData(base_location_id + 318, regn.lond),
    LocationName.harry_winter_token: LocationData(base_location_id + 319, regn.hogs),
    LocationName.arthur_torn_suit_token: LocationData(base_location_id + 320, regn.wcs),
    LocationName.fred_winter_token: LocationData(base_location_id + 321, regn.hogspath),
    LocationName.cho_winter_token: LocationData(base_location_id + 322, regn.da),
    LocationName.george_winter_token: LocationData(base_location_id + 323, regn.hogspath),
    LocationName.herm_scarf_token: LocationData(base_location_id + 324, regn.da),
    LocationName.luna_blue_jumper_token: LocationData(base_location_id + 325, regn.thest),
    LocationName.fred_owls_token: LocationData(base_location_id + 326, regn.wc),
    LocationName.fred_pyjamas_token: LocationData(base_location_id + 327, regn.www),
    LocationName.george_owls_token: LocationData(base_location_id + 328, regn.wc),
    LocationName.george_pyjamas_token: LocationData(base_location_id + 329, regn.www),
    LocationName.herm_jumper_token: LocationData(base_location_id + 330, regn.avt),
    LocationName.fudge_wizengamot_token: LocationData(base_location_id + 331, regn.avt),
    LocationName.dudley_token: LocationData(base_location_id + 332, regn.cafe),
    LocationName.gang_mem_token: LocationData(base_location_id + 333, regn.foc),
    LocationName.harry_albert_runcorn_token: LocationData(base_location_id + 334, regn.mim),
    LocationName.harry_brown_jacket_token: LocationData(base_location_id + 335, regn.fiendf),
    LocationName.dumble_cursed_token: LocationData(base_location_id + 336, regn.oorf),
    LocationName.lucius_death_eater_token: LocationData(base_location_id + 337, regn.avt),
    LocationName.luna_token: LocationData(base_location_id + 338, regn.hogwpath),
    LocationName.umbridge_wizengamot_token: LocationData(base_location_id + 339, regn.dada),
    LocationName.dolohov_workman_token: LocationData(base_location_id + 340, regn.cafe),
    LocationName.michael_token: LocationData(base_location_id + 341, regn.hogspath),
    LocationName.dean_winter_token: LocationData(base_location_id + 342, regn.hogs),
    LocationName.arthur_cardigan_token: LocationData(base_location_id + 343, regn.herb),
    LocationName.luna_pink_dress_token: LocationData(base_location_id + 344, regn.raven),
    LocationName.marietta_token: LocationData(base_location_id + 345, regn.hogs),
    LocationName.dumble_young_token: LocationData(base_location_id + 346, regn.dumble_office),
    LocationName.slughorn_young_token: LocationData(base_location_id + 347, regn.herb),
    LocationName.slughorn_pyjamas_token: LocationData(base_location_id + 348, regn.oorf),
    LocationName.lily_young_casual_token: LocationData(base_location_id + 349, regn.hogwpath),
    LocationName.ginny_dress_token: LocationData(base_location_id + 350, regn.divc),
    LocationName.ginny_pyjamas_token: LocationData(base_location_id + 351, regn.gryf),
    LocationName.blaise_black_shirt_token: LocationData(base_location_id + 352, regn.ror),
    LocationName.cormac_suit_token: LocationData(base_location_id + 353, regn.jd),
    LocationName.muggle_orphan_token: LocationData(base_location_id + 354, regn.kcs),
    LocationName.luna_overalls_token: LocationData(base_location_id + 355, regn.hogstat),
    LocationName.molly_token: LocationData(base_location_id + 356, regn.ansmcf),
    LocationName.herm_cardigan_token: LocationData(base_location_id + 357, regn.cl),
    LocationName.luna_yellow_dress_token: LocationData(base_location_id + 358, regn.ror),
    LocationName.dudley_shirt_token: LocationData(base_location_id + 359, regn.kcs),
    LocationName.bill_wedding_token: LocationData(base_location_id + 360, regn.ansmc),
    LocationName.fleur_token: LocationData(base_location_id + 361, regn.wild),
    LocationName.herm_red_dress_token: LocationData(base_location_id + 362, regn.tshf),
    LocationName.figg_token: LocationData(base_location_id + 363, regn.leaky),
    LocationName.harry_locket_token: LocationData(base_location_id + 364, regn.sal),
    LocationName.twin_1_token: LocationData(base_location_id + 365, regn.knock),
    LocationName.cole_token: LocationData(base_location_id + 366, regn.cafe),
    LocationName.herm_ministry_token: LocationData(base_location_id + 367, regn.wild),
    LocationName.arthur_suit_token: LocationData(base_location_id + 368, regn.dt),
    LocationName.harry_christmas_token: LocationData(base_location_id + 369, regn.jd),
    LocationName.ernie_token: LocationData(base_location_id + 370, regn.dumble_office),
    LocationName.prof_snape_token: LocationData(base_location_id + 371, regn.stf),
    LocationName.neville_token: LocationData(base_location_id + 372, regn.agv),
    # LocationName.ron_token: LocationData(base_location_id + 373, regn.mm),
    LocationName.ron_quidditch_token: LocationData(base_location_id + 374, regn.qp),
    LocationName.vernon_token: LocationData(base_location_id + 375, regn.cafe),
    LocationName.tom_riddle_token: LocationData(base_location_id + 376, regn.fiendf),
    LocationName.sirius_black_token: LocationData(base_location_id + 377, regn.kd),
    LocationName.remus_lupin_token: LocationData(base_location_id + 378, regn.wild),
    LocationName.wormtail_token: LocationData(base_location_id + 379, regn.dob),
    LocationName.rita_skeeter_token: LocationData(base_location_id + 380, regn.foyer),
    LocationName.padma_patil_token: LocationData(base_location_id + 381, regn.thest),
    LocationName.station_guard_token: LocationData(base_location_id + 382, regn.hogstat),
    LocationName.prof_binns_token: LocationData(base_location_id + 383, regn.lake),
    LocationName.penelope_token: LocationData(base_location_id + 384, regn.gh),
    LocationName.susan_token: LocationData(base_location_id + 385, regn.foyer),
    LocationName.tonks_token: LocationData(base_location_id + 386, regn.qp),
    LocationName.pius_token: LocationData(base_location_id + 387, regn.knock),
    LocationName.reg_token: LocationData(base_location_id + 388, regn.wild),
    LocationName.regulus_token: LocationData(base_location_id + 389, regn.dumble_office),
    LocationName.scrimgeour_token: LocationData(base_location_id + 390, regn.lond),
    LocationName.scabior_token: LocationData(base_location_id + 391, regn.wild),
    LocationName.xeno_token: LocationData(base_location_id + 392, regn.wild),
    LocationName.yaxley_token: LocationData(base_location_id + 393, regn.wild),
    LocationName.zacharias_token: LocationData(base_location_id + 394, regn.mid_stair),
    LocationName.waitress_treats_token: LocationData(base_location_id + 395, regn.kcs),
    LocationName.lord_voldemort_token: LocationData(base_location_id + 396, regn.tfitpf),
    LocationName.ron_blue_pyjamas_token: LocationData(base_location_id + 397, regn.dormlob),
    LocationName.neville_cardigan_token: LocationData(base_location_id + 398, regn.bbf),
    LocationName.neville_pyjamas_token: LocationData(base_location_id + 399, regn.div),
    LocationName.percy_token: LocationData(base_location_id + 400, regn.wild),
    LocationName.sirius_azkaban_token: LocationData(base_location_id + 401, regn.knock),
    LocationName.black_token: LocationData(base_location_id + 402, regn.knock),
    LocationName.xeno_luna_token: LocationData(base_location_id + 403, regn.ll),
    LocationName.ron_reg_cattermole_token: LocationData(base_location_id + 404, regn.mim),
    LocationName.tonks_pink_coat_token: LocationData(base_location_id + 405, regn.ansmcf),
    LocationName.ron_winter_clothes_token: LocationData(base_location_id + 406, regn.wild),
    LocationName.snape_underwear_token: LocationData(base_location_id + 407, regn.focf),
    LocationName.rowle_token: LocationData(base_location_id + 408, regn.cafe),
    LocationName.petunia_token: LocationData(base_location_id + 409, regn.cafe),
    LocationName.neville_tank_top_token: LocationData(base_location_id + 410, regn.huff),
    LocationName.neville_winter_token: LocationData(base_location_id + 411, regn.da),
    LocationName.parvati_token: LocationData(base_location_id + 412, regn.hogs),
    LocationName.ron_red_sweater_token: LocationData(base_location_id + 413, regn.cl),
    LocationName.ollivander_token: LocationData(base_location_id + 414, regn.dob),
    LocationName.seamus_winter_token: LocationData(base_location_id + 415, regn.hogs),
    LocationName.ron_underwear_token: LocationData(base_location_id + 416, regn.sal),
    LocationName.ron_wedding_token: LocationData(base_location_id + 417, regn.tshf),
    LocationName.waitress_luchino_token: LocationData(base_location_id + 418, regn.cafe),
    LocationName.petunia_green_coat_token: LocationData(base_location_id + 419, regn.cafe),
    LocationName.seamus_token: LocationData(base_location_id + 420, regn.bbf),
    LocationName.snatcher_token: LocationData(base_location_id + 421, regn.wild),
    LocationName.ron_green_shirt_token: LocationData(base_location_id + 422, regn.ghl),
    LocationName.neville_waiter_token: LocationData(base_location_id + 423, regn.divc),
    LocationName.xeno_wedding_token: LocationData(base_location_id + 424, regn.tent),
    LocationName.skeleton_token: LocationData(base_location_id + 425, regn.llf),
}

# 450 - 473
level_beaten_loc_table: Dict[str, LocationData] = {
    LocationName.dt_beat: LocationData(base_location_id + 450, regn.dt),
    LocationName.da_beat: LocationData(base_location_id + 451, regn.da),
    LocationName.foc_beat: LocationData(base_location_id + 452, regn.focf),
    LocationName.kd_beat: LocationData(base_location_id + 453, regn.kd),
    LocationName.agv_beat: LocationData(base_location_id + 454, regn.agv),
    LocationName.avt_beat: LocationData(base_location_id + 455, regn.avt),
    LocationName.oor_beat: LocationData(base_location_id + 456, regn.oorf),
    LocationName.jd_beat: LocationData(base_location_id + 457, regn.jd),
    LocationName.ansmc_beat: LocationData(base_location_id + 458, regn.ansmcf),
    LocationName.lh_beat: LocationData(base_location_id + 459, regn.lhf),
    LocationName.ff_beat: LocationData(base_location_id + 460, regn.fff),
    LocationName.thath_beat: LocationData(base_location_id + 461, regn.thathf),
    LocationName.tsh_beat: LocationData(base_location_id + 462, regn.tshf),
    LocationName.mim_beat: LocationData(base_location_id + 463, regn.mimf),
    LocationName.igd_beat: LocationData(base_location_id + 464, regn.igdf),
    LocationName.sal_beat: LocationData(base_location_id + 465, regn.sal),
    LocationName.ll_beat: LocationData(base_location_id + 466, regn.llf),
    LocationName.dob_beat: LocationData(base_location_id + 467, regn.dobf),
    LocationName.ttd_beat: LocationData(base_location_id + 468, regn.ttdf),
    LocationName.bts_beat: LocationData(base_location_id + 469, regn.btsf),
    LocationName.bb_beat: LocationData(base_location_id + 470, regn.bbf),
    LocationName.fiend_beat: LocationData(base_location_id + 471, regn.fiendf),
    LocationName.st_beat: LocationData(base_location_id + 472, regn.stf),
    LocationName.tfitp_beat: LocationData(base_location_id + 473, regn.tfitpf),
}

# 475 - 498
leve_sip_loc_table: Dict[str, LocationData] = {
    LocationName.dt_sip: LocationData(base_location_id + 475, regn.dt),
    LocationName.da_sip: LocationData(base_location_id + 476, regn.da),
    LocationName.foc_sip: LocationData(base_location_id + 477, regn.focf),
    LocationName.kd_sip: LocationData(base_location_id + 478, regn.kd),
    LocationName.agv_sip: LocationData(base_location_id + 479, regn.agv),
    LocationName.avt_sip: LocationData(base_location_id + 480, regn.avt),
    LocationName.oor_sip: LocationData(base_location_id + 481, regn.oorf),
    LocationName.jd_sip: LocationData(base_location_id + 482, regn.jd),
    LocationName.ansmc_sip: LocationData(base_location_id + 483, regn.ansmcf),
    LocationName.lh_sip: LocationData(base_location_id + 484, regn.lhf),
    LocationName.ff_sip: LocationData(base_location_id + 485, regn.fff),
    LocationName.thath_sip: LocationData(base_location_id + 486, regn.thathf),
    LocationName.tsh_sip: LocationData(base_location_id + 487, regn.tsh),
    LocationName.mim_sip: LocationData(base_location_id + 488, regn.mimf),
    LocationName.igd_sip: LocationData(base_location_id + 489, regn.igd),
    LocationName.sal_sip: LocationData(base_location_id + 490, regn.sal),
    LocationName.ll_sip: LocationData(base_location_id + 491, regn.ll),
    LocationName.dob_sip: LocationData(base_location_id + 492, regn.dob),
    LocationName.ttd_sip: LocationData(base_location_id + 493, regn.ttdf),
    LocationName.bts_sip: LocationData(base_location_id + 494, regn.bts),
    LocationName.bb_sip: LocationData(base_location_id + 495, regn.bbf),
    LocationName.fiend_sip: LocationData(base_location_id + 496, regn.fiend),
    LocationName.st_sip: LocationData(base_location_id + 497, regn.stf),
    LocationName.tfitp_sip: LocationData(base_location_id + 498, regn.tfitp),
}

# 499 - 538
hub_sip_loc_table: Dict[str, LocationData] = {
    LocationName.tent_sip: LocationData(base_location_id + 499, regn.tent),
    LocationName.wild_sip: LocationData(base_location_id + 500, regn.wild),
    LocationName.cafe_sip: LocationData(base_location_id + 501, regn.cafe),
    LocationName.lond_sip: LocationData(base_location_id + 502, regn.lond),
    LocationName.kcs_sip: LocationData(base_location_id + 503, regn.kcs),
    LocationName.hogspath_sip: LocationData(base_location_id + 504, regn.hogspath),
    LocationName.hogs_sip: LocationData(base_location_id + 505, regn.hogs),
    LocationName.hogstat_sip: LocationData(base_location_id + 506, regn.hogstat),
    LocationName.hogwpath_sip: LocationData(base_location_id + 507, regn.hogwpath),
    LocationName.herb_sip: LocationData(base_location_id + 508, regn.herb),
    LocationName.tg_sip: LocationData(base_location_id + 509, regn.tg),
    LocationName.quad_sip: LocationData(base_location_id + 510, regn.quad),
    LocationName.ror_sip: LocationData(base_location_id + 511, regn.ror),
    LocationName.wcs_sip: LocationData(base_location_id + 512, regn.wcs),
    LocationName.wc_sip: LocationData(base_location_id + 513, regn.wc),
    LocationName.gh_sip: LocationData(base_location_id + 514, regn.gh),
    LocationName.ghl_sip: LocationData(base_location_id + 515, regn.ghl),
    LocationName.lake_sip: LocationData(base_location_id + 516, regn.lake),
    # LocationName.qp_sip: LocationData(base_location_id + 517, regn.qp),
    LocationName.thest_sip: LocationData(base_location_id + 518, regn.thest),
    LocationName.ground_sip: LocationData(base_location_id + 519, regn.ground),
    LocationName.raven_sip: LocationData(base_location_id + 520, regn.raven),
    LocationName.gryf_sip: LocationData(base_location_id + 521, regn.gryf),
    LocationName.dormlob_sip: LocationData(base_location_id + 522, regn.dormlob),
    LocationName.ast_sip: LocationData(base_location_id + 523, regn.ast),
    LocationName.y6c_sip: LocationData(base_location_id + 524, regn.y6c),
    LocationName.y5c_sip: LocationData(base_location_id + 525, regn.y5c),
    LocationName.pot_sip: LocationData(base_location_id + 526, regn.pot),
    LocationName.div_sip: LocationData(base_location_id + 527, regn.div),
    LocationName.dada_sip: LocationData(base_location_id + 528, regn.dada),
    LocationName.divc_sip: LocationData(base_location_id + 529, regn.divc),
    LocationName.cl_sip: LocationData(base_location_id + 530, regn.cl),
    LocationName.stair_sip: LocationData(base_location_id + 531, regn.low_stair),
    LocationName.lib_sip: LocationData(base_location_id + 532, regn.lib),
    LocationName.foyer_sip: LocationData(base_location_id + 533, regn.foyer),
    LocationName.mm_sip: LocationData(base_location_id + 534, regn.mm),
    LocationName.knock_sip: LocationData(base_location_id + 535, regn.knock),
    LocationName.leaky_sip: LocationData(base_location_id + 536, regn.leaky),
    LocationName.www_sip: LocationData(base_location_id + 537, regn.www),
    # LocationName.diag_sip: LocationData(base_location_id + 538, regn.diag),
}

# 550 - 525
house_crest_loc_table: Dict[str, LocationData] = {
    # Gryff Crests
    LocationName.dt_gc: LocationData(base_location_id + 550, regn.dt),
    LocationName.da_gc: LocationData(base_location_id + 551, regn.da),
    LocationName.foc_gc: LocationData(base_location_id + 552, regn.focf),
    LocationName.kd_gc: LocationData(base_location_id + 553, regn.kd),
    LocationName.agv_gc: LocationData(base_location_id + 554, regn.agv),
    LocationName.avt_gc: LocationData(base_location_id + 555, regn.avt),
    LocationName.oor_gc: LocationData(base_location_id + 556, regn.oorf),
    LocationName.jd_gc: LocationData(base_location_id + 557, regn.jd),
    LocationName.ansmc_gc: LocationData(base_location_id + 558, regn.ansmcf),
    LocationName.lh_gc: LocationData(base_location_id + 559, regn.lhf),
    LocationName.ff_gc: LocationData(base_location_id + 560, regn.ff),
    LocationName.thath_gc: LocationData(base_location_id + 561, regn.thathf),
    LocationName.tsh_gc: LocationData(base_location_id + 562, regn.tsh),
    LocationName.mim_gc: LocationData(base_location_id + 563, regn.mim),
    LocationName.igd_gc: LocationData(base_location_id + 564, regn.igd),
    LocationName.sal_gc: LocationData(base_location_id + 565, regn.sal),
    LocationName.ll_gc: LocationData(base_location_id + 566, regn.ll),
    LocationName.dob_gc: LocationData(base_location_id + 567, regn.dob),
    LocationName.ttd_gc: LocationData(base_location_id + 568, regn.ttd),
    LocationName.bts_gc: LocationData(base_location_id + 569, regn.bts),
    LocationName.bb_gc: LocationData(base_location_id + 570, regn.bbf),
    LocationName.fiend_gc: LocationData(base_location_id + 571, regn.fiendf),
    LocationName.st_gc: LocationData(base_location_id + 572, regn.st),
    LocationName.tfitp_gc: LocationData(base_location_id + 573, regn.tfitpf),
    # Slyth Crests
    LocationName.dt_sc: LocationData(base_location_id + 574, regn.dt),
    LocationName.da_sc: LocationData(base_location_id + 575, regn.da),
    LocationName.foc_sc: LocationData(base_location_id + 576, regn.foc),
    LocationName.kd_sc: LocationData(base_location_id + 577, regn.kd),
    LocationName.agv_sc: LocationData(base_location_id + 578, regn.agv),
    LocationName.avt_sc: LocationData(base_location_id + 579, regn.avt),
    LocationName.oor_sc: LocationData(base_location_id + 580, regn.oorf),
    LocationName.jd_sc: LocationData(base_location_id + 581, regn.jd),
    LocationName.ansmc_sc: LocationData(base_location_id + 582, regn.ansmc),
    LocationName.lh_sc: LocationData(base_location_id + 583, regn.lhf),
    LocationName.ff_sc: LocationData(base_location_id + 584, regn.ff),
    LocationName.thath_sc: LocationData(base_location_id + 585, regn.thathf),
    LocationName.tsh_sc: LocationData(base_location_id + 586, regn.tsh),
    LocationName.mim_sc: LocationData(base_location_id + 587, regn.mimf),
    LocationName.igd_sc: LocationData(base_location_id + 588, regn.igdf),
    LocationName.sal_sc: LocationData(base_location_id + 589, regn.sal),
    LocationName.ll_sc: LocationData(base_location_id + 590, regn.ll),
    LocationName.dob_sc: LocationData(base_location_id + 591, regn.dobf),
    LocationName.ttd_sc: LocationData(base_location_id + 592, regn.ttdf),
    LocationName.bts_sc: LocationData(base_location_id + 593, regn.btsf),
    LocationName.bb_sc: LocationData(base_location_id + 594, regn.bb),
    LocationName.fiend_sc: LocationData(base_location_id + 595, regn.fiendf),
    LocationName.st_sc: LocationData(base_location_id + 596, regn.stf),
    LocationName.tfitp_sc: LocationData(base_location_id + 597, regn.tfitpf),
    # Raven Crests
    LocationName.dt_rc: LocationData(base_location_id + 598, regn.dt),
    LocationName.da_rc: LocationData(base_location_id + 599, regn.da),
    LocationName.foc_rc: LocationData(base_location_id + 600, regn.focf),
    LocationName.kd_rc: LocationData(base_location_id + 601, regn.kd),
    LocationName.agv_rc: LocationData(base_location_id + 602, regn.agv),
    LocationName.avt_rc: LocationData(base_location_id + 603, regn.avt),
    LocationName.oor_rc: LocationData(base_location_id + 604, regn.oor),
    LocationName.jd_rc: LocationData(base_location_id + 605, regn.jd),
    LocationName.ansmc_rc: LocationData(base_location_id + 606, regn.ansmc),
    LocationName.lh_rc: LocationData(base_location_id + 607, regn.lh),
    LocationName.ff_rc: LocationData(base_location_id + 608, regn.fff),
    LocationName.thath_rc: LocationData(base_location_id + 609, regn.thath),
    LocationName.tsh_rc: LocationData(base_location_id + 610, regn.tsh),
    LocationName.mim_rc: LocationData(base_location_id + 611, regn.mim),
    LocationName.igd_rc: LocationData(base_location_id + 612, regn.igd),
    LocationName.sal_rc: LocationData(base_location_id + 613, regn.sal),
    LocationName.ll_rc: LocationData(base_location_id + 614, regn.llf),
    LocationName.dob_rc: LocationData(base_location_id + 615, regn.dobf),
    LocationName.ttd_rc: LocationData(base_location_id + 616, regn.ttdf),
    LocationName.bts_rc: LocationData(base_location_id + 617, regn.btsf),
    LocationName.bb_rc: LocationData(base_location_id + 618, regn.bbf),
    LocationName.fiend_rc: LocationData(base_location_id + 619, regn.fiend),
    LocationName.st_rc: LocationData(base_location_id + 620, regn.stf),
    LocationName.tfitp_rc: LocationData(base_location_id + 621, regn.tfitpf),
    # Huffle Crests
    LocationName.dt_hc: LocationData(base_location_id + 622, regn.dt),
    LocationName.da_hc: LocationData(base_location_id + 623, regn.da),
    LocationName.foc_hc: LocationData(base_location_id + 624, regn.focf),
    LocationName.kd_hc: LocationData(base_location_id + 625, regn.kd),
    LocationName.agv_hc: LocationData(base_location_id + 626, regn.agv),
    LocationName.avt_hc: LocationData(base_location_id + 627, regn.avt),
    LocationName.oor_hc: LocationData(base_location_id + 628, regn.oorf),
    LocationName.jd_hc: LocationData(base_location_id + 629, regn.jd),
    LocationName.ansmc_hc: LocationData(base_location_id + 630, regn.ansmcf),
    LocationName.lh_hc: LocationData(base_location_id + 631, regn.lhf),
    LocationName.ff_hc: LocationData(base_location_id + 632, regn.fff),
    LocationName.thath_hc: LocationData(base_location_id + 633, regn.thathf),
    LocationName.tsh_hc: LocationData(base_location_id + 634, regn.tshf),
    LocationName.mim_hc: LocationData(base_location_id + 635, regn.mimf),
    LocationName.igd_hc: LocationData(base_location_id + 636, regn.igd),
    LocationName.sal_hc: LocationData(base_location_id + 637, regn.sal),
    LocationName.ll_hc: LocationData(base_location_id + 638, regn.llf),
    LocationName.dob_hc: LocationData(base_location_id + 639, regn.dob),
    LocationName.ttd_hc: LocationData(base_location_id + 640, regn.ttdf),
    LocationName.bts_hc: LocationData(base_location_id + 641, regn.bts),
    LocationName.bb_hc: LocationData(base_location_id + 642, regn.bbf),
    LocationName.fiend_hc: LocationData(base_location_id + 643, regn.fiendf),
    LocationName.st_hc: LocationData(base_location_id + 644, regn.stf),
    LocationName.tfitp_hc: LocationData(base_location_id + 645, regn.tfitp),
}

# 650 - 673
# House Crest Completed

# 675 - 698
true_wizard_loc_table: Dict[str, LocationData] = {
    LocationName.dt_tw: LocationData(base_location_id + 675, regn.dt),
    LocationName.da_tw: LocationData(base_location_id + 676, regn.da),
    LocationName.foc_tw: LocationData(base_location_id + 677, regn.focf),
    LocationName.kd_tw: LocationData(base_location_id + 678, regn.kd),
    LocationName.agv_tw: LocationData(base_location_id + 679, regn.agv),
    LocationName.avt_tw: LocationData(base_location_id + 680, regn.avt),
    LocationName.oor_tw: LocationData(base_location_id + 681, regn.oorf),
    LocationName.jd_tw: LocationData(base_location_id + 682, regn.jd),
    LocationName.ansmc_tw: LocationData(base_location_id + 683, regn.ansmcf),
    LocationName.lh_tw: LocationData(base_location_id + 684, regn.lhf),
    LocationName.ff_tw: LocationData(base_location_id + 685, regn.fff),
    LocationName.thath_tw: LocationData(base_location_id + 686, regn.thathf),
    LocationName.tsh_tw: LocationData(base_location_id + 687, regn.tshf),
    LocationName.mim_tw: LocationData(base_location_id + 688, regn.mimf),
    LocationName.igd_tw: LocationData(base_location_id + 689, regn.igdf),
    LocationName.sal_tw: LocationData(base_location_id + 690, regn.sal),
    LocationName.ll_tw: LocationData(base_location_id + 691, regn.llf),
    LocationName.dob_tw: LocationData(base_location_id + 692, regn.dobf),
    LocationName.ttd_tw: LocationData(base_location_id + 693, regn.ttdf),
    LocationName.bts_tw: LocationData(base_location_id + 694, regn.btsf),
    LocationName.bb_tw: LocationData(base_location_id + 695, regn.bbf),
    LocationName.fiend_tw: LocationData(base_location_id + 696, regn.fiendf),
    LocationName.st_tw: LocationData(base_location_id + 697, regn.stf),
    LocationName.tfitp_tw: LocationData(base_location_id + 698, regn.tfitpf),
}

# 700 - 715
bb_gb_loc_table: Dict[str, LocationData] = {
    LocationName.bb_gb1: LocationData(base_location_id + 700, regn.knock),
    LocationName.bb_gb2: LocationData(base_location_id + 701, regn.knock, 100000),
    LocationName.bb_gb3: LocationData(base_location_id + 702, regn.knock, 200000),
    LocationName.bb_gb4: LocationData(base_location_id + 703, regn.knock, 300000),
    LocationName.bb_gb5: LocationData(base_location_id + 704, regn.knock, 400000),
    LocationName.bb_gb6: LocationData(base_location_id + 705, regn.knock, 500000),
    LocationName.bb_gb7: LocationData(base_location_id + 706, regn.knock, 600000),
    LocationName.bb_gb8: LocationData(base_location_id + 707, regn.knock, 700000),
    LocationName.bb_gb9: LocationData(base_location_id + 708, regn.knock, 800000),
    LocationName.bb_gb10: LocationData(base_location_id + 709, regn.knock, 900000),
    LocationName.bb_gb11: LocationData(base_location_id + 710, regn.knock, 1000000),
    LocationName.bb_gb12: LocationData(base_location_id + 711, regn.knock, 1100000),
    LocationName.bb_gb13: LocationData(base_location_id + 712, regn.knock, 1200000),
    LocationName.bb_gb14: LocationData(base_location_id + 713, regn.knock, 1300000),
    LocationName.bb_gb15: LocationData(base_location_id + 714, regn.knock, 1400000),
    LocationName.bb_gb16: LocationData(base_location_id + 715, regn.knock, 1500000),
}

# 716 - 755
hub_gb_loc_table: Dict[str, LocationData] = {
    LocationName.tent_gb: LocationData(base_location_id + 716, regn.tent),
    LocationName.wild_gb: LocationData(base_location_id + 717, regn.wild),
    LocationName.cafe_gb: LocationData(base_location_id + 718, regn.cafe),
    LocationName.lond_gb: LocationData(base_location_id + 719, regn.lond),
    LocationName.kcs_gb: LocationData(base_location_id + 720, regn.kcs),
    LocationName.hogspath_gb: LocationData(base_location_id + 721, regn.hogspath),
    LocationName.hogs_gb: LocationData(base_location_id + 722, regn.hogs),
    LocationName.hogstat_gb: LocationData(base_location_id + 723, regn.hogstat),
    LocationName.hogwpath_gb: LocationData(base_location_id + 724, regn.hogwpath),
    LocationName.herb_gb: LocationData(base_location_id + 725, regn.herb),
    LocationName.tg_gb: LocationData(base_location_id + 726, regn.tg),
    LocationName.quad_gb: LocationData(base_location_id + 727, regn.quad),
    LocationName.ror_gb: LocationData(base_location_id + 728, regn.ror),
    # LocationName.wcs_gb: LocationData(base_location_id + 729, regn.wcs),
    LocationName.wc_gb: LocationData(base_location_id + 730, regn.wc),
    LocationName.gh_gb: LocationData(base_location_id + 731, regn.gh),
    LocationName.ghl_gb: LocationData(base_location_id + 732, regn.ghl),
    LocationName.lake_gb: LocationData(base_location_id + 733, regn.lake),
    LocationName.qp_gb: LocationData(base_location_id + 734, regn.qp),
    LocationName.thest_gb: LocationData(base_location_id + 735, regn.thest),
    LocationName.ground_gb: LocationData(base_location_id + 736, regn.ground),
    # LocationName.raven_gb: LocationData(base_location_id + 737, regn.raven),
    LocationName.gryf_gb: LocationData(base_location_id + 738, regn.gryf),
    LocationName.dormlob_gb: LocationData(base_location_id + 739, regn.dormlob),
    # LocationName.ast_gb: LocationData(base_location_id + 740, regn.ast),
    LocationName.y6c_gb: LocationData(base_location_id + 741, regn.y6c),
    LocationName.y5c_gb: LocationData(base_location_id + 742, regn.y5c),
    LocationName.pot_gb: LocationData(base_location_id + 743, regn.pot),
    LocationName.div_gb: LocationData(base_location_id + 744, regn.div),
    LocationName.dada_gb: LocationData(base_location_id + 745, regn.dada),
    LocationName.divc_gb: LocationData(base_location_id + 746, regn.divc),
    LocationName.cl_gb: LocationData(base_location_id + 747, regn.cl),
    LocationName.stair_gb: LocationData(base_location_id + 748, regn.mid_stair),
    LocationName.lib_gb: LocationData(base_location_id + 749, regn.lib),
    LocationName.foyer_gb: LocationData(base_location_id + 750, regn.foyer),
    LocationName.mm_gb: LocationData(base_location_id + 751, regn.mm),
    LocationName.knock_gb: LocationData(base_location_id + 752, regn.knock),
    LocationName.leaky_gb: LocationData(base_location_id + 753, regn.leaky),
    LocationName.www_gb: LocationData(base_location_id + 754, regn.www),
    LocationName.diag_gb: LocationData(base_location_id + 755, regn.diag),
}

# Red Brick Locations 900 - 939
red_brick_loc_table: Dict[str, LocationData] = {
    # LocationName.tent_rb: LocationData(base_location_id + 900, regn.tent),
    LocationName.wild_rb: LocationData(base_location_id + 901, regn.wild),
    # LocationName.cafe_rb: LocationData(base_location_id + 902, regn.cafe),
    LocationName.lond_rb: LocationData(base_location_id + 903, regn.lond),
    LocationName.kcs_rb: LocationData(base_location_id + 904, regn.kcs),
    LocationName.hogspath_rb: LocationData(base_location_id + 905, regn.hogspath),
    LocationName.hogs_rb: LocationData(base_location_id + 906, regn.hogs),
    LocationName.hogstat_rb: LocationData(base_location_id + 907, regn.hogstat),
    LocationName.hogwpath_rb: LocationData(base_location_id + 908, regn.hogwpath),
    # LocationName.herb_rb: LocationData(base_location_id + 909, regn.herb),
    # LocationName.tg_rb: LocationData(base_location_id + 910, regn.tg),
    LocationName.quad_rb: LocationData(base_location_id + 911, regn.quad),
    LocationName.ror_rb: LocationData(base_location_id + 912, regn.ror),
    # LocationName.wcs_rb: LocationData(base_location_id + 913, regn.wcs),
    LocationName.wc_rb: LocationData(base_location_id + 914, regn.wc),
    LocationName.gh_rb: LocationData(base_location_id + 915, regn.gh),
    LocationName.ghl_rb: LocationData(base_location_id + 916, regn.ghl),
    LocationName.lake_rb: LocationData(base_location_id + 917, regn.lake),
    # LocationName.qp_rb: LocationData(base_location_id + 918, regn.qp),
    LocationName.thest_rb: LocationData(base_location_id + 919, regn.thest),
    LocationName.ground_rb: LocationData(base_location_id + 920, regn.ground),
    # LocationName.raven_rb: LocationData(base_location_id + 921, regn.raven),
    # LocationName.gryf_rb: LocationData(base_location_id + 922, regn.gryf),
    # LocationName.dormlob_rb: LocationData(base_location_id + 923, regn.house),
    LocationName.ast_rb: LocationData(base_location_id + 924, regn.ast),
    # LocationName.y6c_rb: LocationData(base_location_id + 925, regn.y6c),
    # LocationName.y5c_rb: LocationData(base_location_id + 926, regn.y5c),
    # LocationName.pot_rb: LocationData(base_location_id + 927, regn.pot),
    LocationName.div_rb: LocationData(base_location_id + 928, regn.div),
    LocationName.dada_rb: LocationData(base_location_id + 929, regn.dada),
    LocationName.divc_rb: LocationData(base_location_id + 930, regn.divc),
    # LocationName.cl_rb: LocationData(base_location_id + 931, regn.cl),
    # LocationName.stair_rb: LocationData(base_location_id + 932, regn.low_stair),
    LocationName.lib_rb: LocationData(base_location_id + 933, regn.lib),
    # LocationName.foyer_rb: LocationData(base_location_id + 934, regn.foyer),
    # LocationName.mm_rb: LocationData(base_location_id + 935, regn.mm),
    # LocationName.knock_rb: LocationData(base_location_id + 936, regn.knock),
    # LocationName.leaky_rb: LocationData(base_location_id + 937, regn.leaky),
    # LocationName.www_rb: LocationData(base_location_id + 938, regn.www),
    # LocationName.diag_rb: LocationData(base_location_id + 939, regn.diag),
}

# Red Brick Purchases 950 - 973
red_brick_purch_table: Dict[str, LocationData] = {
    LocationName.com_spec_purch: LocationData(base_location_id + 950, regn.leaky, 1250),
    LocationName.adv_guide_purch: LocationData(base_location_id + 951, regn.leaky, 2500),
    LocationName.disguise_purch: LocationData(base_location_id + 952, regn.leaky, 5000),
    LocationName.carrot_wand_purch: LocationData(base_location_id + 953, regn.leaky, 10000),
    LocationName.super_strength_purch: LocationData(base_location_id + 954, regn.leaky, 75000, regn.wc),
    LocationName.char_token_detect_purch: LocationData(base_location_id + 955, regn.leaky, 250000, regn.div),
    LocationName.fall_rescue_purch: LocationData(base_location_id + 956, regn.leaky, 125000, regn.lib),
    LocationName.char_studs_purch: LocationData(base_location_id + 957, regn.leaky, 75000, regn.gh),
    LocationName.score_x2_purch: LocationData(base_location_id + 958, regn.leaky, 200000, regn.hogs),
    LocationName.score_x4_purch: LocationData(base_location_id + 959, regn.leaky, 400000, regn.kcs),
    LocationName.score_x6_purch: LocationData(base_location_id + 960, regn.leaky, 600000, regn.hogspath),
    LocationName.score_x8_purch: LocationData(base_location_id + 961, regn.leaky, 800000, regn.hogwpath),
    LocationName.score_x10_purch: LocationData(base_location_id + 962, regn.leaky, 1000000, regn.lake),
    LocationName.stud_mag_purch: LocationData(base_location_id + 963, regn.leaky, 250000, regn.ror),
    LocationName.regen_hearts_purch: LocationData(base_location_id + 964, regn.leaky, 50000, regn.thest),
    LocationName.extra_hears_purch: LocationData(base_location_id + 965, regn.leaky, 75000, regn.dada),
    LocationName.invincibility_purch: LocationData(base_location_id + 966, regn.leaky, 500000, regn.divc),
    LocationName.red_brick_detect_purch: LocationData(base_location_id + 967, regn.leaky, 250000, regn.hogstat),
    LocationName.crest_detect_purch: LocationData(base_location_id + 968, regn.leaky, 250000, regn.ghl),
    LocationName.gb_detect_purch: LocationData(base_location_id + 969, regn.leaky, 250000, regn.lond),
    LocationName.christmas_purch: LocationData(base_location_id + 970, regn.leaky, 80000, regn.wild),
    LocationName.ghost_studs_purch: LocationData(base_location_id + 971, regn.leaky, 99000, regn.quad),
    LocationName.fast_magic_purch: LocationData(base_location_id + 972, regn.leaky, 75000, regn.ast),
    LocationName.fast_dig_purch: LocationData(base_location_id + 973, regn.leaky, 60000, regn.ground),
}

# 975 - 1005
spell_loc_table: Dict[str, LocationData] = {
    # LocationName.wingard_purch: LocationData(base_location_id + 975, regn.www, 0),
    LocationName.slug_purch: LocationData(base_location_id + 976, regn.www, 500000),
    LocationName.rictu_purch: LocationData(base_location_id + 977, regn.www, 65000),
    LocationName.entomo_purch: LocationData(base_location_id + 978, regn.www, 80000),
    LocationName.taranta_purch: LocationData(base_location_id + 979, regn.www, 75000),
    LocationName.loco_purch: LocationData(base_location_id + 980, regn.www, 30000),
    LocationName.redact_purch: LocationData(base_location_id + 981, regn.www, 10000),
    LocationName.colo_purch: LocationData(base_location_id + 982, regn.www, 75000),
    LocationName.calvo_purch: LocationData(base_location_id + 983, regn.www, 20000),
    LocationName.anteo_purch: LocationData(base_location_id + 984, regn.www, 95000),
    LocationName.herbi_purch: LocationData(base_location_id + 985, regn.www, 15000),
    LocationName.glaci_purch: LocationData(base_location_id + 986, regn.www, 110000),
    LocationName.incarc_purch: LocationData(base_location_id + 987, regn.www, 100000),
    LocationName.expel_purch: LocationData(base_location_id + 988, regn.www, 10000),
    LocationName.flip_purch: LocationData(base_location_id + 989, regn.www, 125000),
    LocationName.trip_purch: LocationData(base_location_id + 990, regn.www, 40000),
    LocationName.stup_purch: LocationData(base_location_id + 991, regn.www, 150000),
    LocationName.transfig_purch: LocationData(base_location_id + 992, regn.www, 200000),
    LocationName.engorg_purch: LocationData(base_location_id + 993, regn.www, 10000),
    LocationName.immob_purch: LocationData(base_location_id + 994, regn.www, 400000),
    # LocationName.pets_purch: LocationData(base_location_id + 995, regn.www),
    # LocationName.invis_purch: LocationData(base_location_id + 996, regn.www),
    # # LocationName.avada_purch: LocationData(base_location_id + 997, regn.www),
    # LocationName.diffindo_purch: LocationData(base_location_id + 998, regn.y5c),
    # # LocationName.lumos_purch: LocationData(base_location_id + 999, regn.www),
    # lumos has 2 bits using second bit for polyjuice potion in the Dictionary
    # LocationName.agua_purch: LocationData(base_location_id + 1002, regn.y6c),
    # LocationName.focus_purch: LocationData(base_location_id + 1003, regn.cl),
    # LocationName.expecto_purch: LocationData(base_location_id + 1004, regn.ror),
    # LocationName.reducto_purch: LocationData(base_location_id + 1005, regn.y6c),
}

hub_progress_loc_table: Dict[str, LocationData] = {
    LocationName.poly_purch: LocationData(base_location_id + 1000, regn.tsh),
    LocationName.delum_lesson: LocationData(base_location_id + 1001, regn.tsh),
    LocationName.y5_hogwarts: LocationData(base_location_id + 1006, regn.hogwpath),
    LocationName.dada_lesson: LocationData(base_location_id + 1007, regn.dada),
    LocationName.thestral_lesson: LocationData(base_location_id + 1008, regn.thest),
    LocationName.dueling_lesson: LocationData(base_location_id + 1009, regn.ror),
    LocationName.diffindo_lesson: LocationData(base_location_id + 1010, regn.y5c),
    LocationName.patroneous_lesson: LocationData(base_location_id + 1011, regn.ror),
    LocationName.grawp_lesson: LocationData(base_location_id + 1012, regn.ground),
    LocationName.focus_lesson: LocationData(base_location_id + 1013, regn.cl),
    LocationName.owls_lesson: LocationData(base_location_id + 1014, regn.wc),
    LocationName.y5_story_complete: LocationData(base_location_id + 1015, regn.wc),
    LocationName.specs_lesson: LocationData(base_location_id + 1016, regn.hogstat),
    LocationName.y6_hogwarts: LocationData(base_location_id + 1017, regn.hogwpath),
    LocationName.draught_lesson: LocationData(base_location_id + 1018, regn.pot),
    LocationName.vial_lesson: LocationData(base_location_id + 1019, regn.dumble_office),
    LocationName.agua_lesson: LocationData(base_location_id + 1020, regn.y6c),
    LocationName.reducto_lesson: LocationData(base_location_id + 1021, regn.y5c),
    LocationName.dumble_lesson: LocationData(base_location_id + 1022, regn.dumble_office),
    LocationName.y6_story_complete: LocationData(base_location_id + 1023, regn.dumble_office),
    # LocationName.delum_lesson: LocationData(base_location_id + 1024, regn.tsh),
    LocationName.bag_lesson: LocationData(base_location_id + 1025, regn.tshf),
    LocationName.apparition_lesson: LocationData(base_location_id + 1026, regn.tshf),
    LocationName.cafe_lesson: LocationData(base_location_id + 1027, regn.cafe),
}

hub_event_loc_table: Dict[str, LocationData] = {
    LocationName.y5_hogwarts_event: LocationData(0, regn.hogwpath),
    LocationName.dada_lesson_event: LocationData(0, regn.dada),
    LocationName.thestral_lesson_event: LocationData(0, regn.thest),
    LocationName.dueling_lesson_event: LocationData(0, regn.ror),
    LocationName.diffindo_lesson_event: LocationData(0, regn.y5c),
    LocationName.patroneous_lesson_event: LocationData(0, regn.ror),
    LocationName.grawp_lesson_event: LocationData(0, regn.ground),
    LocationName.focus_lesson_event: LocationData(0, regn.cl),
    LocationName.owls_lesson_event: LocationData(0, regn.wc),
    LocationName.y5_story_complete_event: LocationData(0, regn.wc),
    LocationName.specs_lesson_event: LocationData(0, regn.hogstat),
    LocationName.y6_hogwarts_event: LocationData(0, regn.hogwpath),
    LocationName.draught_lesson_event: LocationData(0, regn.pot),
    LocationName.vial_lesson_event: LocationData(0, regn.dumble_office),
    LocationName.agua_lesson_event: LocationData(0, regn.y6c),
    LocationName.reducto_lesson_event: LocationData(0, regn.y5c),
    LocationName.dumble_lesson_event: LocationData(0, regn.dumble_office),
    LocationName.y6_story_complete_event: LocationData(0, regn.dumble_office),
    # LocationName.delum_lesson_event: LocationData(0, regn.tshf),
    # LocationName.bag_lesson_event: LocationData(0, regn.tshf),
    # LocationName.apparition_lesson_event: LocationData(0, regn.tshf),
    LocationName.cafe_lesson_event: LocationData(0, regn.cafe),
}

all_location_table = {
    **character_location_table,
    **character_token_location_table,
    **spell_loc_table,
    **level_beaten_loc_table,
    **leve_sip_loc_table,
    **hub_sip_loc_table,
    **house_crest_loc_table,
    **true_wizard_loc_table,
    **bb_gb_loc_table,
    **hub_gb_loc_table,
    **red_brick_loc_table,
    **red_brick_purch_table,
    **hub_progress_loc_table,
}


def setup_locations(options: LHP2Options):
    temp_location_table: Dict[str, LocationData] = {
        **level_beaten_loc_table,
        **leve_sip_loc_table,
        **hub_sip_loc_table,
        **house_crest_loc_table,
        **true_wizard_loc_table,
        **hub_gb_loc_table,
        **hub_progress_loc_table,
    }

    if options.ShuffleCharacterTokens == 0:
        temp_location_table.update(character_location_table)
        temp_location_table.update(character_token_location_table)

    if options.ShuffleCharacterTokens == 1:
        temp_location_table.update(character_token_location_table)

    if options.ShuffleCharacterTokens == 2:
        temp_location_table.update(character_location_table)

    if options.ShuffleRedBricks == 0:
        temp_location_table.update(red_brick_loc_table)
        temp_location_table.update(red_brick_purch_table)

    if options.ShuffleRedBricks == 1:
        temp_location_table.update(red_brick_loc_table)

    if options.ShuffleRedBricks == 2:
        temp_location_table.update(red_brick_purch_table)

    if options.ShuffleJokeSpells == 1:
        temp_location_table.update(spell_loc_table)

    if options.ShuffleGoldBrickPurchases == 1:
        temp_location_table.update(bb_gb_loc_table)

    disabled = set(options.DisabledLevels.value)

    # Remove disabled regions (normal + freeplay)
    for location, data in list(temp_location_table.items()):
        region = data.region
        if region in disabled or region.endswith(" Freeplay") and region[:-9] in disabled:
            del temp_location_table[location]

    return temp_location_table


location_name_groups = {
    regn.dt: {name for name, data in all_location_table.items() if data.region == regn.dt},
    regn.da: {name for name, data in all_location_table.items() if data.region == regn.da},
    regn.foc: {name for name, data in all_location_table.items()
               if data.region == regn.foc or data.region == regn.focf},
    regn.kd: {name for name, data in all_location_table.items() if data.region == regn.kd},
    regn.agv: {name for name, data in all_location_table.items() if data.region == regn.agv},
    regn.avt: {name for name, data in all_location_table.items() if data.region == regn.avt},
    regn.oor: {name for name, data in all_location_table.items()
               if data.region == regn.oor or data.region == regn.oorf},
    regn.jd: {name for name, data in all_location_table.items() if data.region == regn.jd},
    regn.ansmc: {name for name, data in all_location_table.items()
                 if data.region == regn.ansmc or data.region == regn.ansmcf},
    regn.lh: {name for name, data in all_location_table.items()
              if data.region == regn.lh or data.region == regn.lhf},
    regn.ff: {name for name, data in all_location_table.items()
              if data.region == regn.ff or data.region == regn.fff},
    regn.thath: {name for name, data in all_location_table.items()
                 if data.region == regn.thath or data.region == regn.thathf},
    regn.tsh: {name for name, data in all_location_table.items()
               if data.region == regn.tsh or data.region == regn.tshf},
    regn.mim: {name for name, data in all_location_table.items()
               if data.region == regn.mim or data.region == regn.mimf},
    regn.igd: {name for name, data in all_location_table.items()
               if data.region == regn.igd or data.region == regn.igdf},
    regn.sal: {name for name, data in all_location_table.items() if data.region == regn.sal},
    regn.ll: {name for name, data in all_location_table.items()
              if data.region == regn.ll or data.region == regn.llf},
    regn.dob: {name for name, data in all_location_table.items()
               if data.region == regn.dob or data.region == regn.dobf},
    regn.ttd: {name for name, data in all_location_table.items()
               if data.region == regn.ttd or data.region == regn.ttdf},
    regn.bts: {name for name, data in all_location_table.items()
               if data.region == regn.bts or data.region == regn.btsf},
    regn.bb: {name for name, data in all_location_table.items()
              if data.region == regn.bb or data.region == regn.bbf},
    regn.fiend: {name for name, data in all_location_table.items()
                 if data.region == regn.fiend or data.region == regn.fiendf},
    regn.st: {name for name, data in all_location_table.items()
              if data.region == regn.st or data.region == regn.stf},
    regn.tfitp: {name for name, data in all_location_table.items()
                 if data.region == regn.tfitp or data.region == regn.tfitpf},
}
