# Character Definitions

# Character Token Definitions

# Spell & Ability Definitions

# Joke Spell Definitions

# Level Unlock Definitions
dt_unlock = "Dark Times: Level Unlocked"
da_unlock = "Dumbledore's Army: Level Unlocked"
foc_unlock = "Focus!: Level Unlocked"
kd_unlock = "Kreacher Discomforts: Level Unlocked"
agv_unlock = "A Giant Virtuoso: Level Unlocked"
avt_unlock = "A Veiled Threat: Level Unlocked"
oor_unlock = "Out of Retirement: Level Unlocked"
jd_unlock = "Just Desserts: Level Unlocked"
ansmc_unlock = "A Not So Merry Christmas: Level Unlocked"
lh_unlock = "Love Hurts: Level Unlocked"
ff_unlock = "Felix Felicis: Level Unlocked"
thath_unlock = "The Horcrux and the Hand: Level Unlocked"
tsh_unlock = "The Seven Harrys: Level Unlocked"
mim_unlock = "Magic is Might: Level Unlocked"
igd_unlock = "In Grave Danger: Level Unlocked"
sal_unlock = "Sword and Locket: Level Unlocked"
ll_unlock = "Lovegood's Lunacy: Level Unlocked"
dob_unlock = "DOBBY!: Level Unlocked"
ttd_unlock = "The Thief's Downfall: Level Unlocked"
bts_unlock = "Back to School: Level Unlocked"
bb_unlock = "Burning Bridges: Level Unlocked"
fiend_unlock = "Fiendfyre Frenzy: Level Unlocked"
st_unlock = "Snape's Tears: Level Unlocked"
tfitp_unlock = "The Flaw in the Plan: Level Unlocked"

# Student In Peril Definitions
dt_sip = "Dark Times: Student in Peril"
da_sip = "Dumbledore's Army: Student in Peril"
foc_sip = "Focus!: Student in Peril"
kd_sip = "Kreacher Discomforts: Student in Peril"
agv_sip = "A Giant Virtuoso: Student in Peril"
avt_sip = "A Veiled Threat: Student in Peril"
oor_sip = "Out of Retirement: Student in Peril"
jd_sip = "Just Desserts: Student in Peril"
ansmc_sip = "A Not So Merry Christmas: Student in Peril"
lh_sip = "Love Hurts: Student in Peril"
ff_sip = "Felix Felicis: Student in Peril"
thath_sip = "The Horcrux and the Hand: Student in Peril"
tsh_sip = "The Seven Harrys: Student in Peril"
mim_sip = "Magic is Might: Student in Peril"
igd_sip = "In Grave Danger: Student in Peril"
sal_sip = "Sword and Locket: Student in Peril"
ll_sip = "Lovegood's Lunacy: Student in Peril"
dob_sip = "DOBBY!: Student in Peril"
ttd_sip = "The Thief's Downfall: Student in Peril"
bts_sip = "Back to School: Student in Peril"
bb_sip = "Burning Bridges: Student in Peril"
fiend_sip = "Fiendfyre Frenzy: Student in Peril"
st_sip = "Snape's Tears: Student in Peril"
tfitp_sip = "The Flaw in the Plan: Student in Peril"

# House Crest Definitions
dt_gc = "Dark Times: Gryffindor Crest"
dt_sc = "Dark Times: Slytherin Crest"
dt_rc = "Dark Times: Ravenclaw Crest"
dt_hc = "Dark Times: Hufflepuff Crest"
da_gc = "Dumbledore's Army: Gryffindor Crest"
da_sc = "Dumbledore's Army: Slytherin Crest"
da_rc = "Dumbledore's Army: Ravenclaw Crest"
da_hc = "Dumbledore's Army: Hufflepuff Crest"
foc_gc = "Focus!: Gryffindor Crest"
foc_sc = "Focus!: Slytherin Crest"
foc_rc = "Focus!: Ravenclaw Crest"
foc_hc = "Focus!: Hufflepuff Crest"
kd_gc = "Kreacher Discomforts: Gryffindor Crest"
kd_sc = "Kreacher Discomforts: Slytherin Crest"
kd_rc = "Kreacher Discomforts: Ravenclaw Crest"
kd_hc = "Kreacher Discomforts: Hufflepuff Crest"
agv_gc = "A Giant Virtuoso: Gryffindor Crest"
agv_sc = "A Giant Virtuoso: Slytherin Crest"
agv_rc = "A Giant Virtuoso: Ravenclaw Crest"
agv_hc = "A Giant Virtuoso: Hufflepuff Crest"
avt_gc = "A Veiled Threat: Gryffindor Crest"
avt_sc = "A Veiled Threat: Slytherin Crest"
avt_rc = "A Veiled Threat: Ravenclaw Crest"
avt_hc = "A Veiled Threat: Hufflepuff Crest"
oor_gc = "Out of Retirement: Gryffindor Crest"
oor_sc = "Out of Retirement: Slytherin Crest"
oor_rc = "Out of Retirement: Ravenclaw Crest"
oor_hc = "Out of Retirement: Hufflepuff Crest"
jd_gc = "Just Desserts: Gryffindor Crest"
jd_sc = "Just Desserts: Slytherin Crest"
jd_rc = "Just Desserts: Ravenclaw Crest"
jd_hc = "Just Desserts: Hufflepuff Crest"
ansmc_gc = "A Not So Merry Christmas: Gryffindor Crest"
ansmc_sc = "A Not So Merry Christmas: Slytherin Crest"
ansmc_rc = "A Not So Merry Christmas: Ravenclaw Crest"
ansmc_hc = "A Not So Merry Christmas: Hufflepuff Crest"
lh_gc = "Love Hurts: Gryffindor Crest"
lh_sc = "Love Hurts: Slytherin Crest"
lh_rc = "Love Hurts: Ravenclaw Crest"
lh_hc = "Love Hurts: Hufflepuff Crest"
ff_gc = "Felix Felicis: Gryffindor Crest"
ff_sc = "Felix Felicis: Slytherin Crest"
ff_rc = "Felix Felicis: Ravenclaw Crest"
ff_hc = "Felix Felicis: Hufflepuff Crest"
thath_gc = "The Horcrux and the Hand: Gryffindor Crest"
thath_sc = "The Horcrux and the Hand: Slytherin Crest"
thath_rc = "The Horcrux and the Hand: Ravenclaw Crest"
thath_hc = "The Horcrux and the Hand: Hufflepuff Crest"
tsh_gc = "The Seven Harrys: Gryffindor Crest"
tsh_sc = "The Seven Harrys: Slytherin Crest"
tsh_rc = "The Seven Harrys: Ravenclaw Crest"
tsh_hc = "The Seven Harrys: Hufflepuff Crest"
mim_gc = "Magic is Might: Gryffindor Crest"
mim_sc = "Magic is Might: Slytherin Crest"
mim_rc = "Magic is Might: Ravenclaw Crest"
mim_hc = "Magic is Might: Hufflepuff Crest"
igd_gc = "In Grave Danger: Gryffindor Crest"
igd_sc = "In Grave Danger: Slytherin Crest"
igd_rc = "In Grave Danger: Ravenclaw Crest"
igd_hc = "In Grave Danger: Hufflepuff Crest"
sal_gc = "Sword and Locket: Gryffindor Crest"
sal_sc = "Sword and Locket: Slytherin Crest"
sal_rc = "Sword and Locket: Ravenclaw Crest"
sal_hc = "Sword and Locket: Hufflepuff Crest"
ll_gc = "Lovegood's Lunacy: Gryffindor Crest"
ll_sc = "Lovegood's Lunacy: Slytherin Crest"
ll_rc = "Lovegood's Lunacy: Ravenclaw Crest"
ll_hc = "Lovegood's Lunacy: Hufflepuff Crest"
dob_gc = "DOBBY!: Gryffindor Crest"
dob_sc = "DOBBY!: Slytherin Crest"
dob_rc = "DOBBY!: Ravenclaw Crest"
dob_hc = "DOBBY!: Hufflepuff Crest"
ttd_gc = "The Thief's Downfall: Gryffindor Crest"
ttd_sc = "The Thief's Downfall: Slytherin Crest"
ttd_rc = "The Thief's Downfall: Ravenclaw Crest"
ttd_hc = "The Thief's Downfall: Hufflepuff Crest"
bts_gc = "Back to School: Gryffindor Crest"
bts_sc = "Back to School: Slytherin Crest"
bts_rc = "Back to School: Ravenclaw Crest"
bts_hc = "Back to School: Hufflepuff Crest"
bb_gc = "Burning Bridges: Gryffindor Crest"
bb_sc = "Burning Bridges: Slytherin Crest"
bb_rc = "Burning Bridges: Ravenclaw Crest"
bb_hc = "Burning Bridges: Hufflepuff Crest"
fiend_gc = "Fiendfyre Frenzy: Gryffindor Crest"
fiend_sc = "Fiendfyre Frenzy: Slytherin Crest"
fiend_rc = "Fiendfyre Frenzy: Ravenclaw Crest"
fiend_hc = "Fiendfyre Frenzy: Hufflepuff Crest"
st_gc = "Snape's Tears: Gryffindor Crest"
st_sc = "Snape's Tears: Slytherin Crest"
st_rc = "Snape's Tears: Ravenclaw Crest"
st_hc = "Snape's Tears: Hufflepuff Crest"
tfitp_gc = "The Flaw in the Plan: Gryffindor Crest"
tfitp_sc = "The Flaw in the Plan: Slytherin Crest"
tfitp_rc = "The Flaw in the Plan: Ravenclaw Crest"
tfitp_hc = "The Flaw in the Plan: Hufflepuff Crest"

# Completed House Crest Definitions
dt_hcgb = "Dark Times: House Crest Gold Brick"
da_hcgb = "Dumbledore's Army: House Crest Gold Brick"
foc_hcgb = "Focus!: House Crest Gold Brick"
kd_hcgb = "Kreacher Discomforts: House Crest Gold Brick"
agv_hcgb = "A Giant Virtuoso: House Crest Gold Brick"
avt_hcgb = "A Veiled Threat: House Crest Gold Brick"
oor_hcgb = "Out of Retirement: House Crest Gold Brick"
jd_hcgb = "Just Desserts: House Crest Gold Brick"
ansmc_hcgb = "A Not So Merry Christmas: House Crest Gold Brick"
lh_hcgb = "Love Hurts: House Crest Gold Brick"
ff_hcgb = "Felix Felicis: House Crest Gold Brick"
thath_hcgb = "The Horcrux and the Hand: House Crest Gold Brick"
tsh_hcgb = "The Seven Harrys: House Crest Gold Brick"
mim_hcgb = "Magic is Might: House Crest Gold Brick"
igd_hcgb = "In Grave Danger: House Crest Gold Brick"
sal_hcgb = "Sword and Locket: House Crest Gold Brick"
ll_hcgb = "Lovegood's Lunacy: House Crest Gold Brick"
dob_hcgb = "DOBBY!: House Crest Gold Brick"
ttd_hcgb = "The Thief's Downfall: House Crest Gold Brick"
bts_hcgb = "Back to School: House Crest Gold Brick"
bb_hcgb = "Burning Bridges: House Crest Gold Brick"
fiend_hcgb = "Fiendfyre Frenzy: House Crest Gold Brick"
st_hcgb = "Snape's Tears: House Crest Gold Brick"
tfitp_hcgb = "The Flaw in the Plan: House Crest Gold Brick"

# Gold Brick Definitions

# Gold Brick Purchase Definitions

# Red Brick Definitions

# Red Brick Purchase Definitions

# True Status Definitions
dt_tw = "Dark Times: True Wizard"
da_tw = "Dumbledore's Army: True Wizard"
foc_tw = "Focus!: True Wizard"
kd_tw = "Kreacher Discomforts: True Wizard"
agv_tw = "A Giant Virtuoso: True Wizard"
avt_tw = "A Veiled Threat: True Wizard"
oor_tw = "Out of Retirement: True Wizard"
jd_tw = "Just Desserts: True Wizard"
ansmc_tw = "A Not So Merry Christmas: True Wizard"
lh_tw = "Love Hurts: True Wizard"
ff_tw = "Felix Felicis: True Wizard"
thath_tw = "The Horcrux and the Hand: True Wizard"
tsh_tw = "The Seven Harrys: True Wizard"
mim_tw = "Magic is Might: True Wizard"
igd_tw = "In Grave Danger: True Wizard"
sal_tw = "Sword and Locket: True Wizard"
ll_tw = "Lovegood's Lunacy: True Wizard"
dob_tw = "DOBBY!: True Wizard"
ttd_tw = "The Thief's Downfall: True Wizard"
bts_tw = "Back to School: True Wizard"
bb_tw = "Burning Bridges: True Wizard"
fiend_tw = "Fiendfyre Frenzy: True Wizard"
st_tw = "Snape's Tears: True Wizard"
tfitp_tw = "The Flaw in the Plan: True Wizard"
